### ISSUE TITLE
compile on centos

### ISSUE THREAD

**Issue by makemoneystuff** [dogecoin/dogecoin#1001]
Hi i try to compile by this way: http://www.liquidweb.com/kb/install-dogecoin-wallet-on-centos/

the version 1.5 i installed and done, but this version 1.8 i get a error "on the step of ""make -f makefile.unix USE_UPNP=- BDB_LIB_PATH=/usr/local/lib OPENSSL_LIB_PATH=/usr/local/lib64""""

Please if someone can guide me to install this version on centos 6 64bit i will be very gratefull.

Thanks

**Comment by patricklodder** [comment]
I updated my [centos build gist](https://gist.github.com/patricklodder/c7c067cc831f0d3190c2) for 1.8.2. This script installs dogecoind and dogecoin-cli in userspace with proper openssl, boost and berkdb versions. For build dependency install you need root, so as root do:

```bash
yum update
yum -y groupinstall "Development Tools"
yum -y install wget

# add user
useradd -m -s/bin/bash doge
su - doge

# get script & build dogecoind and dogecoin-cli
wget -O build-dogecoin-1.8.2.sh https://gist.githubusercontent.com/patricklodder/c7c067cc831f0d3190c2/raw/59d3e63cda20e80560141043b34d23a6d434ccff/build-dogecoin.sh
sh build-dogecoin-1.8.2.sh 
```

after this, you can find your binaries in ```~/dogecoin/```, there are some vars to change this at the top of the ```build-dogecoin-1.8.2.sh``` file 

Hope this helps :)

PS: please note that since there are issues with the main openssl source download archives right now, I (temporarily) changed the openssl download location to use switch.ch's ftp mirror.

**Comment by makemoneystuff** [comment]
Hello patricklodder, very thanks, it worked very fine. Please leave your dogecoin here to i sent some for your help.

**Comment by patricklodder** [comment]
Most welcome. The dev fund address is 9x9zSN9vx3Kf9B4ofwzEfWgiqxwBieCNEb :)

**Comment by makemoneystuff** [comment]
Hi, send 100000 doge, Really very thanks, I passed 2 weeks brake my brain to install it and always get error, with your .sh it install and done in 10 minutes :)

Best Regards

**Comment by patricklodder** [comment]
Much appreciated! Thank you.
