### ISSUE TITLE
0 fee and <1 fee transactions confirmed

### ISSUE THREAD

**Issue by peoplma** [dogecoin/dogecoin#1260]
To replicate, click choose transaction fee option in the sending screen in 1.10, checkbox "send as 0 fee transaction if possible".  I guess in bitcoin, miners are set up to ignore 0 fee transactions, I don't think people mining scrypt have configured that.  But, shouldn't 0 fee transactions not be relayed by nodes?

All were confirmed in the next block:

0 fee:

https://dogechain.info/tx/284e43e34299479748315fd3dc3b0ba7535fd30dbfb4b2c87a20c7f772042bfb

https://dogechain.info/tx/d986fec32ffcdade4f8b502ca5ef600046de3c7687bfabc48f3dd0a19dfebe26

https://dogechain.info/tx/de24af5ca2f6f9ea6c9445defcb81222f5ad643ec4c31b78b2a3a57f55ce42bb

<1Ð fee:

https://dogechain.info/tx/bd69fdb13e09c693667cfedcc29c61e5e56288e662c3d8f7040f170a885beab9

https://dogechain.info/tx/e39a41deae7e4556c4a559553cbbf8f255f07444cf2ab115744641fd858f264d

https://dogechain.info/tx/f6ace5daf3eb6fe8a908208a49b7d550ea078b0b391ff730623f05e3d85f5746

**Comment by patricklodder** [comment]
Thank you very much for the find, I didn't even get to testing that yet. 2 things to note here:

1. Relay and mempool acceptance is a policy local to a node, so any node can choose to implement a different policy than what we recommend (though prior to this version, it would require a code patch.) For example the blockexplorers run nodes that will not accept a transaction with insufficient fees.
2. For compatibility, and not having a ton of people with dead transactions in their wallet, we have never set relay of 0-fee transactions to be rejected, we've only done that for sending transactions (which is the process of broadcasting a transaction that was created locally.) And for the wallet we've previously set the minimum fee to 1 doge (so that no low-fee transactions will be created.)

I feel we need to review Dogecoin fee structure in general, but I don't want to do it for this release, as we have enough changes to worry about, so I think the best course of action would be to patch 1.7-style fees back in and work on a new fee structure as part of 1.10.1. I also distilled from @langerhans comments on other big changes that he wants to aim for best compatibility with this release (would like to see a confirm on that btw.)

**Comment by langerhans** [comment]
>would like to see a confirm on that btw.  

Can confirm. I think it's sensible that we should not introduce big changes in a release that is a big change in itself due to being a complete rework/refactor of how we introduce Dogeocin customizations into upstream code. This is enough to get right and test already so that I'd be very careful about introducing more changes, especially if they turn out to be controversial and may need several design iterations (Talking about fee structure in general, not specifically implementation).  

From looking at the logs of my node I see 1.10 will happily reject 0 fee transactions at the moment. This should be changed to our default before, at least for 1.10. We should check if the transaction creation policy is strict enough to reduce the overall amount of free transactions from the source. That way (in hopes of large adoption of 1.10 until 1.1X) it will "hurt" less to stop relaying the free transactions (or whatever the model we designed by then supports).

**Comment by patricklodder** [comment]
#1276 fixes this

**Comment by patricklodder** [comment]
Fixed
