### ISSUE TITLE
Why don't we add Distributed computing function into dogecoin?

### ISSUE THREAD

**Issue by tleydxdy** [dogecoin/dogecoin#1326]
People pay coins for computing power. 

More rooms for general computer. 

I think this will add much more power to dogecoin.

**Comment by langerhans** [comment]
Keep in mind the computing power has to actually also build the blockchain, which it does by computing useless stuff. But then again this useless stuff has a very distinct attributes that make the blockchain work as it does. General computing doesn't necessarily do this.   

Also distributed computing as you imagine it has very specific use cases as of now and it won't really let the normal user just "get" some computing power to do what normal users do. There are coins that tried it and they never took off any further than their initial pump&dump and that's it.

I think we should focus on real world usage and adoption and not some niche product ;) Closing this for now.

**Comment by rnicoll** [comment]
I wanted to expand on this a bit, because it comes up fairly frequently and it's worth going into the details on why this doesn't work.

Proof of work has to fulfil a number of basic requirements:

* It must be dependent on the previous block (work can only be done once the previous block is mined)
* It must be specific to the mined transactions (work cannot be used for a different set of transactions)
* It must be easy to verify
* It must not require any central authority to issue/verify

Most distributed computing projects (I say most - all I'm aware of) involve a central service issuing chunks of work, which are completed then returned to be checked. Many (i.e. SETI) are expensive to verify as well. None that I'm aware of readily support tying the work done to arbitrary extra data (in this case, previous block hash and merkle root of the transactions). I believe Gridcoin handles this by having a central authority that does hand out work and verify it when it's returned, but that's not really decentralised and goes against many of the ideas of cryptocurrency.
