### ISSUE TITLE
unable to build 1.10 on debian stable

### ISSUE THREAD

**Issue by dooglus** [dogecoin/dogecoin#1333]
What am I doing wrong?

    $ make
    Making all in src
    make[1]: Entering directory '/home/chris/Programs/dogecoin10/src'
    make[2]: Entering directory '/home/chris/Programs/dogecoin10/src'
      CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
    In file included from /usr/include/x86_64-linux-gnu/bits/byteswap.h:35:0,
                     from /usr/include/endian.h:60,
                     from /usr/include/x86_64-linux-gnu/bits/waitstatus.h:64,
                     from /usr/include/stdlib.h:42,
                     from ./crypto/ripemd160.h:9,
                     from crypto/ripemd160.cpp:5:
    ./compat/endian.h:111:17: error: expected unqualified-id before '__extension__'
     inline uint16_t htobe16(uint16_t host_16bits)

I'm on the 1.10-maint branch.

**Comment by langerhans** [comment]
If you've just checked out the branch in a directory where you built 1.8.x before, you need to `make clean` or even `make distclean` just to be extra sure. That should fix it. If not see if you have `src/config/bitcoin-config.h` and delete that too.

**Comment by dooglus** [comment]
I had `src/bitcoin-config.h` and `src/bitcoin-config.h.in` and had to delete those.

Thanks for getting me on the right track.

**Comment by langerhans** [comment]
Yeah, that's because it was moved into ./config/ so a make distclean will also try to delete it there and therefore miss the 1.8 generated one. if you want to get your repository super clean and have nothing to lose there you could also do `git clean -xfd` which will reset/delete everything that's different from the original repo (Also dependencies build with the dependency builder, so careful).

I guess I can close here then?
