### ISSUE TITLE
[Windows] 1.10.0 Memory Leak

### ISSUE THREAD

**Issue by cc7-f5-si** [dogecoin/dogecoin#1348]
Starting from the time of the block reading process, the physical and the sum of the virtual both of memory, resulting in a crash with no response yet been consumed in the moment more than 2GiB.
Delete all of the block to start normally if the refresh, but the memory will become more immediately 2GiB.

Also without effect re-installation and re-synchronization.

It should be noted, Furunodo of other coins, such as Bitcoin and Litecoin is, even if there block capacity is more than 60GiB, total memory usage of the appropriate process, normally stable operation for a long time in the following state 1GiB.

**Comment by patricklodder** [comment]
This has been fixed with #1338. There are windows builds of 1.10.1-alpha-1 available here:

[win32 setup](https://ipfs.io/ipfs/QmZKaASA6U4xmzFkFafb5SrHufoz2wuzyNSiaZGENECRZE/dogecoin-1.10.1-win32-setup-unsigned.exe) (sha256sum: `29882f1dd992d615c214dde2a45a9b9645576fbb320802da57b9f456285677c1`)
[win32 zip](https://ipfs.io/ipfs/QmZKaASA6U4xmzFkFafb5SrHufoz2wuzyNSiaZGENECRZE/dogecoin-1.10.1-win32.zip) (sha256sum: `f6b8f7cd6e88e74becbaa7440e364637366b470a2f013d2cc245ac51ad210766`)
[win64 setup](https://ipfs.io/ipfs/QmZKaASA6U4xmzFkFafb5SrHufoz2wuzyNSiaZGENECRZE/dogecoin-1.10.1-win64-setup-unsigned.exe) (sha256sum: `6d4d1009282410c95f50ba4c187ed8444d86e91af0ab34ea23094a28ae876b80`)
[win64 zip](https://ipfs.io/ipfs/QmZKaASA6U4xmzFkFafb5SrHufoz2wuzyNSiaZGENECRZE/dogecoin-1.10.1-win64.zip) (sha256sum: `908048812c33afea076742e6351375204a90625e3e44214bf374869fde6f315a`)

**Comment by MrRamych** [comment]
These links don't work

**Comment by patricklodder** [comment]
@MrRamych those should work again.
