### ISSUE TITLE
Vulnerability to spam transactions and dynamic blocksize solution 

### ISSUE THREAD

**Issue by TommyEconomics** [dogecoin/dogecoin#1352]
Hi guys, I've been part of the Dogecoin community since Feb 2014 and want to see Dogecoin prosper. I understand Dogecoin is vulnerable to a spam transaction attack in which an attacker could relatively cheap fill our blocks and by doing so create orphans and jeapordize our position with miners (which could severely harm our currency). I wanted to gauge how you guys feel about implementing a dynamic blocksize solution, it appears most of the code is already out there, a lot of the work would perhaps be coordinating with miners and exchanges, which I would be happy to help with or even lead if I needed to. Just wanted to see what you guys thought about implementing dynamic blocks.

Thanks in advance, 
Tommy

Edit add- Link to bitpay's Bitcoin dynamic blocksize proposal:
https://github.com/bitpay/bips/blob/master/bip-adaptiveblocksize.mediawiki

Edit add 2- I took a poll on the Dogecoin reddit, it seems the community overwhelmingly supports dynamic blocks (currently about 85% are for it, while only about 15% are for keeping blocks at 1mb). Here is a link to the poll: http://www.strawpoll.me/10818427

**Comment by peoplma** [comment]
To expand on what @TommyEconomics said, I'd be in favor of a dynamic max block size. As it is now, there is sort of an obscure vulnerability. Since dogecoin fees are so low, it would be extremely cheap (~1000 doge per minute) for someone to spam transactions and fill up blocks. Since doge is also fast, this is 2.5X the block size equivalent of litecoin and 10X of bitcoin. Our largest miner, F2Pool also mines litecoin and bitcoin. Having to propagate our 1MB blocks may have a negative impact on their orphan rate of bitcoin and litecoin blocks due to increased latency and bandwidth requirements. And block rewards for dogecoin are so small that the increase in orphan rate of those coins may be a larger financial hit for them than discontinuing mining dogecoin would be. So it's conceivable that they would stop mining dogecoin and leave us more vulnerable to 51%. Not just F2Pool either, all of our miners mine another coin as their primary source of income.

With a dynamic max blocksize, such as outlined by BitPay, miners would have much more time to respond to such an attack, depending on how quickly the max block size would adjust.  They could see in advance that it was happening and decide not to mine low fee transactions, for example.  Although that would probably cause real users trying to get transactions through problems if we don't have wallets with dynamic fees.

Another solution might be compact blocks or Xthin blocks to minimize block propagation bandwidth requirements, but these are of no use if the attacker is another miner.

So there is an argument to be made from a security standpoint for dynamic max block size for dogecoin.

**Comment by rnicoll** [comment]
Apologies for the delay, been pondering this. I'm cautious of pushing our total throughput higher, as @peoplma says, we're already at 10x Bitcoin.

How would you feel about increasing base fees for transactions, and/or using a fee market to effectively give us reactive transaction costing?

Max, Patrick, any thoughts either way?

**Comment by TommyEconomics** [comment]
We could increase base fees too, but what harm is there to moving to dynamic blocks? It seems the community is overwhelming in support of it and I think it's very likely it will have a positive impact on our price, as well as our PR. Plus it's a good long term move for Dogecoin, if we ever want to situate yourself to be prepared for the long term, just my thoughts, either way I appreciate your guys' hard work, thank you!

**Comment by langerhans** [comment]
>it's very likely it will have a positive impact on our price

To be honest I kinda stopped reading at that. Devs are not to implement features to fuel some price speculation. There are tons if coins out there that do that for their P&D schemes. Let's not focus on that bit.

>community is overwhelming in support  

That poll had 35 people to vote on it, from which I bet you 30 have not even read, or understood the BIP with all its implications. This is honestly no convincing argument either.

But that aside. We have seen stress tests of our network and they went really well. We can certainly push a lot more transactions than we do right now. Of course it might be "easy" to attack us with that, yes. But do you think the right solution would be to give the attacker more space to fill? The fee was raised back in times for exactly that reason. Just linearly raising the fee again might not be the best solution either. There should be some dynamic to it, to accommodate the threat model.  
The point is this: If an attacker can fill our blocks for 1000 DOGE per minute, then an attacker can fill a dynamic, 2MB large block for 2000 DOGE, thus making it even harder for miners to propagate the blocks. What does that solve? 1000 DOGE is $0.25 right now. If someone is determined to attack us by filling out blocks (which I honestly think is a laughable idea of the word "attack") then you could imagine they would happily also spend $0.50 to do the same, and that is only after the block size adjustment.

**Comment by peoplma** [comment]
A dynamic max block size wouldn't increase the max block size, it would lower it.

Let's say there were a minimum limit, like 100kB.  And we used the median of the past 1000 blocks to recalculate the next minimum limit, and the maximum it could adjust was up to 2X max block size.

Then an attacker would have to spam for 1000 blocks to get a max of 200kB.  And then again for 400kB.  And then again for 800kB.  These limits wouldn't harm the network, for sure.  But it would make it more expensive and more time consuming.  

Miners would be able to see it coming with plenty of time in advance, and they could adjust their policies.  Like increasing the minimum fee to include a transaction.

So it would be a deterrent to that type of attack.  With the added bonus that in the off chance we need the extra capacity for real transactions, we'd be able to scale.

As far as I understand, there's a max of 32MB no matter what the `MAX_BLOCK_SIZE` is due to database limitations, so a dynamic limit couldn't go above that anyway.

**Comment by TommyEconomics** [comment]
Well I appreciate your work langerhans, and I am not one to swim upriver, however, at this point I think it's worth considering whether we as a community want to evolve, or if we want to stay stagnant. I've posted in the Dogecoin subreddit and seems like a large population in our community wants to evolve. I'll put a link to the post below.

Bottom line is... whether we like it or not, we have gone nowhere in over 2 years, and other cryptocurrencies are passing us up technologically, and their communities are growing. If we are to remain stagnant, I fear we won't have much of a future (especially long term).

Link to my post here (90% upvoted, 93 votes):
https://www.reddit.com/r/dogecoin/comments/4u4d7y/is_dogecoin_really_going_to_refuse_to_evolve/


Best regards,
Tommy

**Comment by patricklodder** [comment]
> Bottom line is... whether we like it or not, we have gone nowhere in over 2 years, and other cryptocurrencies are passing us up technologically, and their communities are growing. If we are to remain stagnant, I fear we won't have much of a future (especially long term).

The problem that you raise is unfortunately in the meta of everything you argue here. Every change Dogecoin has undergone is there for only 2 reasons: 

1. The person(s) that **developed** it believed in the change enough to spend time on creating it, get the code quality to a level that was acceptable and get it merged.
2. Maintainers agreed with the change and it's quality, and merged it.

The former has always been the issue: there aren't people developing. The latter, I estimate 99%-ish of all proper quality PRs have been merged. Arguing for a change has never gotten anyone anywhere.

All you need to do is make a proper proposal in code and then you may argue for your change. Arguing before there is code is pointless as change is not made through lobbying around here, it is made through hard work.

I'm closing this, any further discussion can be done based on a PR :-)

**Comment by peoplma** [comment]
I was the one who recommended to Tommy opening an issue as the first step.  Since you 3 have the ultimate merge powers, I thought it would make sense to discuss whether or not such a change would be accepted or rejected, before someone put in the time to make a PR.  The spec was linked https://github.com/bitpay/bips/blob/master/bip-adaptiveblocksize.mediawiki.  If such a PR were made, would it be accepted, or would it be a waste of time coding it up for dogecoin?

**Comment by patricklodder** [comment]
I cannot tell if it would be accepted, and even then: I cannot tell if it would be accepted by a majority of miners. The only thing you can do is code it and see where it ends up. If the code is of good quality I will review it and test it.

There are a lot of prerequisites for that particular BIP to be merged, so you're looking at a very long path to merging on that one. At the very least it MUST at the very least be done after a #1340 release, then we need to introduce versionbits, after which we might be able to introduce it at it's own pace (ie: quickly).

Please, do realize that you are eliminating the ability to have another hype with this change; that is, if you want the anti-spam protection to have any meaningful parameters. If your hype will max out the network and it will take days to recover, after which it maxes out again and takes days to recover, your hype dies. If it doesn't take days to recover then the protection is meaningless. Make sure that you want that and while someone is coding it, I'll think about whether I want that :-)

**Comment by peoplma** [comment]
So theoretically that's a definite maybe then.  Thanks :)

**Comment by patricklodder** [comment]
Every line of consensus code here is the same: you'll only know whether it's going to work once you'll get that super-majority. There are no guarantees; if there were, we'd have a flaw. Thus, imho it's better to not ask for permission on a permission-less ecosystem: just go code it and see where it ends up!
