### ISSUE TITLE
Discussion: updated tooling and CI, now what?

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#1359]
Now that we've got a tooling update on 1.10-maint, what do we do with the master branch? The main idea of the master branch not following development is that it can just be checked out and compiled, but for that, 1.10-maint now needs to be checked out instead as compilation of depends is broken on master.

We really do not have any procedure for this, so how do we want to go from here:

- Do we update master without a release?
- Do we tag a source-only release?
- Do we just leave it like this?

TIA for your thoughts :-)

**Comment by patricklodder** [comment]
@langerhans / @rnicoll: 50D for your thoughts?

**Comment by langerhans** [comment]
Ohshit, sorry, I had that mail in my inbox to reply :/

Anyway. I would assume that since master is the default branch and any instructions to compile from any other branch would be too hidden, we should update master, tag a release but skip binary distribution as there are no changes at all so no need for that hassle on our or the user's side.

**Comment by rnicoll** [comment]
I'd back a source only release too

**Comment by langerhans** [comment]
Guess this won't be relevant anymore with 1.14 😅
