### ISSUE TITLE
the lightning network? 

### ISSUE THREAD

**Issue by briannyeko** [dogecoin/dogecoin#1382]
when are you getting the lightning network?

**Comment by RainbowAsteroids** [comment]
We don't need it. There have been many posts about this exact subject on /r/dogecoin.

**Comment by buddilla** [comment]
Actually you do if you want to do side chain atomic swaps

**Comment by briannyeko** [comment]
^this statement above.

**Comment by apobbati** [comment]
Yes. One of the features of Lightning network is to facilitate atomic swaps using cross-blockchains. E.g. send a merchant some dogecoin who only accepts bitcoin or litecoin.

**Comment by andre-amorim** [comment]
@briannyeko I like dogecoin as a didactic coin. Today my kids understand how the general conceptions of the blockchain because we played a lot with dogecoin. I do support to teach blockchain in schools. Dogecoin could be a nice tool on that direction. Although we need that dogecoin keep updated with bitcoin/litecoin code improvements.

**Comment by ReverseControl** [comment]
This is not an issue. Question like this one are better placed in the https://github.com/dogecoin/dogecoin/discussions section.
