### ISSUE TITLE
Rootstock(Smart Contracts)?

### ISSUE THREAD

**Issue by briannyeko** [dogecoin/dogecoin#1389]
Is it possible for Dogecoin to implement Smart Contracts(through Rootstock)? If so is there any plans for adding smart contracts to the dogecoin protocol? Is it possible to do this without/with Segwit?
http://www.rsk.co/

**Comment by buddilla** [comment]
I really don't think the devs are interested in bringing in new features even ones that would help future proof doge. It's sad really. Maybe it's time to hard fork doge?

**Comment by langerhans** [comment]
>help future proof doge
If you can undoublty explain to me how adding Rootstock would make Dogecoin future proof I'll implement it right away ;) Spoiler: You can't. Since you seem to have the knowledge to implement it though, feel free to do so.

On topic tho: No immediate plans for this. Given the small amount of tiume the devs left have it's far from a priority.
