### ISSUE TITLE
Beginner questions

### ISSUE THREAD

**Issue by recoilme** [dogecoin/dogecoin#1539]
Hello, I want to integrate dogecoin as payment in my project - https://github.com/recoilme/tgram/issues/109

I want to create the wallet for all users and add a tip feature.

Am i right what no free json api for dogecoin now? only with limits on 100 wallets?
Must i install binary release and start work with server via bitcoin json-rpc?

Give me, please direction on how to start. Thank you

**Comment by rnicoll** [comment]
That's basically correct, you'd want to self-host the `dogecoind` daemon on a server somewhere (I use https://www.ramnode.com/ myself and it works fine), and use its JSON-RPC interface.

Keep in mind we're not an organisation; the individual open source contributors run some limited infrastructure, but we aren't funded at a level that would let us run services for heavy usage. Also being decentralised this way is one of the core tenets of cryptocurrency (or, this is by design rather than accident).
