### ISSUE TITLE
settxfee no longer working?

### ISSUE THREAD

**Issue by Joter271** [dogecoin/dogecoin#1604]
Dogecoin Core v1.14.0

Settxfee RPC call doesn't set fee. There is no error returned by RPC call, but it doesn't change transaction fee. Same RPC call works fine with  Dogecoin Core v1.11.

EDIT:
After some more digging I have found that paytxfee is actually set correctly, but transaction is always sent with fee 1 DOGE, no matter the fee size we set. We use sendtoaddress RPC call.

Here is  getinfo output:￼
getinfo￼
{
  "version": 1140000,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance":  xxxxxx,
  "blocks": 2838653,
  "timeoffset": -1,
  "connections": 8,
  "proxy": "",
  "difficulty": 6321115.617799241,
  "testnet": false,
  "keypoololdest": 1564688963,
  "keypoolsize": 100,
  "paytxfee": 5.40000000,
  "relayfee": 1.00000000,
  "errors": ""
}

EDIT2:
Temporal solution was setting mintxfee paramater in config. This is only way of increasing sendtoaddress transaction fee...

**Comment by Joter271** [comment]
So, any update on this?

**Comment by ReverseControl** [comment]
@Joter271 This issue might be fixed in 1.14.4. Could you please test it and post the update.

**Comment by ReverseControl** [comment]
@Joter271 this issue was addressed in 1.14.4. Transaction relay fee along with several other values were fixed to 1 DOGE / Kb, where transaction size was rounded up. All one-to-one transactions take less than 1KB, so previously they all got rounded up to 1KB, so their cost became 1 DOGE. And because of this, and some technical issues (bugs) which we have now resolved (See https://github.com/dogecoin/dogecoin/pull/2446), the system actually counts the number of bytes per transaction without rounding (See https://github.com/dogecoin/dogecoin/pull/2485/),  and applies the fees that you set correctly. The next release will decrease the default fee values (See https://github.com/dogecoin/dogecoin/discussions/2347).

For reference:

Dogecoin Core 1.14.5 Default Fees


Parameter | Current value | Proposed value
|-- |--|--|
|MIN_RELAY_FEE | 100,000,000 | 100,000
|DEFAULT_FALLBACK_FEE | 100,000,000 | 1,000,000
|DEFAULT_TRANSACTION_FEE | 0 | 1,000,000
|DUST_RELAY_TX_FEE | 100,000,000 | 100,000
|DEFAULT_BLOCK_MIN_TX_FEE | 1,000 | 1,000,000
|DEFAULT_DUST_LIMIT | (100,000,000) | 1,000,000
