### ISSUE TITLE
[Regtest] unconstantly receiving inv message

### ISSUE THREAD

**Issue by rllola** [dogecoin/dogecoin#1606]
### Describe the issue

Not receiving and `inv` message for each new block generated on regtest. The number of message is inconsistent and I am missing on new block.

#### If so, please list the steps to reproduce below:
1. Start a node in regtest
2. Connect to a the regtest node (using a spv node or another program)
3. Generate block using `generate` method

### Expected behaviour

We expect to see as many unsolicited `inv` message than newly block generated.

### Actual behaviour

Most of the time only one message is sent.

I am using the dogecore version 1.14

**Comment by patricklodder** [comment]
Tried reproducing this with my mainnet 1.14.2 node and hacked mainnet bitcore-p2p node, but I do get all the block invs there.

I'll see if there's some existing test for this that we can extend, to make sure all new blocks get propagated.

**Comment by rllola** [comment]
Hey,

I don't have this problem on mainnet or testnet. It was only happening on regtest (which I used for convenience when developing). I am not sure I tested it with 1.14.2 

I will create a minimal project to try reproduce the issue.

**Comment by rllola** [comment]
Here the example with the instructions : https://github.com/rllola/dogecoin-regtest-issue

The interesting part actually happened in peer.js file (https://github.com/rllola/dogecoin-regtest-issue/blob/master/src/peer.js)
This is the same code that used for my spv node... so another possibility is that my code to handle the data is not good... Might be worth to check with Wireshark too.

**Comment by patricklodder** [comment]
So the phenomenon that you're seeing is [this optimization in SendMessages](https://github.com/dogecoin/dogecoin/blob/master/src/net_processing.cpp#L3039-L3046)

If we have, between the `inv`s we sent to your node, accumulated more than one block to send in the `inv`, we'll only send you the hash of the block on our tip, not everything. This is because you shouldn't fully depend on the `inv` messages to discover all the blocks you need to get, but instead should check your local best chain's tip, and connect the block to there (or somewhere in the middle because this was a fork.) If you're missing blocks in the middle (detectable because the header's `prev_block` does not match anything you know), then use the forward-synching `getblocks` (or preferably: `getheaders`!) from your last known block, to build your chain up to the point where you can connect the block from the `inv` you received.

Although you won't see this happening on mainnet and testnet often, it can happen there too. By doing `generate 5` on regtest you're basically forcing the unhappy scenario where the above code gets triggered, which is a good thing because this forces you to always build your locally validated chain, and not trust that whatever peers give you is good enough :-)

Hope it helps!

**Comment by rllola** [comment]
It does help me a lot. I was unaware of this.

To keep up with the new blocks I was going to rely on `inv` message but I realize now this is a bad strategy. I was hesitating with keeping up with the `getheaders` strategy but thought it would be more calls.

Also I had this happening in Testnet using phone data. The idea of doing this spvnode is for low bandwith use so I should expect it to happen.

Closing this.

**Comment by rllola** [comment]
Hi @patricklodder 
I have follow the strategy you mentioned and I have it mostly working. One last thing is when I am synchronized and I try to keep up with the lastest block, I do a `getheaders` (update my headers), then do `getblocks` (get the inv message) and send a `getdata` with the inv message I have recieved.

However my issue is that most of the time `getblocks` never send me anything. Is there also an optimization in this part that would avoid repeating messages ?

**Comment by patricklodder** [comment]
Hi!

Yes. 1.14 nodes support [BIP-152](https://github.com/bitcoin/bips/blob/master/bip-0152.mediawiki).

There's a good illustration for "low bandwidth nodes" that allow you to not have to fetch full blocks on SPV, but just get the [compact block](https://en.bitcoin.it/wiki/Protocol_documentation#sendcmpct) and specific txn from that block.

**Comment by rllola** [comment]
Hi!
Thanks for the fast answer!

I am not trying to get the full block because I am using bloom filters. I am sending `getblocks` (https://developer.bitcoin.org/reference/p2p_networking.html#getblocks) just to get the inventory so I can form my inv message using `MSG_FILTERED_BLOCK`.

I have it running with one peer now and no problem but from time to time some peers won't send me an answer to me `getblocks` request. (In regtest, I have no problem neither by the way).
So might be that the peer have seen it sent this to me in the past and won't repeat the message (but I doubt that).
Or I have two option : 
* Set a timeout and resend a message (<-- easy)
* save that `inv` message I received for which I didn't have the header and once I have the header updated using this in my `getdata` (<-- meh quite complicated)

Or maybe I misunderstood something on BIP-152 ?

**Comment by rllola** [comment]
I have done more digging and might be that the faulty node not a answering is a `/Shibetoshi:1.10.0/`.

I am now connected to 2 `/Shibetoshi:1.14.0/` and it is running smoothly.

I will for now reject node lower than 1.14 and see if I have encounter the same issue.

**Comment by patricklodder** [comment]
In general it's better to reject `version < 70015`, than filter `subversion`. Also if someone fakes `70015` (eg no reply to `cmpct` commands, just banlist those nodes.)
