### ISSUE TITLE
Invalid txfee?

### ISSUE THREAD

**Issue by tianpu** [dogecoin/dogecoin#1607]
Block 1023973, https://blockchair.com/dogecoin/block/1072a9984abffeea9b633aa732bc872af02729b47ddeeaed99323b67a6982bdb

Input: 66331708.03224165
Output: 66331668.03224165
Txfee: -40?

**Comment by rnicoll** [comment]
That's not what that field is labelled and the difference between "TX fee" and "generation" is important; one is on a single transaction and the latter is the balance change due to the block. It looks like the block miner didn't claim the fees from the transactions, so rather than creating coins they've basically destroyed the TX fees from all the transactions in the block.
