### ISSUE TITLE
Not Get non-wallet Transaction details via api (nodejs)??

### ISSUE THREAD

**Issue by rajajwaliya** [dogecoin/dogecoin#1608]
hello i m using doge wallet. i m using <a href="https://www.npmjs.com/package/node-dogecoin">node-dogecoin</a> to get the transaction details i got my wallet transaction with out from address. but when i shaw the other api <a href="https://chain.so/api/v2/get_tx/DOGETEST/5ee72f3e9ae8f7c92c1dbb3b21e5a6e3188199850632c5e294d13c13c8c82f64">chain.so</a> then get the full details of transaction (non-wallet or wallet) with from address.  how could i got transaction details of all txids.

**Comment by rnicoll** [comment]
This isn't something the default `bitcoind` (and therefore `dogecoind`) supports, because the indexes are huge. There are patches to add an `--addrindex` option, which could potentially be adapted, but it's not an option we have in any recent release.

Generally it's a lot more efficient to use a service such as chain.so to do this, or alternatively you can fetch each block in turn via RPC and scan the transactions inside it for any matching the relevant address(es).

**Comment by patricklodder** [comment]
To answer the last part of your question:

> how could i got transaction details of all txids.

add a `txindex=1` to your dogecoin.conf. This explodes your data directory, so make sure you have plenty of disk space.

It will not sort by address still, but it will allow you to fetch any transaction by hash.

```
    -txindex
       Maintain a full transaction index, used by the getrawtransaction rpc
       call (default: 0)
```
