### ISSUE TITLE
RPC verbosity

### ISSUE THREAD

**Issue by atcueme** [dogecoin/dogecoin#1625]
Good day everyone, I have a problem with the rpc method in dogecoind

I just executed this command to get the details of this hash setting the verbose to 2 so that i could see also transaction details
```
curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getblock","params":["044cd3f3827293e6ab2ae52801f61adb2d26d0ad967d132f48df93a00337198f", 2]}' -H 'content-type:text/plain;' http://username:password@127.0.0.1:22555
```
and then error appears
```
{"result":null,"error":{"code":-1,"message":"JSON value is not a boolean as expected"},"id":"curltext"}
```

Is the verbosity different from litecoind and bitcoind?

**Comment by langerhans** [comment]
The upstream commit that introduced this is not present in 0.14: https://github.com/bitcoin/bitcoin/commit/96c850c20913b191cff9f66fedbb68812b1a41ea
That's why you won't find it in our current release. This would be in 1.17 which depends on 1.14 adoption on the miner side. Closing here as this will get implicitly fixed then.
