### ISSUE TITLE
dogecoin CPFP support

### ISSUE THREAD

**Issue by uranik777** [dogecoin/dogecoin#1658]
Why CPFP not working for dogecoin: parent tx https://blockchair.com/dogecoin/transaction/6ff5832553489b4b01693e04988b3aeea65247c47f0234c79cdf88763fe6a001 (fee 1DOGE) and chield tx https://blockchair.com/dogecoin/transaction/a567f424a8c597765c3376c630675565988c2f344fd123de715189806814bf18 (fee 32 DOGE) stuck in mempool for a long time

**Comment by uranik777** [comment]
Why CPFP not working for dogecoin: parent tx https://blockchair.com/dogecoin/transaction/6ff5832553489b4b01693e04988b3aeea65247c47f0234c79cdf88763fe6a001 (fee 1DOGE) and chield tx https://blockchair.com/dogecoin/transaction/a567f424a8c597765c3376c630675565988c2f344fd123de715189806814bf18 (fee 32 DOGE) stuck in mempool for a long time

**Comment by patricklodder** [comment]
CPFP does not work if the node that evaluates `child` does not have `parent`, it only works if the node has both txs. Because the 1.14.2 relay logic will not relay `parent`, `child` is seen as spending a non-existing utxo.

The best way to make this go through is to respend the `parent` tx original inputs in a new tx with sufficient fee and broadcast that to a (set of) nodes with either a very short mempool expiry time or nodes that have not yet received the stuck parent at all.

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin We can close this one.
