### ISSUE TITLE
Reintroduce the cap

### ISSUE THREAD

**Issue by j4hangir** [dogecoin/dogecoin#1674]
In light of recent events, this is a feature request on behalf of many people around the community.

As things stand, the only thing that is keeping dogecoin from reaching extraordinary heights is the lack, or rather, deactivation of the cap that was originally imposed on the network.

Dollar as a modern **fiat** currency, although similarly uncapped, is nonetheless periodically regulated and hence doesn't suffer the same consequences. Dogecoin on the other hand, is network-regulated and unfortunately its growth is way beyond its legitimate use-cases, and no I kid you not, dogecoin over the years has established many legitimate use-cases, thus, with all that taken into account, everyone might agree a new consensus should be in order. 
Let's simply reintroduce the cap and let dogecoin gain the glory that it deserves.

**Comment by patricklodder** [comment]
How would you keep the network secure if there is no subsidy?

**Comment by DemonRx** [comment]
What about a coin burn and lower the cap instead. Just my two-cents.

**Comment by langerhans** [comment]
> What about a coin burn and lower the cap instead. Just my two-cents.

Feel free to send all your coins to DDogepartyxxxxxxxxxxxxxxxxxxw1dfzr

**Comment by DemonRx** [comment]
@j4hangir speaking of use cases, dogecoin has gained ground with https://doge.opendao.io/ 

> Dogecoin (DOGE) will soon be available for use as collateral in minting the dollar-pegged $DOGEO stable coin at OpenDAO! This is all made possible thanks to our ongoing collaboration with Ren. Learn how this affects you and more below!

https://medium.com/opendao/dogecoin-ren-opendao-dogeo-stablecoin-40c5c65135d2

**Comment by zdwade89** [comment]
https://www.change.org/p/doge-2-the-mars?recruiter=false&utm_source=share_petition&utm_campaign=psf_combo_share_initial&utm_medium=whatsapp&recruited_by_id=3262d810-630f-11eb-a1d6-0f378de214f0&share_bandit_exp=skip-27097401-es-ES

just a heads up its a little more than us 3 with interest in this alot are really trying to make this fly

**Comment by patricklodder** [comment]
> just a heads up its a little more than us 3 with interest in this alot are really trying to make this fly

Please do not post/link your brigades here, or I will be forced to close this topic. 

Instead, please do a real proposal. Weigh the pros and cons, come up with solutions. We're not interested in how many people you can trick into signing something.

**Comment by venraij** [comment]
It would be good for all of those that got caught massively in the dogecoin hyptrain organized by the ones doing a pump and dump. I understand dogecoin wasn't meant to be taking serious. But at this point millions of people are actually taking it serious. Setting a cap on dogecoin would mean that over the longterm the new doge holders will lose less. I would not need to be a hard cap. A soft cap would do. It would provide millions of doge investors an oppurtunity they would not otherwise get. 

This is just my opinion, i don't very specific details about the pro's and con's. But i'm sure someone here will.

**Comment by zdwade89** [comment]
> > just a heads up its a little more than us 3 with interest in this alot are really trying to make this fly
> 
> Please do not post/link your brigades here, or I will be forced to close this topic.
> 
> Instead, please do a real proposal. Weigh the pros and cons, come up with solutions. We're not interested in how many people you can trick into signing something.

Excuse me, I was pointing out we're actually working on building interest in the project to turn it into something more more foundational and not simply asking for the fun of it we're literally looking through the 500 thousand members for those with the experience to provide options and opinions. It is not a "brigade" or people tricked into signing a petition its actually a movement that this project could be foundational to...

**Comment by shibe2** [comment]
@venraij What are "soft cap" and "hard cap"?

**Comment by langerhans** [comment]
Re-iterating what Patrick just said: Please come up with an actual proposal.  Until then I will close this issue as this is not the right place for opinion pieces.  
We have had lots of people tell us to add a cap "to make the price go to the moon". I'm sick of this. This isn't going to happen. At least not this way.

**Comment by patricklodder** [comment]
The interest was already built by people trying to trick others in buying an asset they themselves do not understand and your link is to a petition that tricks people into asserting social pressure towards changing the core parameters of an asset that have been there since its launch.

We believe that what you're really doing is trying to get rich at the cost of others and when that failed because you ran out of victims and money, you come here asking us to bail you out. However, we will not bail you out, as with great freedom comes great responsibility. We take ours seriously and we hope that you will too in the future.

We have now closed this topic. Request denied.

**Comment by venraij** [comment]
Wouldn't it mean that without a cap the coin is largely rendered useless for holding over a long period of time because the inflation being caused by the creation of new coins?

**Comment by Frosty-J** [comment]
Currencies are for spending, not for hoarding. Adding new coins combats inflation as opposed to contributing to it.

**Comment by dr-bonez** [comment]
DOGE inflation is linear and therefore the monetary supply debasement decreases over time. This is a good thing.

**Comment by shibe2** [comment]
This is already closed, but I'll add my opinion anyway.

First of all, block reward is needed to secure Dogecoin network in a decentralized manner. Dogecoin is merge-mined with Litecoin, and that makes it somewhat secure against PoW attacks. But if Dogecoin reward will be too low, some Litecoin miners may drop Dogecoin, and our security will suffer. From this point of view, bigger reward is better. If you propose reducing the reward over time, you must also propose a solid way to keep Dogecoin secure.

Now about the economic aspect. Current Dogecoin issue rate, taken relative to current total amount, is low, it's almost nothing compared to all the other factors that affect Dogecoin value. If you look at Dogecoin price chart since the introduction of current issue schedule, you will not see effects of "inflation" for all the wild price changes caused by other factors. And this already low issue rate gets even smaller over time, compared to total amount of dogecoins.

The only real reason for these "cap" proposals is trying to "sell" Dogecoin to investors under the premise of possibly increased scarcity in the future. In my opinion, we don't need to try to appeal to investors. Dogecoin value will be increasing because of strong community and increased usage. And the fact that Dogecoin value increases is already enough for investors to jump in and increase it even more.

**Comment by j4hangir** [comment]
> Re-iterating what Patrick just said: Please come up with an actual proposal. Until then I will close this issue as this is not the right place for opinion pieces.
> We have had lots of people tell us to add a cap "to make the price go to the moon". I'm sick of this. This isn't going to happen. At least not this way.

The description of the dogecoin on GitHub reads as **The Moon**, therefore nothing wrong with keeping that mentality, _nevertheless_, the actual proposal on this issue - which was unjustly closed - including the cons and pros, is as follows:

Every currency serves a cause, and addresses a problem. The cause for dogecoin had been a joke, but overtime it has gained more than enough popularity and legitimate use-cases that it shouldn't be just taken as a joke anymore.

On the other hand, the logic behind capping is that all currencies one way or another, need to be regulated. In case of cryptocurrencies, _self-regulated_ or rather `network-regulated`.

Dollar as a common currency used to be pegged to physical assets, i.e. gold, yet after its conversion into a `fiat currency` in 1971, its cap was theoretically lifted, but **_not_** removed.  At the moment only a handful of authorities can issue dollars, and theoretically they can issue infinite dollars, but given that they're also regulated in a bigger system of government, i.e. the higher authority, that's most likely not going to happen. In case of dogecoin however, there is no higher authority, the network *is* the authority, and it's not properly regulated, or at least _perceived_ to be properly regulated.
 
We can see that the perceived and assigned value to a currency **needs** some sort of guarantee that it will not be easily __diluted__, and the **current problem with dogecoin** is that its value is perceived as highly _dilutable_. It might've not been a problem if there weren't so many dogecoins in circulation, or if the _network difficulty_ was much higher, or simply just weren't SO MANY dogecoins in existence, but altogether given how the network is as of right now, it is rightfully _perceived_ to be too thin, and not of much value.


`Cons & Pros`

**Cons**
* Changing the *implicit contract* amongst the network users is highly ever a good idea, in this case, can be considered a drastic change.
* Many miners would perceive - arguably wrongfully - a capped dogecoin not as profitable and switch elsewhere, reducing the strength of dogecoin.
* Many people in the community might take the change as a shift from currency into asset.


**Pros**
* This is in essence bringing dogecoin to what it has been already, not as drastic a change, but more of a correction.
* A capped dogecoin appeals no longer only to the spenders, but as well to the __investors__.
* The mining might in all likelihood become more appealing or remain more-or-less the same, as each block becomes more precious.
* It will increase the trust in this currency, as many people _perceive_ it as too wild and unregulated.



**Proposal**

To satisfy all parties, i.e. spenders, miners, developers and the investors, a large-cap be re-introduced into the network. 

The cap used to be originally _100 billion dogecoins_, and at the moment there are ≈130 billion dogecoins in circulation. In order to make the transition as pain-free as possible, a large-cap in the range of 500-1000 billion could be introduced, in effect not changing much of the current status quo, but in practice lead to a higher perceived value, and an increase in trust in the currency, that a cap does exist and that the coin is not going to be infinite.

**Comment by j4hangir** [comment]
> @venraij What are "soft cap" and "hard cap"?

`Soft-cap` can be taken as what the US government does with dollar, the currency is theoretically uncapped, you can print as much as you want, but __in practice_ it is regulated and and printed only periodically.

`Hard-cap` would be simply a final contract that this exact amount of coins will be produced and never ever go against it, that is the route that Bitcoin has taken.

The only thing one needs to pay close attention to is that **no real hard-cap** exists in the crypto sphere. Even bitcoin's contract has left backdoor for bypassing the limit, as theoretically when all the coins are mined, people can extend the support for decimal fractions and come up with something smaller than *satoshis*, say _satoshiettes_, in effect bypassing the cap, resulting in more coins in circulation than before. Granted there'll be no more bitcoins in circulation, but there'll more of bitcoin circulating.

I've emphasized the word `perception` many times in the proposal above, as in some aspects what matters is not the theoretical possibilities, but the perception that surrounds it. 




P.s.
In theory, people can fork bitcoin to to end and be successful in migration, or in theory, the bitcoin community can change its mind and modify the contract (= code) tomorrow.  People don't lose sleep over this as much as before, because the momentum, the community and their beliefs - is not as easily movable (what itself was perceived in the recent decades)

**Comment by DemonRx** [comment]
I'd like to add a point to this, something I've mentioned in passing many times over the years with crypto in general. Think in terms of the bigger picture. Firstly, understand cryptocurrency is still in its infancy. In Doge's case, literally less than 10 years.  

Now think about this. using a nice round number of about 100 billion Doges in circulation. Let's say the the coin takes off (think not in terms of just thousands of users, but potentially BILLIONS).  Now say a few billion people each want their bag of Doge. Is 100 Billion Dogecoins gonna be enough to supply that kind of demand ? Well... Of course not. So through the natural course of time and demand, its worth and use will increase exponentially :)

On that note messing with the cap has no significance to the functionality of the coin nor a negative impact on the potential economic/financial effect thereof IMHO. The number of coins don't affect block size like number of transactions do.

Not just that, regarding supply, you have to consider another factor here, like what's happened with Bitcoin. Since this is blockchain technology. There will be coins that end up locked up forever, be it the user dies, forgets their password, access or otherwise, which then equates to there being less supply available on exchangers, and so forth. Hope the point is made clear. Thanks for hearing me out.

- Much Doge Much Love

**Comment by shibe2** [comment]
> Dollar as a common currency used to be pegged to physical assets, i.e. gold, yet after its conversion into a `fiat currency` in 1971, its cap was theoretically lifted, but **_not_** removed. At the moment only a handful of authorities can issue dollars, and theoretically they can issue infinite dollars, but given that they're also regulated in a bigger system of government, i.e. the higher authority, that's most likely not going to happen. In case of dogecoin however, there is no higher authority, the network _is_ the authority, and it's not properly regulated, or at least _perceived_ to be properly regulated.

LOL, you got it backwards! They can issue new dollars basically as much as they want. Look at the dollar supply increase:

![United States Money Supply M0](https://user-images.githubusercontent.com/25643785/106368241-a10ea080-6361-11eb-9dc0-c9dd08dd873b.png)

And that's just M0. If you look at M1, it's worse:

![United States Money Supply M1](https://user-images.githubusercontent.com/25643785/106368302-082c5500-6362-11eb-8554-54a4218e6a55.png)

On the other hand, Dogecoin issue is done strictly by schedule which was set beforehand. It's unaffected by current desires of developers or miners.

> We can see that the perceived and assigned value to a currency **needs** some sort of guarantee that it will not be easily **diluted**, and the **current problem with dogecoin** is that its value is perceived as highly _dilutable_. It might've not been a problem if there weren't so many dogecoins in circulation, or if the _network difficulty_ was much higher, or simply just weren't SO MANY dogecoins in existence, but altogether given how the network is as of right now, it is rightfully _perceived_ to be too thin, and not of much value.

Perception is by definition subjective, so I will not argue about that. But in fact, Dogecoin value cannot be diluted by issuing new dogecoins. With current schedule, it will take more than 24 years to double the amount of dogecoins in circulation. By that time, other factors can easily change Dogecoin value like 1000x either way. Then who will care about 2x change in supply? I agree that perception may matter more than facts, but I actually like the fun/easy/light perception of Dogecoin more than "serious" perception. It's Dogecoin's strength, it's what differentiates it from many other ctyptocurrencies. Again, this all is subjective.

>     * A capped dogecoin appeals no longer only to the spenders, but as well to the **investors**.

As I said in my earlier comment, I don't think that we need to specifically appeal to investors. By now, Dogecoin is already well-known enough that "investors" come by themselves. If you want to "invest" in cryptocurrency and look at Dogecoin price chart, you will not need further appeals.

> The cap used to be originally _100 billion dogecoins_, and at the moment there are ≈130 billion dogecoins in circulation. In order to make the transition as pain-free as possible, a large-cap in the range of 500-1000 billion could be introduced, in effect not changing much of the current status quo, but in practice lead to a higher perceived value, and an increase in trust in the currency, that a cap does exist and that the coin is not going to be infinite.

So as with current issue schedule, total amount of dogecoins will never be infinite.

**Comment by patricklodder** [comment]
> We can see that the perceived and assigned value to a currency needs some sort of guarantee that it will not be easily diluted, and the current problem with dogecoin is that its value is perceived as highly dilutable. It might've not been a problem if there weren't so many dogecoins in circulation, or if the network difficulty was much higher, or simply just weren't SO MANY dogecoins in existence, but altogether given how the network is as of right now, it is rightfully perceived to be too thin, and not of much value.

As much as a currency, or any contract, needs some sort of guarantee that it will not be easily diluted, it also needs some sort of guarantee that its principles will not be easily broken. In fact, our development team's stance on this has been pretty predictable, as we have never changed the economic parameters. We value reliability and long-term sustainability over short term gains, especially if they only benefit one segment of bag holders. So in fact you can say that there is an implicit guarantee for both no easy dilution and no breaking of promises, as that's exactly what we've been doing and what we plan to continue to do. And we do that by declining your request.

For us, if the consequence of the contract is that it will not have much value, then that's the consequence and we will live by it. There are no other governing procedures than miner majority for this coin, but if you really need to make your point so badly that you need to cause a hardfork, then just go do it? I will personally not do it, for free or otherwise. Instead, I will personally maintain these parameters or none, because that is what I signed up for. 

We, the developers, are not the Fed, we are not the ECB; we do not meddle with any issuance. We are apolitical and we maintain an asset that has clearly advertised properties. One of those is a block subsidy of 10,000 DOGE per block. It is there because we, and those before us, believe that this is necessary for the security of the coin. If anyone promoted something different than what the coin actually does, or has been promising certain price points based on flawed mathematics, then these people should in my opinion be prosecuted where possible, and definitely not be granted a way out by our meddling with issuance.

**Comment by Achristine-me** [comment]
I'm just a person who bought Dogecoin, probably got sucked in with the hubris and joy in the community. I didn't invest enough to hurt myself, but after reading this thread I am now very worried about those that did invest too much. 

(I found a link to this thread on a twitter feed so I hope I am not intruding by commenting here, as this not my intention.) 

I just want to give my point of view as a normal person who bought into, after reading this thread, what appears to be madness.. I feel gullible that my newness to crypto currency and the excitement I gathered from the community swept me along for the ride too. 

I do love the idea of this coin and that the premise is to bring happiness and joy to people.  I wanted to support that type of currency. I felt like good people should have their own brand of currency, and it made sense to me at the time. I never encouraged anyone else to buy in, as this was my choice and my risk. However, sadly, it seems not everyone took a cautious approach that bought into to Dogecoin

I think I understand the desire of putting a cap on the coin, I am at a loss at what that would entail on the the technical side, perhaps this is too difficult of a task too do.  That being said, I do see that if the value of this coin is preserved with a cap it could help a lot of people. Now I personally didn't invest to the point of danger so if Doge tanks that will sting but I'll live. Of course a cap would make me happy in my own circumstance, but I will be ok if you don't too.

My worry, which drove me to create an account and comment here, is that there are probably thousands and thousands of people who got swept up in the circus and may have over extended, in which a cap could save them alot of pain. In addition, I  think even a small success with Dogecoin could propel a greater acceptance in the mainstream of crypto currency in general, especially if people don't lose their shirts the first time they get involved with crypto.  Many who invested, like myself, are newish or brand new to the crypto market. If all these first time buyers lose too much they will probably never trust any crypto currency again. 

I realize you have made a decision on the cap, and I am sure the decisions you make are best,

From my layperson perspective I hope you do find a way to cap the coin or find another solution, so that people don't lose too much overall.  It would probably make the world a better place if Dogecoin was successful, Even though there were some with bad or greedy intentions, I believe the influx of newcomers to cryptocurrency are probably good people. I do believe most are probably dreamers and good natured at their core and really do love Dogecoin and want to see it succeed.   

Anyway, if you got this far,  Thank you for reading.  Also I again apologize if I shouldn't be posting here, but I felt compelled to share my experience and thoughts as a person who bought Doge 

Take care and be well

**Comment by patricklodder** [comment]
> My worry, which drove me to create an account and comment here, is that there are probably thousands and thousands of people who got swept up in the circus and may have over extended, in which a cap could save them alot of pain.

The issuance has been fixed to a schedule, which you can read about in the README. 

- There is a constraint imposed on every miner to get a maximum subsidy of 10,000 DOGE per block. A miner cannot claim more than that.
- The number of blocks per day is roughly 1440 (it's not exact because it depends on random number generation), so that means that 14,400,000 DOGE is generated per day.
- In total there are a little over 128B DOGE in circulation
- The past 24h, according to CMC, $6,303,398,845 worth of Dogecoin exchanged hands on the crypto exchanges. That's 223B DOGE at current exchange rates
- The subsidy earned by miners today is:
  - 14.4 / 128,000 = 0.01125% of total supply
  - 14.4 / 223,000  = 0.0064% of total trades

Don't you think that it is far more likely that the other 99.9936% of the trade volume is responsible for people losing money?

**Comment by shibe2** [comment]
> From my layperson perspective I hope you do find a way to cap the coin or find another solution, so that people don't lose too much overall.

Thanks for sharing your layperson's point of view, but in this case it's not a useful input. It seems that most people who are in favor of "cap" don't understand what it really is and what effects it may have on a particular cryptocurrency. It's not some magic thing that will make the price go up permanently nor will it help price stay at some level. Learn more about cryptocurrency, including particular its original purpose, history and how PoW works. Also, experience it. And by that I mean not just sitting on your stash waiting for the price to go up. See what you can do with it, other than trading and "investing". The more you will learn, the more your views will be changing.

> Even though there were some with bad or greedy intentions, I believe the influx of newcomers to cryptocurrency are probably good people.

Now I won't be judging whether it's bad or not, but the recent influx of newcomers is driven by selfish intentions. Like 99% of people who bought in recently don't care about Dogecoin other than for one thing, to sell it higher than they bought. They only care about dollars (or whatever local currency they trade in) that they can earn from the trade. For what they care, Dogecoin can crash and burn after they sold it for profit. It's not the same kind of people as those who were supporting and improving Dogecoin through the years up to this point. We welcome new members to the community, but we don't support their greed. On the contrary, we promote generosity and fun, laid-back approach to cryptocurrency.

**Comment by Achristine-me** [comment]
I am sure you and your team know what you are doing. 

I just wanted to put my 2 doge in.  as I just don't want anyone to get hurt. 

I also don't want people to end up with a mistrust crypto as this could be the moment in time that it crosses into mainstream, and I hope a majority of new people have a positive or neutral experience buying rather than being financially hurt in the process.

I guess maybe Dogecoin is the gateway coin to crypto ...And maybe I just worry too much. :)

As I said I before,  am new to buying cryptocurrency and I am really excited by what it represents, even if I take a bath this time I have learned a lot. 

I also want to say I am really surprised and happy you responded. Thank you for taking the time.  I hope you have a wonderful day/evening and good things come your way. 

Best regards

**Comment by shibe2** [comment]
> I also don't want people to end up with a mistrust of crypto as this could be the moment in time that it crosses into mainstream, and I hope a majority of new people have a positive or neutral experience buying rather than being financially hurt in the process.

When you are trading something for profit, you are betting on its price. I think, you understand that when you make a bet, you can either win or lose. It's normal, it's what it is. There is never a guarantee. Some people won in the recent price movement, some people lost. It happens every time, it couldn't have been different this time. Whatever can pull off now, it cannot change the facts. Even if we somehow magically drive the price up again so that those who already bought could sell without losses, there will need to be other people who will lose.

**Comment by patricklodder** [comment]
> I also don't want people to end up with a mistrust of crypto as this could be the moment in time that it crosses into mainstream, and I hope a majority of new people have a positive or neutral experience buying rather than being financially hurt in the process.

I absolutely share that concern, but do not see removing subsidy as a solution, especially since no one that has proposed one has done the math on what would happen. I will paste a small explanation I did on reddit yesterday below, just to create awareness. I am confident that most people that take the time to come to the github really do not want people to get hurt but I think that no matter what happens now, people will get hurt. If the price goes further down, people that bought at the peak will get hurt more, and if it goes up again, the people that are sold to will get hurt once that peak is reached. I really believe we're past the point where no one gets hurt and this is a very sad reality.

I can only hope that a lot of people are now learning - be it the hard way - that whenever someone gives you an advice to buy something, you're very likely already too late, and you should never trust these people. To me, and many others here, the moment someone starts hyping something our reaction is to do the exact opposite and stay far away from whatever is being hyped. Because it always ends bad. We've seen this many times over the years. Instead, I'm spending the past 72 hours with too little sleep, helping to keep the network functioning because there is a lot of stress on it, and now, helping people cope with their losses.

----

### What happens if we remove subsidy:

1. If there is no subsidy, then only transaction fees will pay miners. The average transaction fee per is around 60 DOGE.
2. The security of the network is measured in cost-to-attack vs total market capitalization. Current cost-to-attack sits between $900M and $1B, so security vs cap right now is about 1:4 or 25% (which is not optimal, but still better than most, and this is a sign that DOGE is overvalued rather than undervalued.)
3. Currently there is 10,000 DOGE subsidy. To have a cap that has to be 0. So that means that at current tx volume, mining profitability will fall 1-(60/10060) = 99.4%
4. That would mean that mining hashrate will have to drop by 99.4% too, because otherwise mining is not profitable, at which point the cost to attack becomes $5.25M. But that is so low that you can just go to nicehash and rent an hour of hash power to successfully attack the coin. This means the cost would be around $602 per hour.
5. Once the coin is no longer secure, you or your bank/app/broker cannot securely transfer Dogecoin anymore, so how will you buy or sell it? You cannot.
6. As there is then no ability to buy or sell, because there is no ability to transact, your coin will now be worth absolutely nothing. As in $0.000000000.

**Comment by shibe2** [comment]
> What happens if we remove subsidy:

I think, immediate removal of subsidy is not proposed here. What is proposed is theoretical cap on the total supply that could be reached in some distant future. Then the situation will be quite different for sure, and projecting current situation does not provide good insight. We can only speculate.

> That would mean that mining hashrate will have to drop by 99.4% too

You don't take merged mining into account, but it's is quite important here.

**Comment by Achristine-me** [comment]
You all seem like well intentioned people and I really do appreciate the thoughtful and informative responses. I know you don't have to do that, so thank you for taking the time and sharing your knowledge and insight. 

I will say I have learned a lot recently, and I will continue to learn about crypto currency. I didn't invest more than I can afford and I am honestly ok with whatever happens because I do like this coin a lot,  even more so now after this conversation. Good people are at the foundation and that is important to me. So I'm a Dogecoin fan for life!

Anyway, I don't think I can offer much useful input at this point, but I will say thank you for being level heads and caring. I hope you are able to rest and I thank you a lot.

**Comment by j4hangir** [comment]
> > Dollar as a common currency used to be pegged to physical assets, i.e. gold, yet after its conversion into a `fiat currency` in 1971, its cap was theoretically lifted, but **_not_** removed. At the moment only a handful of authorities can issue dollars, and theoretically they can issue infinite dollars, but given that they're also regulated in a bigger system of government, i.e. the higher authority, that's most likely not going to happen. In case of dogecoin however, there is no higher authority, the network _is_ the authority, and it's not properly regulated, or at least _perceived_ to be properly regulated.
> 
> LOL, you got it backwards! They can issue new dollars basically as much as they want. Look at the dollar supply increase:
> 
> ![United States Money Supply M0](https://user-images.githubusercontent.com/25643785/106368241-a10ea080-6361-11eb-9dc0-c9dd08dd873b.png)
> 
> And that's just M0. If you look at M1, it's worse:
> 
> ![United States Money Supply M1](https://user-images.githubusercontent.com/25643785/106368302-082c5500-6362-11eb-8554-54a4218e6a55.png)

I do understand that the US government can issue as much as they want - hence the cap being lifted - yet in practice the system is governed by multiple authorities to exactly prevent that, each of which also governed by other entities and so on (also pretty sure there's an exploit somewhere or it's being exploited already and we don't know about it, but also not of that magnitude).



> On the other hand, Dogecoin issue is done strictly by schedule which was set beforehand. It's unaffected by current desires of developers or miners.
> 

☝🏻  This aspect of dogecoin I would say requires a lot more publicity. Even if the consensus weren't to reintroduce the cap, at least a good publicity / emphasis on the `issuing schedules` is desired, to convey that the coin is not lawless, and that good - in this case automated - regulations are in place.

**Comment by j4hangir** [comment]
> > What happens if we remove subsidy:
> 
> I think, immediate removal of subsidy is not proposed here. What is proposed is theoretical cap on the total supply that could be reached in some distant future. Then the situation will be quite different for sure, and projecting current situation does not provide good insight. We can only speculate.
> 
> > That would mean that mining hashrate will have to drop by 99.4% too
> 
> You don't take merged mining into account, but it's is quite important here.

What I've proposed technically - a **large-cap** - doesn't change a thing _right now_, but it instills a higher perceived value to dogecoin. 

This might sound **_subjective_**, but how value is perceived and assigned has its own governing rules. We as living beings assign higher value to something that is scarce, and that might be a heuristic not completely aligned with reality, nonetheless it is a heuristic deeply ingrained with our psyche so much that we cannot simply disregard, warranting its own planning.

**Comment by hueseyinkilic** [comment]
Holding my uncapped Dogecoins. You mods are great people. This will get far either way.

**Comment by patricklodder** [comment]
> ☝🏻 This aspect of dogecoin I would say requires a lot more publicity. Even if the consensus weren't to reintroduce the cap, at least a good publicity / emphasis on the issuing schedules is desired, to convey that the coin is not lawless, and that good - in this case automated - regulations are in place.

Agreed, so let's start with that. We've been doing that since forever. I am also pretty sure that once you understand what the consequences are, you don't want to do a contentious fork as done with "Ethereum Classic" or "Bitcoin Cash".

_PS: For the record, it's not **re**introduce as there has never been a cap implemented in the code._ Please browse this repository's pull requests and issue reports from late 2013 and early 2014 to learn what actually happened?

**Comment by patricklodder** [comment]
> I think, immediate removal of subsidy is not proposed here. What is proposed is theoretical cap on the total supply that could be reached in some distant future. Then the situation will be quite different for sure, and projecting current situation does not provide good insight. We can only speculate.

It doesn't really matter. It just means we change a contract to unsolve a problem that was solved in the past (first by accident, then by consensus) because it with something that is better perceived, and that will make the price go up? If that's true (and it probably is) then it is no wonder everyone always gets manipulated and tricked into doing things that are bad for themselves. We also would set a precedent that way that it's ok to mess around with Dogecoin's parameters, and that would undo everything we've fought for all those years. So it's already been declined as a proposal to us and I don't see any argument changing that.  

On the other hand, if one does not like these parameters then why did they not just buy a deflationary coin, like Bitcoin? 

> You don't take merged mining into account, but it's is quite important here.

Because in my opinion it may make the initial reaction softer, but since with AuxPoW hash power comes in large chunks rather than gradually (because it's really binary - a pool implements it or not), the path to oblivion will be much much rockier and the moment where the coin can be attacked much less predictable than with other coins suffering 51% attacks.

**Comment by beatles1** [comment]
I think an important note for anyone reading this is: Inflation encourages spending, deflation encourages saving.

I think that goes a long way to helping the layperson understand why even if there weren't other considerations the community has always wanted inflation.

**Comment by shibe2** [comment]
Well, I don't want inflation. With current linear issuance, Dogecoin will become deflationary at some point. But even today, the rate of issue is negligible. So I don't consider Dogecoin inflationary.

**Comment by DPsystems** [comment]
Crypto currency was never designed to be an investment security.  You're using it wrong.  And you're part of the problem if you want to make it deflationary.

**Comment by rywards** [comment]
Lets not focus on price so much as utility.

**Comment by alisterdaniel** [comment]
> How would you keep the network secure if there is no subsidy?

Good day 

You can set it up to use exchange fees and transfer fees to compensate miners or staking to use wallets as Proof of Stake. I guess similar to other coins Cosmos, NEO and so on that have fix caps. 
Right now, I feel the crypto market is at a critical point in history where the masses are finally gravitating to it...... the pump is not the best way but it is giving crypto coins, in general, the marketing it desires. 
When the internet first came out; people fought it was worthless but it developed to something so huge and is still growing in what it can do..... the same applies to crypto. We, the people, may not have the knowledge but you guys do. Let's make it happen as millions of people, especially Americans join the rest of the world in this crypto arena.

**Comment by j4hangir** [comment]
> Crypto currency was never designed to be an investment security.  You're using it wrong.  And you're part of the problem if you want to make it deflationary.

That's what people said about the internet. There's no using it wrong, moreover cryptocurrency is too new to know what's right and wrong.


The public is asking for a cap, why? Because they **believe** there are too many dogecoins and there's going to be infinite dogecoins (right or wrong, aside)

The solutions go in various directions:

* disregard the public, they're the masses anyways. Let's carry on exactly as before.
* heed to the public, give them what they want.
* find out the underlying cause and work on that.
* ...


The arguments that "it's wrong" and "we want it to be against the public interest" are certainly valid, but not helpful in the long-term.


I pointed out why most people find dogecoins not as worthy, and the other mods seem to understand. Putting a cap is not necessarily the only solution, as the underlying cause is that people find dogecoins to be too many and keep becoming more, hence no feeling of scarcity, hence not much perceived value.  


On the other hand, what the word **investment** entails is not only that "Imma put my money to make profitz" BUT "I find this project interesting and like to give it my attention, resources, and hope for it to succeed".


There are people out there, and they have their own limited resources. How they allocate them is their investment. You're also already an investor with your time if you're contributing to this project.

**Comment by patricklodder** [comment]
Alright everyone. I'm going to lock the topic for comments because this is not an issue with the code (yet) and hence off-topic. Right now this is just spamming a philosophical discussion into people's mailboxes that are following code updates.

However I do not wish to censor the discussion, so I have opened a message on the reddit dogecoin-dev sub:

https://www.reddit.com/r/dogecoindev/comments/la1hk3/continuation_of_1674/
