### ISSUE TITLE
Supply bug? 8 billion increase in a few hours 

### ISSUE THREAD

**Issue by ks-coder-1** [dogecoin/dogecoin#1688]
On 1/28, near it’s high of .07 cents the supply was 120.996 billion.  The next morning on 1/29 it’s price collapsed and the total supply was 128.15 billion.

based on the algorithms  I’m seeing on supply , it seems an increase of 8 billion coins is way to high for an overnight increase.

#### If so, please list the steps to reproduce below

I have screenshots
If you don’t  have a historical supply data
![8494CEF8-3A1D-4DB9-A865-8A6B68B32E5A](https://user-images.githubusercontent.com/78357792/106459070-efea3200-6456-11eb-8bef-8f5ed768074b.png)
![210A8D21-203E-41EB-B121-0DF4CE955C26](https://user-images.githubusercontent.com/78357792/106459074-f11b5f00-6456-11eb-8cc9-96b3d13e7d78.png)
![90F16EC6-18CA-4C71-9EC0-B65C0E9B0C6A](https://user-images.githubusercontent.com/78357792/106459076-f1b3f580-6456-11eb-9ef3-597d5c0f90d3.jpeg)

**Comment by patricklodder** [comment]
Extremely unlikely that this is a bug in the software. But we should check it for sure.

I'll crawl the blocks to make an issuance log. Give me a couple of hours. Will open-source the script.

**Comment by patricklodder** [comment]
Alright so I checked all blocks since 2021-01-26 17:19:51 UTC and there has not been an issuance of 8bln. (There is a hardcoded constraint that makes sure a miner never gets paid more than 10,000 subsidy + whatever fees were mined, that's why it was so unlikely.)

I have attached the log file: [block_fees.txt](https://github.com/dogecoin/dogecoin/files/5904369/block_fees.txt)
And you can find the source script here: https://gist.github.com/patricklodder/1a505e6521d1059aad4e3fec912d6d41

Please file a report with the website that gave you this information, as there was no issuance of that amount of coins on the Dogecoin chain.
