### ISSUE TITLE
DNS Seeders unreachable when using proxy through Tor connections

### ISSUE THREAD

**Issue by DemonRx** [dogecoin/dogecoin#1693]
#### If so, please list the steps to reproduce below:
1. Enable proxy connections (either in GUI network tab) or adding `proxy=127.0.0.1:9050` in **dogecoin.conf**
2. Start dogecoin client

### Expected behaviour
Client establishes connections and acquires list of IPs from DNS seeders

### Actual behaviour
When client attempts to connect to the seeders it errors stating: `failed: host unreachable`

### Debug.log output:
```bash
2021-02-02 03:48:26 Loading addresses from DNS seeds (could take a while)
2021-02-02 03:48:26 0 addresses found from DNS seeds
2021-02-02 03:48:26 dnsseed thread exit
2021-02-02 03:48:36 ERROR: Error reading proxy response
2021-02-02 03:48:36 Socks5() connect to seed.multidoge.org:22556 failed: host unreachable
2021-02-02 03:48:57 ERROR: Error reading proxy response
2021-02-02 03:48:59 Socks5() connect to seed2.multidoge.org:22556 failed: host unreachable
2021-02-02 03:49:19 ERROR: Error reading proxy response

```

### What version of Dogecoin Core are you using?
Latest dogecoin-qt release version 1.14.2

### Machine specs:
- OS: ubuntu 18.04
- CPU: amd
- RAM: 8gb
- Disk size: 500gb
- Disk Type (HD/SDD): HD

### Addtional info:
Network connections that are established when running dogecoin client:
```bash
demon@Bionic18:~/Desktop/dogecoin-1.14.2/bin$ sudo netstat -antp|grep -E 'dog|\tor'
tcp        0      0 0.0.0.0:22555           0.0.0.0:*               LISTEN      8567/./dogecoin-qt  
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      1242/tor            
tcp        0      0 10.0.0.26:34998         178.170.42.112:9001     ESTABLISHED 1242/tor            
tcp        0      0 127.0.0.1:9050          127.0.0.1:51690         ESTABLISHED 1242/tor            
tcp        0      0 127.0.0.1:9050          127.0.0.1:51718         ESTABLISHED 1242/tor            
tcp        0      0 127.0.0.1:51718         127.0.0.1:9050          ESTABLISHED 8567/./dogecoin-qt  
tcp        0      0 127.0.0.1:51690         127.0.0.1:9050          ESTABLISHED 8567/./dogecoin-qt 
```

**Comment by Saibato** [comment]
Please note that seeding over DNS can not work work in the same manner as if in ipv5/6.
Tor is TCP only so UDP DNS query's make not much sense.
 
What happens when u bootstrap / seed over Tor is that the random Tor exit node that try's to connect in cllearnet for you the socks5 DOMAIN  request to seed.multidoge.org  translates **his** ( not urs )  DNS answer to 
seed.multidoge.org.
Since that is a seeder address, it probably answers to the Tor exit node DNS request with multiple ip's or not at all.
In the case the exit node finds ip's for the name u might get the first entry or connect or it decides to not connect at all to seed2.multidoge.org 22556. That's the error u got.

That can change and when Tor switches internal to an other exit  u might get a connect.
After that is done seeding over Tor is done like any direct connect over standard dogecoin internal ADDR messages, so no DNS involved here since that are plain TCP message exchanges,

So please note that when u seed over Tor u can not be sure that u really connect to the seeders node u specify and its not the same as DNS  seeding.
So good advice could be when u want pure Tor is to use the option -nodns and specify a known trusted Tor onion seednode or any normal nodes onion address from whom u know it is well connected and can serv ADDR messages with know nodes.
by say -seednode=theonionuknow.onion:22556.
To make sure u stay in Tor when bootstrapping.
t would be nice for privacy of the seeders, if they would publish there Tor onion addresses, 

Pls note also that Tor will change soon to v3 onion addresses and doge has no v3 ADDR support..
Sp best is just to add from day one the long v3 addr behind the -seednode= 
and just live until some magic comes then to dogecoin to live with the fact that then u can only learn ipv4/pv6 addresses and if u want to stay in Tor u have to add manually many addnode= entrys in the conf

One option is to adapt the ADDRv2 messages from bitcoin or to use a simple tunnel protocol that tunnels in 3 ADDR ipv6 message the longer v3   address so that by the end of this year Tor and doge will still work.

**Comment by DemonRx** [comment]
Right, here is the commit in bitcoin: https://github.com/bitcoin/bitcoin/pull/9726 to ignore the TOR timeouts. 

I'll start a PR on this for that.

**Comment by DemonRx** [comment]
In regards to running DNS over TOR this might be a good start: 

https://developers.cloudflare.com/1.1.1.1/fun-stuff/dns-over-tor

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin  We can close this one.
