### ISSUE TITLE
get the core to run in linux

### ISSUE THREAD

**Issue by hendriks888** [dogecoin/dogecoin#1747]
i cant find an answer anywhere, really. 

Ive got an old doge Ubuntu OS and I've been trying to upgrade to 14.2
have downloaded, but don't know what commands to run or how to get the program to open
using 14.2 [which file, which command]
really could not find a walk through or guide or anything to help anywhere.

There is info for bitcoin, but nothing for doge core anywhere.
### What version of Dogecoin Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Ubuntu 20 LTS
- CPU:i5 2500
- RAM:8gb
- Disk size:3Tb
- Disk Type (HD/SDD): HD
please help, as no one seems to have done....

**Comment by longvic0** [comment]
Just download dogecoin wallet program from : https://github.com/dogecoin/dogecoin/releases/
Then run: dogecoind to be full synchronized with the dogechain
I start to run a full node now. It will take more than 20 hours to sync.

**Comment by hendriks888** [comment]
Thank you

 

The question is, how to run dogecoind?

 
 

Sent: Friday, February 19, 2021 at 9:19 AM

**Comment by hendriks888** [comment]
i have downloaded all versions

but i dont know the command to make the file work

ubuntu Gnome

 
 

Sent: Friday, February 19, 2021 at 9:19 AM

**Comment by hendriks888** [comment]
let me put it this way. im in the directory. I can see dogecoind and 3 other files, in bin
im a newby to linux
i know sudo
and apt get
but i dont know how or what to write , in a terminal , to make dogecoind do anything
double click just give a 
"there is no application installed for shared library files" message

**Comment by longvic0** [comment]
Here is my tutorial to setup a dogecoin full node: https://nguyenkhaclong.com/385/create-a-dogecoin-node-on-your-own-vps/

Hope it help!

**Comment by MostHated** [comment]
> Just download dogecoin wallet program from : [dogecoin/dogecoin/releases](https://github.com/dogecoin/dogecoin/releases/)
> Then run: dogecoind to be full synchronized with the dogechain
> I start to run a full node now. It will take more than 20 hours to sync.

Hmm... mine has  been running for over 24 hours and I am only at 2.13% :\

![](https://i.imgur.com/VMar43t.png)

**Comment by longvic0** [comment]
![dogecoin-bootstrap-wallet](https://user-images.githubusercontent.com/48219858/108952347-e2157e80-769b-11eb-9d91-708e81f8711d.jpg)
1. First , you must run ./dogecoind . wait for few seconds to generate .dogecoin folder. then stop that process.
2. Copy two folder in the bootstrap torrent file to .dogecoin folder
3. start the wallet process again: ./dogecoind
4. If it works, send me some tips
5. My $doge wallet address : **DJZC6CUKPvUWWRN4bv5XpeD1Z79XwYLX8n**

**Comment by hendriks888** [comment]
Hi, thanks

notcompletely sure what and why the node daemon, but its done

doge is downloaded

waiting on bootstrap to complete download {what is that about? What is it?bootstrap....}

 

but Vic, now i am here and my computer suggested i ask for help

did that, but donty really understand the answers [my knowledge is spotty, to say the least]


cp dogecoin-1.14.2-x86_64-linux-gnu/bin/doge* .   this is what has me stumped

why, and how, what to do?

 

if you have a moment please


 
 

Sent: Friday, February 19, 2021 at 11:57 PM

**Comment by MostHated** [comment]
At least now there is an eta. Seems quite excessive, though?

![](https://i.imgur.com/AHGL47h.png)

**Comment by hendriks888** [comment]
about the instructions

 

2. copy to where in the dogecoin folder? just in, or into bin or another?

3. start dogecoind

then gui?

4. for sure :-)

 
 

Sent: Wednesday, February 24, 2021 at 1:33 PM

**Comment by hendriks888** [comment]
is that after you did the bootstrap"?

and where to put it?

 

ps, my wife run hers on windows laptop and after 5 days its now down to 5 years and 43 months

that's excessive  oo

 

Sent: Thursday, February 25, 2021 at 12:29 AM

**Comment by DemonRx** [comment]
@hendriks888 You'll have maximum connection of 8. So this is correct what you are seeing. Network syncing is just slow due to possibly the speed of your computer and / internet service.  You'll just have to be patient. 

But did you actually download the bootstrap from the torrent ? It's being served by discord's server which you can get here:
https://dogecoin.gg/dogecoin-bootstrap-2021-01-29.torrent (if you  have a torrent client this should open the program up automatically and start downloading when you double click it). If not install a client such as qbittorrent. 

Once you download it, it should contain two folders: **blocks** and **chainstate**.  

You need to place them in the dogecoin data directory.
On windows this is in `C:\Users\YourUserName\Appdata\Roaming\dogecoin`
On linux this is in `/home/user/.dogecoin`

**replace *YourUserName* or *user* with your windows or linux username

Good luck !

**Comment by MostHated** [comment]
I just downloaded the bootstrap torrent now, this was the first I had seen it. I just did as instructions mentioned and got the app from releases, opened it up, let it do it's thing.

I will try whatever I need to do with the bootstrap thing.

**Comment by hendriks888** [comment]
After i did this, how do i save or activate it

?

what is the next command?

 


# vi ~/.dogecoin/dogecoin.conf
rpcallowip=127.0.0.1
listen=1
server=1
rpcport=9888
daemon=1
addnode=1.seed.dogecoin.gg
addnode=2.seed.dogecoin.gg
addnode=3.seed.dogecoin.gg
addnode=4.seed.dogecoin.gg
rpcuser=dogecoinuser
rpcpassword=dogepassword


now what to do?
 

Sent: Friday, February 19, 2021 at 11:57 PM

**Comment by hendriks888** [comment]
I created a drive for dogy

unzipped dogecoin-1.14.2 there directory name same [dogecoin-1.14.2]

then ran dogecoind from inside a terminal inside the bin directory

so, bin + include + lib + blocks + share  are now directories in [dogecoin-1.14.2]

 

will my data directory still be in /home/user/.dogecoin

??? because i find nothing there

 

or, can i set the data directory to where i want it? the reason is my current istallation drive isnt big enoug so I made a plan  ;-)

 

And

Thank you

Your answer was very helpful and clear tro follow


Sent: Thursday, February 25, 2021 at 3:24 AM

**Comment by DemonRx** [comment]
@hendriks888 **user** should be your actual linux username. then you'll find your data directory there.  If you're not sure what that is then type in the terminal >   `whoami`

You can also do: `cd $HOME/.dogecoin` this command will take you inside your data folder. 

You could run the dogecoin-qt instead from inside the bin folder. this will help you see easier the status and sync progress of your wallet. 

Also don't tell the rpcpassword and rpcuser to anyone. You should change that.

**Comment by longvic0** [comment]
Hi,
 Here is my compressed bootstrap for dogecoin (2021-02-24) : https://drive.google.com/file/d/1v3Fdc0DqRpMrf7eZFUdFn7ziWKDhm9Xk/view?usp=sharing
  The bootstrap data will speedup your wallet synchronization with the $dogecoin network. If you don't have a bootstrap , your wallet need to pull every single block from the network ( since block height 1 to 3621880 ), it's about 3 millions block. It will take 2-3 days.
  After you download the bootstrap data, just put the compressed files to your $doge folder:
`
//stop the current wallet.
 killall dogecoin
 // backup data
 cp -rp ~/.dogecoin/ ~/.dogecoin_backup/
// move the compressed bootstrap to $doge folder
 cp dogecoin-bootstrap-20210224.tar.gz ~/.dogecoin/
 tar xvf dogecoin-bootstrap-20210224.tar.gz
// start your dogecoin wallet client again and wait about half an hour.
`

**Comment by hendriks888** [comment]
Thanks Vic

 

currently in China, so google drive is dead to me

So, why create that other user in your setting up a doge .....whats its name

 
 

Sent: Thursday, February 25, 2021 at 10:42 AM

**Comment by longvic0** [comment]
Hi
 Let’s add my 微信.
![Uploading E40B51F8-AA76-4D53-981F-2FD07FE5551A.jpeg…]()

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin We can close this one.
