### ISSUE TITLE
QT wallet console command replies with "null"

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#1750]
### Describe the issue

QT wallet replies `null` to `addnode` command in console.

### Expected behaviour

Something informative

### Actual behaviour

Much confuse.

### Screenshots.

![screenshot](https://cdn.discordapp.com/attachments/450586589165256705/812766261577515008/unknown.png)

### Any extra information that might be useful in the debugging process.

Filing for visibility.

**Comment by shibe2** [comment]
The best solution:

1. Any instruction that involves RPC commands or debug console should specify what replies are expected.
2. Require that anyone who uses RPC commands or debug console to understand basics of how it works and what the commands do. Otherwise they may get tricked into executing scam commands.
3. Provide separate UI for functions that non-savvy users may need.

**Comment by patricklodder** [comment]
Agree. I think 1 and 2 are taken care of, with the only point that explaining a null pointer is not user friendly at all (and it's a bit of a design flaw, as a void method doesn't return a null pointer, it returns nothing.) I'm not going to advocate fixing the design flaw within Dogecoin, if this is important, this should happen upstream in bitcoin/bitcoin, so that the APIs remain the same.

As for point 3... we can launch a separate (cross-version) project here on github for improving user friendliness through adding UI functions. I think this would be useful. Open to thoughts on that approach.

**Comment by p-j01** [comment]
@patricklodder Can you add steps to reproduce?

**Comment by p-j01** [comment]
@patricklodder Seems fixed in #1788. Should it be closed?
