### ISSUE TITLE
does dogecoin support omni ?

### ISSUE THREAD

**Issue by wade-liwei** [dogecoin/dogecoin#1787]
does dogecoin support omni ?

**Comment by patricklodder** [comment]
As in the layer that was built upon bitcoin? No.

**Comment by patricklodder** [comment]
I think on a protocol level, we should either have sufficient protocol compliance now with 1.14.3, or otherwise after segwit activation that I hope we can get in with the next major release. 

However, there are much more modern frameworks available nowadays, for example you could use [cosmos-sdk](https://github.com/cosmos/cosmos-sdk) with a cosmwasm or EVM module. If you then wish to interact with the DOGE asset, there is a lot of utxo-chain-to-cosmos bridging logic built at https://github.com/summa-tx/relays/tree/master/golang
