### ISSUE TITLE
Txid is missing and coins don't seem on the wallet address

### ISSUE THREAD

**Issue by kmatari** [dogecoin/dogecoin#1790]
I had transferred 148321,62 doge from an exchange to another exchange. The exchange used very low fee and the transaction got stucked. After my research, I tried the double spend, cpfp, and re-sent the same amount. Since the used wallet is the same and the fee is good enough, I was able to get the new transaction. 

For my previous transaction which was stucked, its txid dissappeared 14 hours ago. But, I cannot see the amount in my exchange's wallet address. Shouldn't it be gone there? What is the expected expiry time for this issue?

**Comment by patricklodder** [comment]
With 1.14.3, the expiration time is 24 hours. With 1.14.2 and older, the expiration is 2 weeks. So this depends on which version they run.

The exchange should respend those inputs with a proper fee (either fulfilling your withdrawal or cancel it) and then, once the new tx has sufficient confirmations, update their off-chain records.

**Comment by kmatari** [comment]
I meant, I had a txid and I kinda tried double spend through the exchange. Since they used the same wallet, it should have happened. Now the txid dissappeared. Does this mean that the transaction is reverted? And what is the ETA of reverted transactions in the code?

**Comment by patricklodder** [comment]
On the blockchain, transactions cannot be reverted. There are only 2 possible actions:

1. The transaction is valid and gets mined
2. The transaction is not valid and cannot get mined

Anything else is a non-final state, and from the exchange's perspective, unless they make sure that #2 is the case, the original transaction can still get mined if someone directly puts it into a block (because fees are not enforced inside blocks, only at the relay layer that sends it around the network, to miners.) So they really should take action on this.

Are your balances ok on the source exchange now? If they aren't you'll have to contact the exchange directly, because that is software written by the exchange, not by us.

**Comment by kmatari** [comment]
Well, I don't have the first transaction and its txid is lost after 2 days. So, they probably don't have the updated version otherwise it should have expired. 

Don't CPFP-double spend work on dogecoin blockchain? What is the way to recover the funds on my side? 

Exchange doesn't care about this issue, they say the blockchain will confirm the transaction but they paid very very low fee so it is not going to get confirmed. 

And why does the txid is lost from the explorer? What is the relevant code for this one? Let's not consider the expiration because it doesn't seem valid for this case.

**Comment by kmatari** [comment]
is it possible that I can rent some mine power and mine my own tx?

**Comment by patricklodder** [comment]
> Exchange doesn't care about this issue

Well, they really shouldn't send transactions with insufficient fee... so maybe we can help by contacting them and working through this. Could you send us an email at info@dogecoin.com with some more details, so we don't have to spam everyone's inbox with the details?

> And why does the txid is lost from the explorer? 

Each explorer has their own policy towards displaying mempool contents. This is fully outside of our control.

> is it possible that I can rent some mine power and mine my own tx?

Yes but that will be very expensive. Do you still have the full transaction data?
