### ISSUE TITLE
Dogecoin


### ISSUE THREAD

**Issue by leopsidom** [dogecoin/dogecoin#1824]

**Comment by nemiroff85** [comment]
Hello! Please help with the solution of the issue. Today I made a transfer of 1993 DOGE from Ledger's wallet to another address through the best-change exchanger. The transaction has hung with the Not yet redeemed status. How to be in this situation? The site operators are expecting a DOGE transfer from me in order to charge me money for them, but the transfer is frozen.
[Screen.docx](https://github.com/dogecoin/dogecoin/files/6326616/Screen.docx)
