### ISSUE TITLE
I have getting 127 error in doge build

### ISSUE THREAD

**Issue by jesuasir007** [dogecoin/dogecoin#1863]
Configuring native_ccache...
/bin/sh: 1: Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2021.222.0_x64__79rhkp1fndgsc:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program: not found
make: *** [funcs.mk:245: /mnt/c/dogecoin/dogecoin/depends/work/build/x86_64-w64-mingw32/native_ccache/3.3.3-a993c320af3/./.stamp_configured] Error 127

os win10 using ubuntu terminal app

**Comment by patricklodder** [comment]
Did you see the updated windows build docs from @michilumin at https://github.com/dogecoin/dogecoin/blob/1.14.4-dev/doc/build-windows.md ?

**Comment by dridri** [comment]
Just a simple random guess, but it seems to be caused by a path containing a space character :
`/mnt/c/Program: not found` (probably the infamous "Program Files" here)

**Comment by taurus228** [comment]
Отправлено из мобильной Почты Mail.ru


пятница, 30 апреля 2021 г., 9:32 +0300 от ***@***.***  ***@***.***>:

**Comment by angelcervantesa** [comment]
I can work on this.

**Comment by taurus228** [comment]
<div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0ODE0MDUxNw==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0ODE0MDUxNw==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0ODE0MDUxNw==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-848140517" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists current-user" data-body-version="816048d07fb9d7755a5eb600bac538e5bf366c79e5e55eecd477ed01d89f3d0d" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border-color: var(--color-box-border-info); border: 1px solid var(--color-border-primary); border-top-left-radius: 6px; border-top-right-radius: 6px; border-bottom-right-radius: 6px; border-bottom-left-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><div class="comment-reactions flex-items-center border-top  js-reactions-container" style="box-sizing: border-box; border-top: 1px solid var(--color-border-primary) !important; align-items: center !important; display: flex;"><details class="details-overlay details-reset dropdown hx_dropdown-fullscreen position-relative float-left d-inline-block reaction-popover-container reactions-menu js-reaction-popover-container" style="box-sizing: border-box; display: inline-block !important; position: relative; float: left !important;"><task-lists sortable="" style="box-sizing: border-box;">Configuring native_ccache...
/bin/sh: 1: Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2021.222.0_x64__79rhkp1fndgsc:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program: not found
make: *** [funcs.mk:245: /mnt/c/dogecoin/dogecoin/depends/work/build/x86_64-w64-mingw32/native_ccache/3.3.3-a993c320af3/./.stamp_configured] Error 127
os win10 using ubuntu terminal app
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly,  view it on GitHub , or  unsubscribe .
</task-lists><div class="comment-reactions flex-items-center border-top  js-reactions-container" style="box-sizing: border-box; border-top: 1px solid var(--color-border-primary) !important; align-items: center !important; display: flex;"><details class="details-overlay details-reset dropdown hx_dropdown-fullscreen position-relative float-left d-inline-block reaction-popover-container reactions-menu js-reaction-popover-container" style="box-sizing: border-box; display: inline-block !important; position: relative; float: left !important;"><summary class="btn-link reaction-summary-item add-reaction-btn" aria-label="Add your reaction" aria-haspopup="menu" role="button" style="box-sizing: border-box; display: inline-block; cursor: pointer; padding: 9px 15px 7px; font-size: inherit; color: var(--color-text-link); text-decoration: none; white-space: nowrap; -webkit-user-select: none; border: 0px; -webkit-appearance: none; opacity: 1; transition: opacity 0.1s ease-in-out; float: left; line-height: 18px; list-style: none;"><svg aria-hidden="true" viewBox="0 0 16 16" version="1.1" data-view-component="true" height="16" width="16" class="octicon octicon-smiley"><path fill-rule="evenodd" d="M1.5 8a6.5 6.5 0 1113 0 6.5 6.5 0 01-13 0zM8 0a8 8 0 100 16A8 8 0 008 0zM5 8a1 1 0 100-2 1 1 0 000 2zm7-1a1 1 0 11-2 0 1 1 0 012 0zM5.32 9.636a.75.75 0 011.038.175l.007.009c.103.118.22.222.35.31.264.178.683.37 1.285.37.602 0 1.02-.192 1.285-.371.13-.088.247-.192.35-.31l.007-.008a.75.75 0 111.222.87l-.614-.431c.614.43.614.431.613.431v.001l-.001.002-.002.003-.005.007-.014.019a1.984 1.984 0 01-.184.213c-.16.166-.338.316-.53.445-.63.418-1.37.638-2.127.629-.946 0-1.652-.308-2.126-.63a3.32 3.32 0 01-.715-.657l-.014-.02-.005-.006-.002-.003v-.002h-.001l.613-.432-.614.43a.75.75 0 01.183-1.044h.001z"></path></svg></summary></details></div></details></div><form class="js-comment-update" id="issuecomment-848140517-edit-form" action="/dogecoin/dogecoin/issue_comments/848140517" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0ODE1ODYxNg==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0ODE1ODYxNg==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0ODE1ODYxNg==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-848158616" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container js-comment timeline-comment--caret reorderable-task-lists" data-body-version="204a87a4181bf6b87117ef246e02d2f5c8983e6ca38548190b905223a32ae9a6" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border: 1px solid var(--color-border-primary); border-top-left-radius: 6px; border-top-right-radius: 6px; border-bottom-right-radius: 6px; border-bottom-left-radius: 6px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.301961); -webkit-text-size-adjust: 100%; -webkit-text-stroke-width: 0px; text-decoration: none;"><div class="timeline-comment-header clearfix d-block d-sm-flex" style="box-sizing: border-box; display: flex; align-items: center; padding-right: 16px; padding-left: 16px; color: var(--color-text-secondary); flex-direction: row-reverse; background-color: var(--color-bg-tertiary); border-bottom: 1px solid var(--color-border-primary); border-top-left-radius: 6px; border-top-right-radius: 6px;"><div class="timeline-comment-actions flex-shrink-0" style="box-sizing: border-box; flex-shrink: 0 !important; float: right; margin-left: 8px;"><details class="details-overlay details-reset position-relative d-inline-block" style="box-sizing: border-box; display: inline-block !important; position: relative !important;"><summary class="btn-link timeline-comment-action Link--secondary" aria-haspopup="menu" role="button" style="box-sizing: border-box; display: inline-block; cursor: pointer; padding: 8px 4px; font-size: inherit; color: var(--color-text-tertiary); text-decoration: none; white-space: nowrap; -webkit-user-select: none; border: 0px; -webkit-appearance: none; list-style: none;"><svg aria-label="Show options" role="img" viewBox="0 0 16 16" version="1.1" data-view-component="true" height="16" width="16" class="octicon octicon-kebab-horizontal"><path d="M8 9a1.5 1.5 0 100-3 1.5 1.5 0 000 3zM1.5 9a1.5 1.5 0 100-3 1.5 1.5 0 000 3zm13 0a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"></path></svg></summary></details></div></div></div><br class="Apple-interchange-newline"></div></div></div></div>

**Comment by taurus228** [comment]
Join your team on Slack

taurussssssssss ***@***.***) has invited you to use Slack with them, in a workspace called Hi.

Workspace name: Hi

H

hi-vh78894.slack.com []

Join Now [https://join.slack.com/t/hi-vh78894/invite/enQtMjM5NDY2OTc1OTI5Ny0yODdlOTJkYWRhNWMyZmMwMDhhYzcxZGU1ODgyODBiYzU4ZWEyMjk4NTRjYWU4YTM5MTYzYTViY2E3NWI3ZGU2?x=x-p932605326480-921137271987-2382051818226]

taurussssssssss and 4 others have already joined

[Profile picture of taurussssssssss.][Profile picture of taurussssss.][Profile picture of taurussssssssss.][Profile picture of support.][Profile picture of atom.]

What is Slack?

Slack is a messaging app for teams, a place you can collaborate on projects and organize conversations — so you can work together, no matter where you are. Learn more about Slack [https://hi-vh78894.slack.com/x-p932605326480-921137271987-2382051818226/?utm_medium=email&utm_source=invitation-to-join]

**Comment by taurus228** [comment]
Join Hi on Slack

Just a quick reminder that your invitation from taurussssssssss ***@***.***​com) is waiting. Don’t miss out — come join the conversation in the Hi workspace!

Join Now [https://join.slack.com/t/hi-vh78894/invite/enQtMjM5NDY2OTc1OTI5Ny0yODdlOTJkYWRhNWMyZmMwMDhhYzcxZGU1ODgyODBiYzU4ZWEyMjk4NTRjYWU4YTM5MTYzYTViY2E3NWI3ZGU2?x=x-p932605326480-921137271987-2389483055460]
What is Slack? [https://slack.com/features]

Slack connects you with the people and apps you work with every day. Message with your team, share files, and get updates from other tools, all within Slack. Learn more [https://slack.com/features].

https://slack.com/features

Workspace name: Hi
Workspace URL: hi-vh78894.slack.com

**Comment by taurus228** [comment]
Welcome to Slack

Ta-da! You’ve joined your first Slack workspace and we couldn’t be more delighted. Here are your account details, along with some tips to help you get started.

Workspace name: Hi

H

hi-vh78894.slack.com []

Open Slack [https://hi-vh78894.slack.com/x-p932605326480-2394669833649-2389591183348/archives/CTEJDMRNH]

Tips for getting started

Take a quick tour

Get familiar with the basics of Slack [https://hi-vh78894.slack.com/x-p932605326480-2394669833649-2389591183348/resources/using-slack/your-quick-start-guide-to-slack?utm_medium=email&utm_source=confirmation-new-join] so you’re ready to get to work in no time.

Start working in channels

Keep conversations organized in channels [https://hi-vh78894.slack.com/x-p932605326480-2394669833649-2389591183348/features/channels?utm_medium=email&utm_source=confirmation-new-join] — organized spaces for everything related to a project, topic, or team.

Download Slack

For the best experience with Slack, download our apps [https://hi-vh78894.slack.com/x-p932605326480-2394669833649-2389591183348/downloads?utm_medium=email&utm_source=confirmation-new-join&t=TTEHT9LE4] for desktop and mobile.

See more tips [https://hi-vh78894.slack.com/x-p932605326480-2394669833649-2389591183348/resources/using-slack/top-5-tips-for-getting-started-in-slack?utm_medium=email&utm_source=confirmation-new-join]

If you have any questions as you’re getting started, drop us a note at ***@***.*** We’re glad you’re here!

**Comment by taurus228** [comment]
Slack account sign in from a new device

📱 Android in NGA

Signed in to Hi (https://hi-vh78894.slack.com/) on 8/16/21

Location based on IP address: 154.118.70.129

If this was you, you’re all set!

If this wasn’t you, please change your password [https://hi-vh78894.slack.com/x-p932605326480-2394669833649-2389591495076/account/settings#password]. You can also enable two-factor authentication [https://hi-vh78894.slack.com/x-p932605326480-2394669833649-2389591495076/account/settings#two_factor] to help secure your account.

**Comment by ReverseControl** [comment]
@jesuasir007 Were you able to resolve this? It seems like @dridri's observation is correct from looking at the error.

> Just a simple random guess, but it seems to be caused by a path containing a space character :
> `/mnt/c/Program: not found` (probably the infamous "Program Files" here)
> 
> edit: found this [microsoft/WSL#1766](https://github.com/microsoft/WSL/issues/1766)
