### ISSUE TITLE
Not yet redeemed

### ISSUE THREAD

**Issue by leo94666** [dogecoin/dogecoin#1880]
Not yet redeemed

Bug，Big Bug

**Comment by patricklodder** [comment]
What is not yet redeemed?

**Comment by danielmbradley** [comment]
@leo94666 Could you elaborate please so we can begin to look into whatever bug you may have discovered? Thank you.

**Comment by ghmac** [comment]
If he means Dog Chain I has similar issue.
Chain has stated it for over a week(s)
Doge Core has no transaction listed

**Comment by klawdarza** [comment]
I was scammed and I need help . I can see that my transaction iD and wallet address of recipient and it says not yet redeemed . 

I sent my dogecoins to


D6Sb98cbaDyQpYbHCMQmpaLxZe6LctqAj3

Because I was stupid to believe they would double it .
![image](https://user-images.githubusercontent.com/68105594/118347544-c1601500-b576-11eb-9264-8c14e98fc1cd.png)

The website was dogecoin-snl.com and I learned about this giveaway from YouTube . Why do they air scammers ? ![image](https://user-images.githubusercontent.com/68105594/118347555-d472e500-b576-11eb-85ce-25fed2b58d81.png)

**Comment by klawdarza** [comment]
Please help me find the recipient of Dogecoin address . I sent 8thousand .n

**Comment by klawdarza** [comment]
![image](https://user-images.githubusercontent.com/68105594/118347601-1f8cf800-b577-11eb-9c26-1635ec3c16b5.png)

This shows I sent it from Binance. My chat with this site disappeared .. i can't find the site ... They wanted me to send from my wallet ..it was Binance that sent my coins . Now they wanted me to connect my binance  to my trust wallet or any wallet so that they can give me back k the coins doubled.

I didn't know how to connect because i am really slow.. 
TThen when I wanted to chat .. I didn't find the site anymore . 

Thanks please I just want to be directed to a block chain expert . Thank you

**Comment by klawdarza** [comment]
![image](https://user-images.githubusercontent.com/68105594/118347712-d8533700-b577-11eb-9abb-6510c726cd69.png)

**Comment by klawdarza** [comment]
As you can see it is not yet redeemed in the photo above m

**Comment by klawdarza** [comment]
When I put the wallet address to search for balance , one site will say it's not valid and another site will say it ha 1.6 mill dollars . ![image](https://user-images.githubusercontent.com/68105594/118347828-ad1d1780-b578-11eb-8226-f7a38f4bf720.png)

When is lying or who is fake ? I think it's dogechain info

**Comment by klawdarza** [comment]
@patricklodder @ghmac @danielmbradley @leo94666 

Hello gentlemen, I wrote some posts about Dogecoin and not yet redeemed. Please ... If you have time , please read my post. I apologise for the grammar and typos.. 

Kathy

**Comment by klawdarza** [comment]
![image](https://user-images.githubusercontent.com/68105594/118347974-ae9b0f80-b579-11eb-93ad-4097ae971eed.png)


When I try to go to that server .. it says it acnt be found .

**Comment by klawdarza** [comment]
https://api.blockcypher.com/v1/doge/main/addrs/D6Sb98cbaDyQpYbHCMQmpaLxZe6LctqAj3/full?limit=50?unspentOnly=true&includeScript=true

**Comment by slightlyskepticalpotat** [comment]
One of the core principles of Dogecoin is that transactions are irreversible. Sorry for your loss.

**Comment by klawdarza** [comment]
Thank you for taking the time to answer an idiot like me. I wish there was a coin that was fully transparent and reversible . There is a market for super honest people .

**Comment by rnicoll** [comment]
Not enough detail, closing.

**Comment by qwertyssimo** [comment]
please explaine me what i can do with transaction https://dogechain.info/tx/b3df3c553bc9f822746b543daa9da73c4f8685fec2dbeae0e06b761f98b12931 that i can see in 325 line "not yet redeemed" transaction made from pool to exchange wallet. on pool i see sent on exchange nothing.

**Comment by patricklodder** [comment]
@qwertyssimo Ask the exchange where your coin is.
