### ISSUE TITLE
Biggest issue that will destroy a lot of life’s 

### ISSUE THREAD

**Issue by exile337** [dogecoin/dogecoin#1890]
Dear team 

The main problem of the doge, that it has infinity emission, every day people gathering 14 million of new coins, demands will be very high, and a lot of people do not know about this and how it works, when the market get a lot of coins for sell, people will suicide their self, because of very fast price drop, 

Can you make limit for emission and burn coins per transaction??

**Comment by danielmbradley** [comment]
@exile337 Could you please elaborate on what you mean by emission and burn coins per transaction? I'm not entirely sure what the issue is here, do you. object to the underlying nature of Dogecoin? If so you may need to provide a lot more evidence to the community here that changing from a non-terminating, fixed reward per block to a limit on the number of coins that can be produced would be beneficial to the project and the holders of the asset. Even a contribution such as a white paper on how this would impact the overall pricing of the asset would be good. Thank you for the interest in Dogecoin though.

**Comment by exile337** [comment]
Read the Reddit, people worrying about, every 3 months there is new 6 billions mined, people won’t have that much money to keep the price, miners will keep selling their new coins, this will affect price very hard, you should add some that will burn fee tokens per transaction and something also that will keep marker and buyers, owners, feel safe. Other wise there will be trillion of coins and doge will die

**Comment by slightlyskepticalpotat** [comment]
Currently, 10000 * 60 * 24 * 365 = 5,256,000,000 = 5 billion Dogecoins are
generated every year. The circulating supply is 130 billion so the current
yearly inflation rate is less than 4%, which isn't that much (to reach 1
trillion Dogecoin would take nearly two centuries). In time, this will slow
until the amount of Dogecoins generated every year is roughly equal to the
amount of Dogecoins "lost" every year through on-purpose burns and lost
wallets. I think this is much better than setting an arbitrary cap, because
we want Dogecoins to be used as an actual currency instead of a store of
value like Bitcoin, and for that we need new Dogecoins coming in.

**Comment by exile337** [comment]
Well okay

**Comment by mr-stegosaurus** [comment]
the emissions incentivize the network security. if there aren't enough fees or emissions to incentivize mining, nobody would do it and the security budget would decrease. its not as simple as removing inflation and calling it  day

**Comment by kingsleyndiewo** [comment]
The new coins are a good thing. Incentive for mining and also diluting the whales. But a few points: 

- No one is going to do on-purpose burns when the price is even > 10$. 
- Client software will eventually improve to the point where accidental burns are minimal.
- For the same reason (improved UI/UX) the possibility of losing a wallet will decrease.

With a mainstream appeal and an increased unit value, the influx of new coins with no end will discourage HODLers. Which will create an infinite cycle of pumps and dumps. The model makes sense for a currency, less for a speculative investment. So OP is correct on that count.

**Comment by 0xmatt1** [comment]
For security we could implement a rolling 10 block reorg protection scheme.
For retaining value the only way I see that is making the supply capped vs
infinite

**Comment by langerhans** [comment]
#1674
