### ISSUE TITLE
Doge Chain Balance amout not showing up in Doge Core Wallet

### ISSUE THREAD

**Issue by ghmac** [dogecoin/dogecoin#1903]
### Describe the issue
Transfer of my first mining payout shows in dogechain but hasn't went to dogecore wallet

### Expected behaviour
Balance from dogechain should show in dogecore wallet

### Actual behaviour
Correct amount shows in dogechain

### Screenshots.
![Lost](https://user-images.githubusercontent.com/11984381/117606498-f78d3700-b127-11eb-8a06-ef60845a31e5.png)

### What version of Dogecoin Core are you using?
Dogecoin Core version v1.14.3 (64-bit)

### Machine specs:
- OS: Windows 8.1 Pro
- CPU: i7 4980HQ
- RAM: 32 G
- Disk size: 500 G
- Disk Type (HD/SDD): SSD

**Comment by ghmac** [comment]
Yes long ago

**Comment by shibe2** [comment]
Show your receiving addresses from "File" menu.

**Comment by ghmac** [comment]
![Receives](https://user-images.githubusercontent.com/11984381/117689046-6057cc00-b187-11eb-97e8-1c48f89ed0a6.png

**Comment by ghmac** [comment]
Hopes you can  see that?

**Comment by shibe2** [comment]
None of these addresses have received coins. Where do you expect to receive the payout?

**Comment by ghmac** [comment]
I agree totally, Is why I tried soo many times
But the address I was given at Unmineable I can not enter in Core Wallet/
It's the Last on dogechain's list #4

**Comment by ghmac** [comment]
hmmmm not my address? 
well I can verify my link on unmineable with a screen shot?

**Comment by ghmac** [comment]
@ randygreenfield428, 
I would love to have that much doge.
Unfortunately this was my first 30 I mined

**Comment by ghmac** [comment]
the one on dogechain.info ?
It's from unmineable.com.
It was assigned to me when I started to mine doge.
[unMineable - DOGE mining pool - Earn DOGE with your GPUs & CPUs.pdf](https://github.com/dogecoin/dogecoin/files/6454288/unMineable.-.DOGE.mining.pool.-.Earn.DOGE.with.your.GPUs.CPUs.pdf)

**Comment by shibe2** [comment]
The PDF says: "enter your address".

**Comment by ghmac** [comment]
doesn't have the DHUT,,,, address?

**Comment by shibe2** [comment]
It has that address, and it says "enter your address".

**Comment by ghmac** [comment]
That is my address the DHUT,,, one

**Comment by shibe2** [comment]
Did you enter it?

**Comment by ghmac** [comment]
In what? doge core?

**Comment by shibe2** [comment]
Where it says "enter your address".

**Comment by ghmac** [comment]
it comes up automatically

**Comment by shibe2** [comment]
Why does it say "enter your address"?

**Comment by ghmac** [comment]
as you see I started to mine another set

**Comment by ghmac** [comment]
or wallets i mean

**Comment by shibe2** [comment]
>as you see I started to mine another set

I don't see, and I don't understand what that means.

**Comment by incognitojam** [comment]
On unMineable.com, you paste/type in your _own_ address from Dogecoin Core or another wallet, unMineable doesn't "create an address" for you. Do you have another wallet that you might have copied the address from, which unMineable is sending your mining rewards to?

**Comment by ghmac** [comment]
@incognitojam 
This was my first experience at dogecoin and I learnt you could mine with your PC to acquire free coin. I took what I received with a referal

**Comment by shibe2** [comment]
Maybe payouts are going to the one who gave you the link.

**Comment by ghmac** [comment]
This is my address that mineable gave

**Comment by ghmac** [comment]
especially when it takes precaution it seems verifying your browser

**Comment by shibe2** [comment]
I don't know where it gets that address from, but you are supposed to enter your own address, as it says on the page.

Clearly in this case there is nothing wrong with Dogecoin Core and DogeChain. Case closed.

**Comment by ghmac** [comment]
My question would be, how can I put my address at mineable in doge core?

**Comment by ghmac** [comment]
Closed?

**Comment by ghmac** [comment]
Let me look 1st

**Comment by ghmac** [comment]
let me read your link

**Comment by incognitojam** [comment]
It looks like the coins have been sent to the wrong address due to user error unfortunately. unMineable has sent the coins to `DHUTjp6DRbwSNyQUhDQv81mSqM8TfdyCyf` but you don't have the keys for that address in your wallet (Dogecoin Core). There is no way to send the coins from that address to your wallet without the private key.

I would suggest immediately changing the address on unMineable to one you control - copy a new receiving address from Dogecoin Core.

**Comment by ghmac** [comment]
and I have re-scanned n  re-indexed my wallet on doge core awhile back, should I do again?

**Comment by shibe2** [comment]
There is nothing wrong with your wallet.

**Comment by ghmac** [comment]
OK so what do I do to get my first 30 coins?

**Comment by ghmac** [comment]
contact unmineable I guess? since it's back in their hands

**Comment by klawdarza** [comment]
@shibe2 hi sorry to bother but I was reading this conversation and really would appreciate some advice .

I have zero knowledge about  most of the tech stuff . 

I am looking for my Dogecoin which I sent throughBinance last May 9 to a site that said it was giving away dogecoins . It would give double .
I bought Dogecoin by credit card in Binance and had them send to an address which was provided by the site .
Binance gave me this ![image](https://user-images.githubusercontent.com/68105594/118362037-67843d00-b5c0-11eb-9b46-98260621796a.jpeg)

And this was what I was given by the site called elon-snl.com 
It was a link on the YouTube video of SNL interview after the show . So I assumed it was legitimate .

  ![image](https://user-images.githubusercontent.com/68105594/118362075-8aaeec80-b5c0-11eb-9d86-4724ab3c9ebe.png)
Binance sent it then I went back to the site to post proof that  Binance  did .

That's when I was informed that I needed a wallet because my dogecoins can be redeemed and are ready i have to connect that wallet  to Binance .only then can they send me the coins and I was told to transfer all my coins . I didn't have much but that assignment was difficult for me .. 
I am so stupid that I don't know how to do that .. so I went back to the site  to inform that I can't connect my trust wallet and I don't even know what smart chain looks like but the site is gone . 

It says server can't be found .

![image](https://user-images.githubusercontent.com/68105594/118362227-43752b80-b5c1-11eb-802b-682e04b2f5ab.png)

I have zero clue what is going on but I started to search how to find that address . I saw dogechain and blockchain and block decipher and unmineable . I have no clue but I just input the address on the search bar 

They have different answers .

One will say that the address is not valid 

One will say that the address has 1.5 mil dollars 
Unmineable will say it has trx and o .

Please I have never felt so stupid .. I learned my lesson. I will use bank checks as payment so I can always trace .. 

May I ask for advice what to do .. I don't understand why the address shows 20thou and not yet redeemed . 

Also I only use an iPhone and am I hacked ? 

I tweet for anyone who knows blockchain and no one answers not even dogecoin .

I don't think people know .
![image](https://user-images.githubusercontent.com/68105594/118362555-8388de00-b5c2-11eb-8bb7-0ffd94f11343.png)

![image](https://user-images.githubusercontent.com/68105594/118362576-8c79af80-b5c2-11eb-93c7-6667e601deeb.png)
![image](https://user-images.githubusercontent.com/68105594/118362586-98657180-b5c2-11eb-8d47-54f9778d3beb.png)

Please help me or endorse me . God bless

**Comment by shibe2** [comment]
@klawdarza This has nothing to do with Dogecoin Core.

**Comment by klawdarza** [comment]
I am sorry to post here .. I admit I only saw the word Doge and didn't think... Well it's because I don't know anything about tech and coins and I am ignorant. 

I was hoping to find help .. I realized after 6 days posting like a headless chicken that crypto is not inclusive for dumb ignorant people .. 

I wish I was smart because I would make a coin that was fully transparent and reversible and had a hotline and a crypto cop to help the ignorant.. 
Thank you for taking the time to inform me I posted in the wrong forum .

**Comment by rnicoll** [comment]
If coins have been sent to an address you don't control, there's no way for you to get them (any more than someone else can recover coins you hold). If you know who has the address you can contact them and request the send the coins to you.

As always, the decentralised part of a decentralised currency means there's no authority to move coins others hold.

**Comment by ghmac** [comment]
Well to me it's obvious no one holds, it's still sitting there unclaimed, but I mined it on that address
