### ISSUE TITLE
Coin mining update

### ISSUE THREAD

**Issue by n4rus** [dogecoin/dogecoin#1907]
Most of the comunity uncertainty goes to the fact that DOGE amount is not finite and we can see this principle pretty soon at the README.md file. 

If the objective is convert lost coins in the mining process we can factor a whole lost block, or a coin, in n numbers (1/n), and if the block or coin is mined, the whole value is subtracted from the end of the chain and the factors sent to the miners. Instead of adding large values, the amount of reward for each block could be a factor subtracted from each coin and given to the block miners.

The actual method of coins being added to the total net amount does not fit sustainable ecosystems in long runs, I humbly ask the comunity to revise this feature since DOGE is a great coin and could unlock a even greater potential if updated to a more widely accepted code.

**Comment by n4rus** [comment]
The loss of rewards could be adressed as well since it's part of lost amounts, but the main point I would like to see fixed is the huge amount of coins being generated, it really does not help at the coin value. Doge could behave much better.
Also agree with the part of it being not as useful as the other tools you mentioned, but it can be a good asset with the growing popularity, even better if somehow we could improve some aspects as those.

**Comment by raggingsoldier** [comment]
ETH implemented a burn code for excess ETH, to help reduce the coins over time. So that could be something that can be looked at but to help the value a supply limit would have to be put in place in my belief anyways.

The burn would help reduce extra coins not being used or help what you are talking about, ETH implemented it to help reduce coins as well as fee’s here is an article for some information don’t know if you are looking for this: https://www.google.com/amp/s/www.thestreet.com/crypto/.amp/ethereum/major-ethereum-code-change-that-reduces-supply-set-for-july

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by raggingsoldier** [comment]
If you have to do it yourself I doubt anyone will perform this task; but that was my idea, the main point is to decrease the massive amounts of doge being produced or generated from mining. No one said it was a scam.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by raggingsoldier** [comment]
You just have to be careful with that, asic’s farms are easy to target but GPU’ farms are more difficult and you don’t want to make doge coin mining non-profitable because then you’ll run into the lack of coins. Good luck though, I’ve helped with beam,ae, eth issues and it feels good when you fix an issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shibe2** [comment]
Some people are in favor of decrease of number of coins, other are not. So let those who want it burn their coins. Everyone wins, and no changes to Dogecoin protocol are needed.
