### ISSUE TITLE
Proof of stake as an optional layer 2 settlement layer. 

### ISSUE THREAD

**Issue by Drael64** [dogecoin/dogecoin#1924]
OK, this is a half formed idea. But what about instead of a lightening network, you use proof of stake purely for higher speed transactions. 

Transactions are validated by validators. Validators are rewarded a share of an additional transaction fee, much like how liquidity pooling works. Not being a coder, the exact details I'm unsure of. 

Just wondering if this might not be an approach that reduces power consumption, increases speed and thus usability at point of sale whilst keeping the main network secure and decentralized in a proven form? 

There's probably a lot about this that doesn't make sense. But maybe somewhere in it, someone can salvage something intelligent!

**Comment by Gistos** [comment]
Tht would be great hey. I came here after Elon's tweet that he is working with Doge Developers. To the Moon!!!

**Comment by darrenkis** [comment]
You guys are not right in the head.

**Comment by darrenkis** [comment]
> Tht would be great hey. I came here after Elon's tweet that he is working with Doge Developers. To the Moon!!!

There are no 'developers' LMAO

**Comment by paulVu** [comment]
Proof of stake is as a current financial system, that needs a guarantor as government. 
We need a solution to keep Doge still network secure and decentralized

**Comment by patrickdugan** [comment]
Guys, we're not forking Doge to proof of stake. If someone wants to do this, you can, but it will not be DOGE, it would be a new coin. PPC is a 2012 era early Proof-of-Stake, if you must.

**Comment by paulVu** [comment]
Do you have any idea to improve the transactions? I really want to figure out about that.

**Comment by patrickdugan** [comment]
We can improve the energy profile of the network by getting more LTC+DOGE
miners deployed with solar energy and battery and getting a good load
optimization, as illustrated in the recent ARK Invest whitepaper about the
energy mix.

We can improve the byte efficiency of the transactions by importing some of
the tech upgrades that BTC has enjoyed such as SegWit and Taproot, and
also, by using Layer 2 functionality, such as caching transactions in
multisig channels.

**Comment by EverythingWillBeCode** [comment]
Good Idea!

**Comment by Vishesh-Pandey** [comment]
> ht would be great hey. I came here after Elon's tweet that he is working with Doge Developers. To the Moon!!!

Same here as well. I came here after Elon's tweet. I want to somehow contribute here

**Comment by jorellano** [comment]
So, we are saying no staking/ smart contracts because it will change doge? Am i understanding this correctly?

**Comment by patrickdugan** [comment]
Staking and smart contracts are 2 completely different things that happen
to overlap in ETH.

DOGE should be composable with any DeFi apps developed for OP_Return
message based protocols, Lightning, Thorchain-type protocols, sidechains or
Blockstack-like layering of smart contract functionality, and things like
that. Any Ethereum Virtual Machine fork would likely be best served on a
sidechain. You could also do an EVM fork in an OP_Return layer, Wormhole
cash which was the Omni port project for Bitcoin Cash pertained to do that
but with tokens. Because BTC, LTC, DOGE et al. are based on the UTXO/merkel
tree data structures, it's not easy to get them to work dynamically in
DeFi. In TradeLayer (a successor project to Omni) we have a trade
construction that enables trading UTXOs for tokens in a single tx, but we
don't have an EVM feature like Wormhole attempted, but we would support
using tokens as collateral on some sidechain that has all that dynamism.

You can get a lot of functionality in C++ logic in an OP_Return protocol
without incorporating a virutual machine. What's nice about a VM is it lets
devs make more minute variations in functionality, and it can do away with
custodians in a big way.

Bitcoin protocol-based DeFi (which includes DOGE) is a lot harder to do
than ETH DeFi but it's arguably less error prone once developed.

**Comment by EquipeMID** [comment]
Hello guys, i can help, i know a little bit of Rust, Javascript, Postgresql and Python. Any protocol you define to improve Dogecoin, I would like to participate.

**Comment by Tracachang** [comment]
Proof of wow is better than Proof of stake, any experimented coder can confirm it, it is a revolutionary technology inspired by elon himself, that would make the difference to any existing crypto. We are working on it.

**Comment by mrbianchi** [comment]
I would like to help too!

**Comment by Drael64** [comment]
> Guys, we're not forking Doge to proof of stake. If someone wants to do this, you can, but it will not be DOGE, it would be a new coin. PPC is a 2012 era early Proof-of-Stake, if you must.

The idea here, ISN'T a fork. It's a side-chain used as a settlement layer.

**Comment by Drael64** [comment]
> Proof of stake is as a current financial system, that needs a guarantor as government.
> We need a solution to keep Doge still network secure and decentralized

This is a bit of misconception. XRP is in court because of selling a premine. It's not their validation method. Nor do they actually use proof of stake. 

Here, I'm not talking about changing the mining method. I'm talking about a side chain for transactions. This falls under zero security laws and would be legally the same.

**Comment by Drael64** [comment]
> > > Guys, we're not forking Doge to proof of stake. If someone wants to do this, you can, but it will not be DOGE, it would be a new coin. PPC is a 2012 era early Proof-of-Stake, if you must.
> > 
> > 
> > The idea here, ISN'T a fork. It's a side-chain used as a settlement layer.
> 
> doge doesnt need a side chain, at least yet...

It's not exactly fast enough for point of sale transactions, and it's proposed as a reserve currency. Right now, if you want to use it that way, you are dependent on third party processors. 

Currently some devs are proposing segwit and lightening as a scaling solution, despite that not really being viable. This would remove the need to stake coins on individual payees, making it viable.

**Comment by dan-ryan** [comment]
Who has Elon talked to, and what has he suggested to make Doge more environmentally friendly?
Another option instead of proof of stake is proof of space. 
This is greener than POW:
https://en.wikipedia.org/wiki/Proof_of_space

**Comment by era-coder** [comment]
That is not true segwit is a blocksize increase that doesn’t require a hardfork (everyone needs to upgrade node for a hardfork) and fixes transaction mailability that could enable lightning network to work ,Lightning is a decentralized network using smart contract functionality in the blockchain to enable instant payments across a network of participants.  and that is not how you spell Lightning ;) learn more here : http://lightning.network/ 
An individual with a high amount of stake in the dogecoin can join this Sidechain and steal funds .

**Comment by Drael64** [comment]
> That is not true segwit is a blocksize increase that doesn’t require a hardfork (everyone needs to upgrade node for a hardfork) and fixes transaction Edit:(malleability) that could enable lightning network to work ,Lightning is a decentralized network using smart contract functionality in the blockchain to enable instant payments across a network of participants. and that is not how you spell Lightning ;) learn more here : http://lightning.network/
> An individual with a high amount of stake in dogecoin can join this Sidechain and steal funds .

These issues have been successfully solved by existing networks using PoS. Algorand for example uses randomly assigned validators that cannot be predicted in advance. Thorchain uses two networks of validators so that the threshold of attack is 75%. 

There are several issues with lightening. One is that you need someone to set up payment channels before you can use it casually. And they only are motivated to do so, when people are already using it (fees). This problem is compounded by the fact that fast payments are ONLY useful for dogecoin at point of sale (retail) - where not one soul will adopt a partially functioning thing, and doge is already fast enough, and cheap enough for most other purposes (unless BTC). 

I believe lightening is an ill fit solution for doge, that will simply end up lying stagnant and not being used, like it is on LTC, or perhaps even worse.

**Comment by GiverofMemory** [comment]
> Guys, we're not forking Doge to proof of stake. If someone wants to do this, you can, but it will not be DOGE, it would be a new coin. PPC is a 2012 era early Proof-of-Stake, if you must.

Are you a dev or just assuming?

**Comment by era-coder** [comment]
> > That is not true segwit is a blocksize increase that doesn’t require a hardfork (everyone needs to upgrade node for a hardfork) and fixes transaction Edit:(malleability) that could enable lightning network to work ,Lightning is a decentralized network using smart contract functionality in the blockchain to enable instant payments across a network of participants. and that is not how you spell Lightning ;) learn more here : http://lightning.network/
> 
> > An individual with a high amount of stake in dogecoin can join this Sidechain and steal funds .
> 
> 
> 
> These issues have been successfully solved by existing networks using PoS. Algorand for example uses randomly assigned validators that cannot be predicted in advance. Thorchain uses two networks of validators that must agree so that the threshold of attack is 75%. 
> 
> 
> 
> You could do all of these things AND limit transactions to 10k doge, and it'd probably be as technically secure as bitcoin tbh and also remain 100% decentralized. Like you would need to repeatedly attempt to bribe 75% of validators (and actually pay them even when it fails), only to be able to doublespend in amounts limited by a cap. I think this basically would make it entirely undesirable to even attempt it. 
> 
> 
> 
> There are several issues with lightening. One is that you need someone to set up payment channels before you can use it casually (multihop). 
> 
> 
> 
> And they only are motivated to do so, when people are already using it (fees). 
> 
> 
> 
> This problem is compounded by the fact that fast payments are ONLY useful for dogecoin at point of sale (retail) - where not one soul will adopt a partially functioning thing, and doge is already fast enough, and cheap enough for most other purposes (unlike BTC). 
> 
> 
> 
> I believe lightening is an ill fit solution for doge, that will simply end up lying stagnant and not being used, like it is on LTC, or perhaps even worse. Whereas a side chain that only requires a small network of validators to be fully functional will scale and be adopted easily - fully functional and practical almost immediately after release. 

Even if proof of stake worked having it as a Sidechain , who gets to create the peg out and peg in? 
Crypto is barely even fairly and widely owned, and distributed which is worse for doge , one adresse alone controls 36.7 billion doge out of the total 130 billion . If that person were to become the Sidechain validator he would be the "network" https://bitinfocharts.com/dogecoin/address/DH5yaieqoZN36fDVciNyRueRGvGLR3mr7L

**Comment by Drael64** [comment]
> Even if proof of stake worked having it as a Sidechain , who gets to create the peg out and peg in?
> Crypto is barely even fairly and widely owned, and distributed which is worse for doge , one adresse alone controls 36.7 billion doge out of the total 130 billion . If that person were to become the Sidechain validator he would be the "network" https://bitinfocharts.com/dogecoin/address/DH5yaieqoZN36fDVciNyRueRGvGLR3mr7L

I think there probably are decentralized solutions for that. Something like thorchains liquidity nodes. Not a coder, so not sure.  

In terms of wallets, that's most likely robinhood. With randomly assigned validators and a 75% attack requirement I don't think concentration is a major problem.

**Comment by era-coder** [comment]
> > Even if proof of stake worked having it as a Sidechain , who gets to create the peg out and peg in?
> 
> > Crypto is barely even fairly and widely owned, and distributed which is worse for doge , one adresse alone controls 36.7 billion doge out of the total 130 billion . If that person were to become the Sidechain validator he would be the "network" https://bitinfocharts.com/dogecoin/address/DH5yaieqoZN36fDVciNyRueRGvGLR3mr7L
> 
> 
> 
> I think there probably are decentralized solutions for that. Something like thorchains liquidity nodes. Not a coder, so not sure. But using something like cosmos SDK, there may be a network design where that pegging can be decentralized securely.  
> 
> 
> 
> In terms of wallets, that's most likely robinhood. With randomly assigned validators and a 75% attack requirement I don't think concentration is a major problem. Especially if you also limit transaction size, to say 10k doge. 
> 
> 
> 
> The amount of effort you'd need to spend, would far outweigh the rewards. 

With high likelihood it is not from an exchange https://twitter.com/cz_binance/status/1393811100655783941?s=21 and for proof of stake concentration is bad .

**Comment by patrickdugan** [comment]
I employ someone who works on ports and will be providing debug support on
this next build. He's also done the BTC port of TradeLayer and helped us
with tech debt in our Litecoin 0.16.3 based build that we're working on.

Elon doesn't control Doge, nor do these devs, it's that someone needs to do
the work to reconcile upstream BTC and LTC versions and get a version of
DOGE that is up to date, then he will handle the DOGE version of TradeLayer.

Sidechains are cool, you could commit OP_Return balances to a state channel
and represent it on a Tendermint sidechain (which uses PBFT, a more
sophisticated Proof of Stake).

This is how Thorchain works, they then hub in other chains to aggregate
liquidity. We've agreed to mine the LTC testnet on Thorchain's behalf so
they can continue testing there. We will be doing some integration project
with them.

You could send raw DOGE UTXO to a 3-of-5 or 10-of-15 or whatever 2/3rds
threshold multisig and that could act as a bridge to a sidechain, you'd
need to trust the federation of signers to some extent.

PoW based sidechain pledging was an R&D dead-end at Blockstream in 2015
because they never looked at PBFT/Tendermint.

Lightning is based on caching UTXOs in 2-of-2 multisig channels and then
chaining cheques, this requires a lot of capacity for routing and millions
of Jack Dorsey's money with some of the arguably smartest developers in
Bitcoin hasn't delivering a working liquidity product in 5.5 years of
development. But to be fair Omni and TradeLayer development goes back 7
years, and we're commenting over a repo that is getting its first major
port update in 6 years, so that's life.

You can do Lightning-esque caching with token balances without the routing
and TradeLayer supports this for both trades and payments.

There are other L2 solutions whose entrepreneurs can come here to shill its
application to Doge, if they like.

Ultimately control over DOGE comes down to LTC miners (who are also DOGE
miners via the magic of merge-mining) and to users who chose to run full
nodes.

I hope the 10MB block idea does not get huge traction here, we went through
this in 2017, I want people with retail laptops to be able to run a Full
Validating DOGE node. We have a feature in TradeLayer called Node Reward,
it's a perpetual faucet in our native token for people running full nodes.
Helps the network. People in Kenya should be able to run a DOGE node on
their laptops.

**Comment by patrickdugan** [comment]
Proof-reading myself, the pronouns, let me put my pronouns in the bio:

"Elon doesn't control Doge, nor do these devs, it's that someone needs to do
the work to reconcile upstream BTC and LTC versions and get a version of
DOGE that is up to date, then he will handle the DOGE version of TradeLayer." 

"He" here is my dev and not Elon or the core Doge devs, that read badly.

"This is how Thorchain works," - ok that's how Thorcoin might work integrated with TradeLayer on top of DOGE, so you can commit your sDOGE or USDC or USDG (native dollar coin based on sDOGE and Native DOGE/USD PERP) to an address. The way Thorchain works on ETH involves a smart contract bridge, etc. Didn't want to speak too broadly for Thorchain in general.

**Comment by DemonRx** [comment]
"Tesla will halt sales of cars using bitcoin due to the effects on the environment that cryptocurrency mining can have, Chief Executive Elon Musk said Wednesday, and prices of Tesla shares and the c..."

via @blockfolio

#BTC $BTC
https://blockfolio.com/coin/BTC/signal/XTHsTtRGd9

Rather than us being specific about changing to POS...instead ppl should consider that there maybe a movement that could start against cryptos negatively impacting our environment! 

Therefore, what can be done about this so doge stays ahead of the game and implement some alternative to curb this concern ?

**Comment by patrickdugan** [comment]
Demonstrate a utility-scale solar operation that load balances with Tesla
batteries and DOGE+LTC Mining.

**Comment by Drael64** [comment]
> I hope the 10MB block idea does not get huge traction here, we went through this in 2017, I want people with retail laptops to be able to run a Full Validating DOGE node. We have a feature in TradeLayer called Node Reward, it's a perpetual faucet in our native token for people running full nodes. Helps the network. People in Kenya should be able to run a DOGE node on their laptops.

Thanks for the run down on how thorchain works, and I suppose in theory how a layer-2/sidechain bridge could work for doge :)

Obviously there isn't any NEED to get 10x block sizes yet. Any increase at all would be future proofing, as blocks aren't being filled. 10x is certainly overkill rn (perhaps those are long term suggested targets?). 

It might be viable to double the block size, without increasing the storage requirements significantly on validating nodes, using some kind of hash history, rather than the full raw block. There was some blockchain researcher who told me about a technology like this, I just don't remember the name. 

If a sidechain or layer 2 exists that's immediately useable and workable (unlike IMO lightning) was in place, there would be less pressing need to scale onchain as well. 

I think the idea there is that it might be possible to onchain scale fully, despite failures to attempt to do so in the past. I don't read that personally as just ignoring the trade offs and obstacles that people have encountered attempting to do so previously. 

This said, here are a few approaches available here, that address the same issues. Some onchain scaling IMO isn't a terrible idea tho IMO. I guess I would say, that as a non-coder, I'm really here just listening as much as voicing my opinions and ideas.  Community consensus has that benefit - we can pool the wisdom of the experienced people who understand the details better than most do.

**Comment by Drael64** [comment]
> > > Even if proof of stake worked having it as a Sidechain , who gets to create the peg out and peg in?
> > 
> > 
> > > Crypto is barely even fairly and widely owned, and distributed which is worse for doge , one adresse alone controls 36.7 billion doge out of the total 130 billion . If that person were to become the Sidechain validator he would be the "network" https://bitinfocharts.com/dogecoin/address/DH5yaieqoZN36fDVciNyRueRGvGLR3mr7L
> > 
> > 
> > I think there probably are decentralized solutions for that. Something like thorchains liquidity nodes. Not a coder, so not sure. But using something like cosmos SDK, there may be a network design where that pegging can be decentralized securely.
> > In terms of wallets, that's most likely robinhood. With randomly assigned validators and a 75% attack requirement I don't think concentration is a major problem. Especially if you also limit transaction size, to say 10k doge.
> > The amount of effort you'd need to spend, would far outweigh the rewards.
> 
> With high likelihood it is not from an exchange https://twitter.com/cz_binance/status/1393811100655783941?s=21 and for proof of stake concentration is bad .

I trust CZ binance's tweets as unbiased expert opinion exactly zero. Looks like a cold storage to me tho. 

There are many ways to mitigate security issues in a proof of stake model.

**Comment by gubatron** [comment]
I've started asking questions in this respect on a thread (that's the most commented so far in the project) in which they're discussing what I believe to be a dead end for this project. They're discussing [if they should implement SegWit](https://github.com/dogecoin/dogecoin/issues/1798#issuecomment-843137004), and then some other people came talking about Lightning Network (LN), which I believe in practice has been a total failure for Bitcoin, therefore I believe it's a failed strategy, and a very divisive waste of time doing SegWit to fix malleability when it's been fixed very differently in BCH.

Judging by the current core devs reactions and most people there, thinking of implementing PoS will only result in a contentious fork, I can see that clearly.

I also proposed the idea of not implementing PoS from scratch, that we should instead evaluate forking a third generation blockchain to implement a hardfork of DOGE, DOGE2 and then build a bridge to transfer tokens to such chain.

However, I think this is also a failed strategy that would get very little traction and would divide the community.

I've come to the conclusion that we can chase a third path, let's make DOGE a multiblockchain currency.

This idea is permissionless, it requires no changes in the current protocol (95% sure of that) and we get to use existing codebase, know-how, infrastructure and capitalization by making use of the best 3rd-generation Proof of Stake blockchains out there.

We are here because we know the current blockchain technology substrate on which DOGE tokens live on is shit.

We can let them waste all the time coding SegWit and trying to get a LN off the ground, we know how that will end, it's going to take them at least 2 years to get it off the ground.

In the meantime, we create one way bridges to 3rd generation blockchains such as:

- Cardano (which allows for native asset minting and paying for transactions using the token you create, DOGE users wouldn't need ADA, just a way to claim their tokens on the other end in the transfer/burn process)
- Avalanche (they've already built bridges for Ethereum, and recently USDT, USDT is an example of a currency that is scaling to mass adoption through multicurrency, it owes no technological ego to any blockchain)
- Solana (50k TPS)
- Binance Smart Chain, which has the most retail DEFI traders on PancakeSwap, which would jump to add hundreds of millions of dollars of liquidity to DOGE-XXX liquidity pools
- Ethereum2
- Any other blockchains, the more the merrier

Then amongst these blockchains DOGE can be transffered no problem as there are mechanisms for Interchain communication being

**Comment by Drael64** [comment]
> * Binance Smart Chain, which has the most retail DEFI traders on PancakeSwap, which would jump to add hundreds of millions of dollars of liquidity to DOGE-XXX liquidity pools
> * Ethereum2

Ren protocol, p network, and binance smart chain already have two way bridges for doge.

**Comment by patrickdugan** [comment]
There's no 2 years coding something again, it's an upstream merge/port.

Your opinion of Bitcoin Protocol R&D and impression of recent proof of
stake chains being next-gen seems to belie a lack of experience working in
Bitcoin Layer 2.

Certainly wrapping DOGE for intra-chain bridging is possible, if imperfect.
You could also just do a wDOGE on ETH, SOL, etc. by putting it with a
centralized custodian.

But let us bring the DeFi to this Proof of Work Bitcoin Protocol base
you're decrying so much, and we'll let DOGE be what it is in its fullest,
rather than try to become something else.

Many, many other good things you could hold at lower market valuations if
you think Proof of Stake will never become subject to regulatory capture.

**Comment by Drael64** [comment]
> Many, many other good things you could hold at lower market valuations if you think Proof of Stake will never become subject to regulatory capture.

Certainly possible. Not so much because of the consensus method itself, but the common use of pre-mine sales as funding, the use of dao tokens and even coin redistribution (which could be seen as a dividend perhaps). Those lie within the realm of legal security definitions at least in the US.

**Comment by gubatron** [comment]
>Ideally IMO, if there is a crosschain solution even if it's another network, it would be presented as a 'default', and thus implemented in every wallet, dapp etc. Such that it was painless, and ever present. And it would need to work frictionlessly from early stages (unlike lightning).

On point. Extending the Transfer screen on this project would be a starting point, then patches would be submitted to other open source doge wallets.

**Comment by gubatron** [comment]
>There's no 2 years coding something again, it's an upstream merge/port.

True, but then there's the costs and efforts of bringing to life the L2 network, it'd be easier to use something that's up and running. Otherwise it's probably the people interested in doing this the ones that would set the first nodes and what not, then maybe people who are already running LN nodes for BTC (which are most likely BTC maximalists) the ones that could be convinced to also run nodes.

>Your opinion of Bitcoin Protocol R&D and impression of recent proof of
stake chains being next-gen seems to belie a lack of experience working in
Bitcoin Layer 2.

Perhaps true, my last attempt was about a year ago and it was very disappointing, in the case of BTC and the high fees it seemed to me that LN was pretty much a sats blackhole for most of the liquidity that enters.

>Certainly wrapping DOGE for intra-chain bridging is possible, if imperfect.
You could also just do a wDOGE on ETH, SOL, etc. by putting it with a
centralized custodian.
No centralized custodians, for that I build a centralized L2 service. I think with [proofs of burn](https://eprint.iacr.org/2019/1096.pdf) you can safely mint the asset on the target blockchain.

**Comment by Drael64** [comment]
> > Ideally IMO, if there is a crosschain solution even if it's another network, it would be presented as a 'default', and thus implemented in every wallet, dapp etc. Such that it was painless, and ever present. And it would need to work frictionlessly from early stages (unlike lightning).
> 
> On point. Extending the Transfer screen on this project would be a starting point, then patches would be submitted to other open source doge wallets.

Cosmos SDK is being used by basically everyone doing multichain. It's delegated proof of stake tendermint, pretty elegant I belive. 

If multichain is what you want, maybe dogecoin could work with them, build a bridge there to their network? Might act as a sort of crossroads. And if others using the SDK wanted to add doge it _might_ make that easier for them too?

It's possible the work thorchain has done, implementing doge might (as it's open source), be yoinkable for revelent code.  Seeing as they also use tendermint etc.

**Comment by patrickdugan** [comment]
Right Thor is another COSMOS, but they're more focused on aggregating trade
flows and swapping between chains whereas COSMOS is trying to be more
generalized.

Cool that you (Angel) are doing apps for sidechain pegs.

I hear you that Lightning has a lot of economic issues and the complexity
in the routing mechanisms (e.g. Channel Factories etc.) are trying to route
around inefficiencies caused by routing on redundant capital reserves. LN
Pool helps. I think LN is probably better as a wholesale clearing network
and settlement layer for Layer 3. There's also the possibility of
configuring new OP_Codes to do things like wrapping DOGE (or BTC, LTC) into
a token that has more dynamic properties such as derivatives settlement.
Discrete Log Contracts are interesting but lumpy, to get a smooth Delta 1
settlement on a contract in raw BTC is complex. With TradeLayer we do
LN-esque 2-of-2 channels for trading and have transfer tx for payments or
channel rebalancing, no routing needed. This capital efficiency comes from
having token balances vs. UTXO, you can have programmed logic for the token
balances that UTXOs don't support.

The point here, other than to shill my own work (haha), is to say that all
these different approaches are composable with each other in the state
space of Bitcoin protocol tx (I like to refer to LTC and DOGE as Bitcoin in
the sense of its formal attributes). So we can combine TradeLayer with LN
with Taproot with etc. This applies to all 3 of these chains. Atomic swaps
between them without relying on a Tendermint routing chain can work too. So
lots of cool stuff.

I think the point about bootstrapping is a really good one. DOGE community
has insane online engagement stats, I used to see how ICO marketers would
do it and have been in the space for 3 cycles, I've seen all the marketing.
What's good vibes about Doge people is the energy, enthusiasm, focus on
giving from sudden gains, and a more fun attitude.

I do think Elon made a slight error, shall we say, in the way that this
messaging was handled. But I get it.

TSLA is in a very privileged position by having the next-gen battery
manufacturing unit cost and capacity, in a world that buys into the BTC (or
LTC+DOGE) miner + Powerwall + Solar worldview. Solar gets cheaper, yes the
eWaste would be intense, monocultures aren't great in farming or in
electric grids, but you could Wall-E your way to a substantial fraction of
a K-I civ just with cheaper and cheaper solar and common elements. Deriving
lithium in isolated form is not easy and is geopolitically easier in some
countries, even though it's the #3 element. Battery scarcity will be a
thing for a while which could potentially make TSLA the most valuable
company on earth. TLSA shorts always analyzing the company like it's a car
company, it's a battery company. Maybe Elon does this for Scrypto ASICs and
even buys a lesser semi manufacturer, maybe it's in Buffalo! USA based
TSMC, I bet you could fold that into the Green New Deal. The REC trading
and the potential hyper-expansion of that market would also greatly enrich
TSLA. Elon knows this, but also believes in a Carbon Tax for pricing
externalities of depreciation of the global biome, a quintillion dollar
asset (you couldn't buy another one). I agree even though I also see his
prerogatives here. But batteries will be scarce so 100% solar-based mining
isn't really realistic in the next 10 years, but at least it poses an
answer to the question of, do these things blot the earth with carbon
emissions as they go to >100T total coin market cap.

So dissing BTC to both protect you REC business (understandable, a bigger
business than the BTC mark-to-market value) so you can then promote DOGE
(which uses a more RAM intensive consensus algo so less extreme nm-based
chip competitivity) was not super well done. It's ok, we all make mistakes,
I bought some 40k July Puts for 0.244 BTC the other night when this was
going on, $2000 less damage if I'd slept through it, meh. We're trying to
focus on the big picture.

Regarding transactions, the path of least resistance is to import all the
advances in Bitcoin and have them mesh. Actually getting people to use DeFi
on DOGE is a fun challenge, and there are a few go to market strategies
companies can approach as they promote these solutions. Doge ought to be at
least as fun as Binance Smart Chain DeFi, I can see it catching on.

SegWit was politicized in 2016/17 because of Mike Hearn's rage quit causing
similar market volatility (instead of a fast drop from 47k to 42k it was a
fast drop from $470 to $420) and the subsequent "Blocksize Wars" but this
war talk is silly. People aren't changing the world going on Twitter and
hammering the keys about one tech thing vs. another any more than they are
trying to do Twitter political activism (with some notable exceptions).
They change the word by going on GitHub and hammering the keys.

SegWit is what we'd adopt to increase the tx efficiency of our trades on
TradeLayer. Even if you fear SegWit addr's being less secure, you using
throwaway keys on multisig addresses to co-sign trades for tokens you
already pledged to the channel. So you might as well use SegWit and save on
fees. This is not controversial.

**Comment by Drael64** [comment]
I think really in some ways, it comes back to what has immediacy, and is intuitive. 

If lightening can be made, or defi for doge can be made, or multichain can be made - where they don't HAVE to be coaxed or encouraged into using it, where they see the thing right there, and their instincts entice them in, that's great! 

Scan address, click send. 

If it's familiar and obvious and low in friction. The best technical solutions on the world will fail if they aren't human. 

That's actually what I love about thorchain, not their technical solution. The fact you just jump in there and trade like any other DEX (even though it's native and crosschain), and you don't have to learn anything, or understand any of it. It just is. You can be oblivious to it's technicality. 

That's what makes dogecoin great, in it's present state, I think. It's not complex to use. It's straightforward. Scan/copy, hit send. 

This isn't an argument for or against anything. The same really goes for defi - creating LP tokens and such, can be an absolute mess. In anything user flow is important. 

But it's something I struggle with when considering layer 2s, and also chain bridges, and also defi. They might all be amazing technical marvels, but if there's one ounce of friction that total possible userbase is 1/10th'd or more.

**Comment by marrer99** [comment]
Cardano have a POS already working and staking pools. they have the concept of saturation to avoid whales to centralize the staking process, it works, but I think it is a more democratic and make it a better staking process if the protocol just do round-robin to select the next block signer pool, that way it does not matter how many stake you have as long as you have a minimum amount TBD, but how many pools are there. There will never be too many pools on the long term because people won't run pooling nodes if there are not cost effective, too many pools will make them to loose money, so the pools counter will tent to be stable around the minimum profitable point.

**Comment by marrer99** [comment]
by doing Round-Robin people will choose to stake on the pool they want and stability of the node will be considered more important, your mission as a pool node is to keep it up and running 24/7/365, because you don't want to loose your next opportunity to sign a block and the rewards that comes with it, for you and your pool members; the protocol should penalize the nodes every time they are down, the more you are down the lower you are in this performance weighted round-robin list mechanism.

**Comment by gubatron** [comment]
> Cardano have a POS already working and staking pools. they have the concept of saturation to avoid whales to centralize the staking process, it works, but I think it is a more democratic and make it a better staking process if the protocol just do round-robin to select the next block signer pool, that way it does not matter how many stake you have as long as you have a minimum amount TBD, but how many pools are there. There will never be too many pools on the long term because people won't run pooling nodes if there are not cost effective, too many pools will make them to loose money, so the pools counter will tent to be stable around the minimum profitable point.

That'd be so easy to attack, I know 3 of the people involved in Ouroborous, they were able to prove the protocol is safe even for adversaries they could never foresee.

**Comment by marrer99** [comment]
Can you explain how that attack could be done so easy? Anything is 'attackable' , but you just said it is very easy to do it in this case.

**Comment by gubatron** [comment]
> Can you explain how that attack could be done so easy? Anything is 'attackable' , but you just said it is very easy to do it in this case.

Here's the first one that comes off the top of my hand.
If you have a round Robin based selection process then you know who the next validators are going to be right? hire DDOS bot network and attack whoever is next so they can't process/validate blocks

**Comment by marrer99** [comment]
no, you don't. the only thing you know is that all up and running validators have to get a block to sign before another one is assigned to you in each round, but you don't know who is going to get the next one.

**Comment by simonmadsen** [comment]
just want to support the idae of moving to PoS for layer 1 even

**Comment by gubatron** [comment]
I gave up, they seem to be real stubborn on following Bitcoin's failed path of Segwit and LN, FML.

**Comment by delbonis** [comment]
>failed

[citation needed]

**Comment by simonmadsen** [comment]
> I gave up, they seem to be real stubborn on following Bitcoin's failed path of Segwit and LN, FML.

well i would stake doge for sure and can do it on the same machine that i stake eth

**Comment by ReverseControl** [comment]
This is a great topic to discuss and as such I recommend such ideas to be brought in the discussion section. For example, see https://github.com/dogecoin/dogecoin/discussions/2331.
