### ISSUE TITLE
Dogecoin qt not requeseting blocks

### ISSUE THREAD

**Issue by Relaxo143** [dogecoin/dogecoin#1937]
I have 10 outgoing connections + 100s of incoming ones. I am 50 blocks behind. Syncing was painful too. The client stayed at X blocks for minutes, then downloaded/validated thousands in a few seconds, then nothing for another few minutes. Seems like it's just not requesting blocks. RAM, disk and cpu usages are low. This is v1.14.3

**Comment by patricklodder** [comment]
- 1.14.0-1.14.2 had a bug in supplying blocks, which was fixed with #1676 in 1.14.3. Any peers of 1.14.3 or higher will supply blocks much faster than prior versions.
- 1.14.0-1.14.3 had a bug in requesting headers, which was fixed with #2417 in 1.14.4. Please use this version or higher to make sure your client efficiently requests headers.
