### ISSUE TITLE
Dogecoin switch to PoS consensus 

### ISSUE THREAD

**Issue by mmitech** [dogecoin/dogecoin#1952]
Just trying to discuss the idea before wasting any time on this, if the community is really interested in switching to PoS and updating the source code to the latest Bitcoin source to fix all [vulnerabilities](https://en.bitcoin.it/wiki/Common_Vulnerabilities_and_Exposures), there is a shortcut to all of this, [Particl](https://github.com/particl/particl-core)  is using a modified version of the PoS v3 which they call Particl Proof of Stake, it solves the main issues of the first of PoS by allowing for cold staking (thus not exposing keys) this also allows pool staking for smallholders (think of it as delegating staking powers to validators) and it also implements community governance by allowing voting, private transactions can be ported as well (CT and RingCT) but that can be ignored if the community decided to stick to fully transparent transactions.

If the community decides to go this path:

- Changes can be ported and consensus changed with a fork at a defined block height (this will bring compatibility with Bitcoin 0.19 as well, which includes huge improvements including segwit)
- Implement faster blocks (for example 1 min blocks)
- I wouldn't increase the block limit, but if the community insists on doing it, I wouldn't push it beyond 2MB, since there will be already 10x the capacity of BTC, with native segwit it is possible to unlock more txps by porting the lightning network.

**Edit:** I need to mention that this version of PoS (or any PoS system I know of FWIW) is inferior to the security of PoW, but its carbon footprint is neutral

**Comment by halahup** [comment]
How hard is it to pivot to PoS at this point?

**Comment by jambestwick** [comment]
I think POS can solve the problem about Reduce power consumption，but more and more Whale will stake dogecoin and doge more and more concentrated，like Present BTC ，so if you want dogecoin  make everyone can tanfer to each others ，please think carefully abount it，and I think  make some ecology  dapp is the more important。

**Comment by halahup** [comment]
> I think POS can solve the problem about Reduce power consumption，but more and more Whale will stake dogecoin and doge more and more concentrated，like Present BTC ，so if you want dogecoin make everyone can tanfer to each others ，please think carefully abount it，and I think make some ecology dapp is the more important。

Aren’t there better PoS consensus protocols already?

**Comment by fastcoin-project** [comment]
"If the community decides to go this path:

Changes can be ported and consensus changed with a fork at a defined block height (this will bring compatibility with Bitcoin 0.19 as well, which includes huge improvements including segwit)"
* Incorporating Segwit into Doge isn't possible without serious fundamental changes to the code, from our teams experience you cannot add segwit to aux-pow algo.  this would require a fork away from auw-pow and have serious known and unknown consequences when syncing SPV wallets or electrum for example.

"Implement faster blocks (for example 1 min blocks)"
* This would require another fork.  Probably unnecessary since zmq is functional and speeds are already sufficient.
 
"I wouldn't increase the block limit, but if the community insists on doing it, I wouldn't push it beyond 2MB, since there will be already 10x the capacity of BTC, with native segwit it is possible to unlock more txps by porting the lightning network."
* regarding block size only, this may also have serious known and unknown consequences to SPV wallets or electrum

**Comment by fastcoin-project** [comment]
> How hard is it to pivot to PoS at this point?

The code is difficult but the real question is community adoption.  Would the coin community make the change if POS client was introduced?  That's the question to ask.

If Musk wants POS, he should submit a bounty like everyone else.

**Comment by mmitech** [comment]
> "If the community decides to go this path:
> 
> Changes can be ported and consensus changed with a fork at a defined block height (this will bring compatibility with Bitcoin 0.19 as well, which includes huge improvements including segwit)"
> 
> * Incorporating Segwit into Doge isn't possible without serious fundamental changes to the code, from our teams experience you cannot add segwit to aux-pow algo.  this would require a fork away from auw-pow and have serious known and unknown consequences when syncing SPV wallets or electrum for example.
> 
> "Implement faster blocks (for example 1 min blocks)"
> 
> * This would require another fork.  Probably unnecessary since zmq is functional and speeds are already sufficient.
> 
> "I wouldn't increase the block limit, but if the community insists on doing it, I wouldn't push it beyond 2MB, since there will be already 10x the capacity of BTC, with native segwit it is possible to unlock more txps by porting the lightning network."
> 
> * regarding block size only, this may also have serious known and unknown consequences to SPV wallets or electrum

those changes would come with the PoS consensus change, they are already implemented in Particl and have been working for at least 3 years now.

Also, since we are discussing consensus changes, this already implies forking (probably multiple hard forks)

**Comment by danielmbradley** [comment]
I don't know if moving to PoS is really the solution to the primary concerns that seem to have spurned this concern. As far as I can see, the main source of this movement in the community appears to be derived from concern about the environmental impact of Dogecoin, not the protocol it uses. Perhaps it might be prudent if something as serious as a fork was on the cards to widen the scope and actually define the full set of issues that are of concern right now and come up with our own solution to say the top major problems present (e.g. network transaction capacity, environment, etc)?
The amount of interest Elon is generating for the coin right now might actually allow us to do something innovative in the space by bringing in new people to help. 
If we aren't making significant changes though that we can easily justify as solving a major issue, it will hard to get many on board with something as significant hard fork in the network.

**Comment by marrer99** [comment]
Cardano have a POS already working and staking pools. they have the concept of saturation to avoid whales to centralize the staking process, it works, but I think it is a more democratic and make it a better staking process if the protocol just do round-robin to select the next block signer pool, that way it does not matter how many stake you have as long as you have a minimum amount TBD, but how many pools are there.  There will never be too many pools on the long term because people won't run pooling nodes if there are not cost effective, too many pools will make them to loose money, so the pools counter will tent to be stable around the minimum profitable point.

**Comment by GiverofMemory** [comment]
I don't think PoS is a serious consideration.  There are numerous problems, the least of which our inflation rate is not enough to support it.  Do you think anyone would lock up their coins for 1 year to make 4% returns?  Your coins could go up or down 4% in a day.

**Comment by sruPL** [comment]
> I don't think PoS is a serious consideration. There are numerous problems, the least of which our inflation rate is not enough to support it. Do you think anyone would lock up their coins for 1 year to make 4% returns? Your coins could go up or down 4% in a day.

Solid PoS algorithms do not require freezing your funds. There are some out there that you can literally unstake at any given moment and sell if you need to or use for payment. Example being ADA.

**Comment by gubatron** [comment]
Hey guys, you should come over to this thread so we don't have redundancy

https://github.com/dogecoin/dogecoin/issues/1924

**Comment by marrer99** [comment]
> > I don't think PoS is a serious consideration. There are numerous problems, the least of which our inflation rate is not enough to support it. Do you think anyone would lock up their coins for 1 year to make 4% returns? Your coins could go up or down 4% in a day.
> 
> Solid PoS algorithms do not require freezing your funds. There are some out there that you can literally unstake at any given moment and sell if you need to or use for payment. Example being ADA.

Yes, I am talking about ADA here, Cardano. it is a solid POS system, not freezing needed

**Comment by BruceHunter** [comment]
PoW only! Keep it stable, improve it. Keep it free!

Lets not pull a ETC(PoW) -> ETH(PoW) -> ETH(PoS)

**Comment by gubatron** [comment]
PoW is a dead end Bruce, it's nothing but hype. We eventually need to move away from it. The Ethereum guys are really smart to have made that decision years ago.

Bitcoin will show the worst case scenario, it's a no brainer **you shouldn't need to waste a whole's country's energy intake to process 7 transactions per second**.

Then there's also the economic issues of PoW as the block rewards dwindle (in the case of Bitcoin), things will get ugly when block fees can't pay the bill, the entire hashrate will be very irregular, there will be all sorts of attacks to fork blocks that yield bigger fees.

Some princeton guys wrote a whole paper of the clusterf** that will come to be

[On the Instability of Bitcoin Without the Block Reward](https://www.cs.princeton.edu/~arvindn/publications/mining_CCS.pdf)

>Bitcoin provides two incentives for miners: block rewards
and transaction fees. The former accounts for the vast majority of miner revenues at the beginning of the system, but
it is expected to transition to the latter as the block rewards
dwindle. There has been an implicit belief that whether
miners are paid by block rewards or transaction fees does
not affect the security of the block chain.
We show that this is not the case. Our key insight is that
with only transaction fees, the variance of the block reward is
very high due to the exponentially distributed block arrival
time, and it becomes attractive to fork a “wealthy” block
to “steal” the rewards therein. We show that this results
in an equilibrium with undesirable properties for Bitcoin’s
security and performance, and even non-equilibria in some
circumstances. We also revisit selfish mining and show that
it can be made profitable for a miner with an arbitrarily low
hash power share, and who is arbitrarily poorly connected
within the network. Our results are derived from theoretical
analysis and confirmed by a new Bitcoin mining simulator
that may be of independent interest.
We discuss the troubling implications of our results for
Bitcoin’s future security and draw lessons for the design of
new cryptocurrencies.

**Comment by l4p4** [comment]
> I think POS can solve the problem about Reduce power consumption，but more and more Whale will stake dogecoin and doge more and more concentrated，like Present BTC ，so if you want dogecoin make everyone can tanfer to each others ，please think carefully abount it，and I think make some ecology dapp is the more important。

I agree! POS is not good for a currency "for the people", a currency for strength and liquidity, it does not need concentration in portfolios to carry out mining. POW is the best way not to let it accumulate in wallets and make the currency strong for use around the world; We see the strong exit of ETH for portfolios for its 2.0 update, is this a good thing? Only speculative for big whales, but to create a strong currency for everyday life, only a currency like Doge is able to supply the needs of the world market, from small to big business.

**Comment by l4p4** [comment]
> PoW is a dead end Bruce, it's nothing but hype due to all the sunk capital. We eventually need to move away from it. The Ethereum guys are really smart to have made that decision years ago.
> 
> Bitcoin will show the worst case scenario, it's a no brainer **you shouldn't need to waste a whole's country's energy intake to process 7 transactions per second**.
> 
> Then there's also the economic issues of PoW as the block rewards dwindle (in the case of Bitcoin), things will get ugly when block fees can't pay the bill, the entire hashrate will be very irregular, there will be all sorts of attacks to fork blocks that yield bigger fees.
> 
> Some princeton guys wrote a whole paper of the clusterf** that will come to be
> 
> [On the Instability of Bitcoin Without the Block Reward](https://www.cs.princeton.edu/~arvindn/publications/mining_CCS.pdf)
> 
> > Bitcoin provides two incentives for miners: block rewards
> > and transaction fees. The former accounts for the vast majority of miner revenues at the beginning of the system, but
> > it is expected to transition to the latter as the block rewards
> > dwindle. There has been an implicit belief that whether
> > miners are paid by block rewards or transaction fees does
> > not affect the security of the block chain.
> > We show that this is not the case. Our key insight is that
> > with only transaction fees, the variance of the block reward is
> > very high due to the exponentially distributed block arrival
> > time, and it becomes attractive to fork a “wealthy” block
> > to “steal” the rewards therein. We show that this results
> > in an equilibrium with undesirable properties for Bitcoin’s
> > security and performance, and even non-equilibria in some
> > circumstances. We also revisit selfish mining and show that
> > it can be made profitable for a miner with an arbitrarily low
> > hash power share, and who is arbitrarily poorly connected
> > within the network. Our results are derived from theoretical
> > analysis and confirmed by a new Bitcoin mining simulator
> > that may be of independent interest.
> > We discuss the troubling implications of our results for
> > Bitcoin’s future security and draw lessons for the design of
> > new cryptocurrencies.
> 
> Also PoW is unsafe from a government as an adversary scenario, ask people in Venezuela how the government would easily find them, seize their miners and put them in prison, the power consumption easily gives you away, not to mention all the unnecessary costs that go to middle men to keep the network running (power companies, ASIC manufacturers, shippers) and add to that all the extra costs (if you've ever mined you'll know well what I'm talking about)
> 
> Then you have all the a-symmetries, not everybody can mine given their access to cheap energy, and the inevitable backslash from the public Bitcoin has started to face and which will only get worse as the years pass and we have more natural disasters due to greenhouse emissions. It's a hard sell telling people most of the mining comes from clean energy sources when we know most of the hashrate is coming from corner-cutting China.
> 
> I don't think there's a single next gen blockchain using PoW, it's just not going to fly in the future.

It is not a complete truth, but it is also not a lie! But we don't need POS for Doge at the moment, we need more speed on the network for transactions and lower costs for that only! Maybe in the future, when we have a more distributed use, with Doge production already above demand, then yes, we can upgrade to POS and that will make the currency gain value at that moment, now that would only make the value go up strongly but without I intend with the use of it by mankind on a daily basis.

Just what Doge needs now is to increase the number of transactions and lower fees, with greater performance on his network, he is able to supply any market need worldwide!

**Comment by delbonis** [comment]
>Bitcoin will show the worst case scenario, it's a no brainer you shouldn't need to waste a whole's country's energy intake to process 7 transactions per second.

This is the key.  Don't do the transactions on the ledger then.  7 tx/s isn't much, but it's definitely *enough* to serve the needs of a billion users by shifting activity off the chain.

And, since it goes without being said enough, I would like to point out:

* energy usage in itself is morally neutral
* carbon emissions are problematic
* not all energy production releases carbon into the atmosphere
* not all carbon emissions come from energy production (in the US, only about 25%)
* eliminating fossil fuels from energy supply benefits *everyone*, not just people that use crypto

**Comment by geekwisdom** [comment]
I would like to propose a slightly different look at this.

1) Doge helps people gives back - That's what makes it better. So how can Doge give back 'power'

2) Competition in Proof of Work is simply a waste of energy. It's means multiple people using their own resources, and the 'best' one wins. This is analogous to buying a $100 dinner, just eating 2 fries and throwing the rest out. This does not help nor does it 'give back'

3) The Proof of Stake needs to allow anyone to stake, and un-stake at will. It also needs to allow cold staking

4) As noted the switch in consensus from PoW to PoS needs to occur at a specific block height.

5) Presently to participate in mining, you need to be part of a mining pool and it's great that this can occur in combination with litecoin BUT mining pools are simply a different type of 'whale' then the 'whales' staking with Proof of Stake. It seems to me to be better to give back to those actually running full nodes and staking, then those using up energy for the 'hopes' of winning.  I believe this analogous to the idea, it is better to invest $1/day in an RRSP  then to pay $/day for a lottery ticket. The money spent is the same, but the former gaurteees a return (give's back) while the latter is only the 'hope' of a return.

**Comment by mmitech** [comment]
I am closing this issue since I don't think most people on this thread understand the technical requirements for this.

**Comment by marrer99** [comment]
https://medium.com/@undersearcher/how-secure-is-cardano-5f1e076be968... no that easy to successfully attack
