### ISSUE TITLE
[feat] Quantum blockchain for DOGE.

### ISSUE THREAD

**Issue by MBillar** [dogecoin/dogecoin#2000]
What is the future of a coin that is not protected from already created quantum systems? I want to help with QuantDoge

**Comment by patricklodder** [comment]
Which aspect would you want to quantum-proof? ecdsa or scrypt?

**Comment by MBillar** [comment]
> Which aspect would you want to quantum-proof? ecdsa or scrypt?

ecdsa still based on simple to brute mathematics basics. I think better soultion is making it on quantum systems?

**Comment by MBillar** [comment]
I would like to work on this project. and I have a lot of ideas. I would like to develop a blockchain for elections, I have been thinking about it for so many days and hours, but there is no one to offer it.

**Comment by simonmadsen** [comment]
it is needed, but first it should be green so move to proof of stake or similar

**Comment by m-luck** [comment]
This is still far off. If modern hashing is broken, this repo is the least of our concerns. Source: studied in Tim Byrnes Quantum Computing Lab (Michael Lukiman, https://nyu.timbyrnes.net/michael-lukiman/)

**Comment by simonmadsen** [comment]
> This is still far off. If modern hashing is broken, this repo is the least of our concerns. Source: studied in Tim Byrnes Quantum Computing Lab (https://nyu.timbyrnes.net/michael-lukiman/)

5-10 years maybe, maybe before (doubtful), maybe after,
another important point according to my knowledge
to QC something you have to have the problem in QC domain.
so you have to transfer the problem first, and sometimes you cant even get hold of the problem
for example how will you get hold of the SSH private key if it is behind a server? 
Sure you can still try all the io brutforce much faster with qc if you have the public key?

actually a problem for crypto is that the problem is known. 
you know for example that there are 12 words seeds and you know they consist of 2048 words, right now.
so crypto could be an obvious QC target for brute force.

**Comment by AadiPapp** [comment]
This is great! I would love to see Doge to be first Quantum blockchain based coin

**Comment by simonmadsen** [comment]
not so much quantum based (though maybe also that) i think
more like protected from quantum computers

quantum computers are probably really facinating, if they work in the same way as quantum which I assume they do,
ill really like to learn the technicals of QC if anyone can point me in a good direction.
i didnt find the wiki super. ill really like to know more than just about gates.

**Comment by AadiPapp** [comment]
I see either ways it helps to simulate quantum computer attacks and see how the system holds up.
To me as a weight Engineer, John Preskill work on Qauntum computing and Quantum Gravity equivalence has brought me into Machine Learning and Quantum computing. There are resource from Quantum Country which is good and also Quantum annealing systems, Quantum Photonic Systems but I would love to see Quantum Topology and Quantum Gravity based systems

**Comment by simonmadsen** [comment]
thanks!

________________________________

**Comment by AadiPapp** [comment]
No problem, Also please check on Frank Wilczek work on Quantum Time Crystals, it is fascinating

**Comment by simonmadsen** [comment]
so actually just to be sure,

you have some kind of black box (necessary in quantum to not know the state) and hence both 1 and 0 is tried at the same time?
hence to brute force a passphrase consisting of 48 bits (6 bytes) you only need a 48+ qubit computer which would then brute force it in one cycle?

btw i know must passphrases are much longer than that and I guess it is because of encryption that it is said you need a QC to operate with millions of qubits in order to pose a threat to days security (QC have reached 50+ qubits so far)

________________________________

**Comment by patricklodder** [comment]
I'd recommend you build this as a standalone chain or a sidechain to Dogecoin for starters, so that it can mature and get field proven, before trying to push this towards Dogecoin Core.

Shall we move this discussion to https://www.reddit.com/r/dogecoindev ?
