### ISSUE TITLE
[Ideal] Transactions containing numbers 69 or 420 should be without fee

### ISSUE THREAD

**Issue by tomash1234** [dogecoin/dogecoin#2033]
I think it is good ideal that transactions containing numbers 69 and 420 should be free or with very lower fee. 
For example:
69
420,420
696,969 
...
Just imagine how would look like transactions lists. People would send these transactions much often

**Comment by qwahzi** [comment]
Why not just remove fees from all transactions?

https://github.com/dogecoin/dogecoin/issues/2024

**Comment by Mito9999** [comment]
> Why not just remove fees from all transactions?

This sounds like a great idea, but wouldn't this make the network far easier to attack?

**Comment by m-luck** [comment]
Realistically, we can make this a hashing side quest. If you happen to generate a ...420420 or ...696969 hash, you get a trivial extra reward. 

Introduce the zoomers to mining, so we ensure that there's enough mining knowhow for the generations going forward, in order to decentralize away from the entrenched clusters.

Other parts of the community should produce apps to let them generate hashes on their phone, like cookie clicker.

**Comment by PapauloGamerOfc** [comment]
> > Why not just remove fees from all transactions?
> 
> This sounds like a great idea, but wouldn't this make the network far easier to attack?

No, it wouldn't. You can prioritise transactions with more balance * time_since_use so then spammers will have low balance or low time_since_use. @qwahzi mentioned his PR #2024.

**Comment by patricklodder** [comment]
Sounds awesome, there is a discussion thread here: https://www.reddit.com/r/dogecoindev/comments/lg4hp7/reducing_dogecoin_transaction_fees/

**Comment by angelcervantesa** [comment]
isnt this just all noise?
