### ISSUE TITLE
Doge can not be people's crypto, if it is allowed to be concentrated!

### ISSUE THREAD

**Issue by IAmSurajBobade** [dogecoin/dogecoin#2049]
According to multiple reports, more than 80% of total DOGECOIN is hold by select people. Doge needs systematic majors to avoid centralization.
#tothemoon

**Comment by intarpit** [comment]
Please share the reference of your reports.

Below is my reference to the information
https://bitinfocharts.com/dogecoin/

Based on the above reference, the top 10 accounts hold around 45%.
Also, if you study their transaction behavior, you will notice that those accounts are exchanges and not individual people.

**Comment by Im-Mr-Chris** [comment]
Guys...the entire internet is still centralized.  Big tech operates the internet.  Doge NEEDS to be decentralized, otherwise it's just contaminated from the start.  I've asked about using smart contracts and putting this on the only decentralized internet project out there, icp.  They are literally the only ones who are fully decentralized and have grown a significant amount of nodes from the initial 4. idk, maybe im out of my reach, but its the only current option right now.  Imagine the instability later on should we decide to completely change what doge is built on after discovering something we hadn't planned for.  I just think we should be proactive and not reactive by learning from historical events.

**Comment by Im-Mr-Chris** [comment]
might i add that icp allows for transition between updates without putting the entire network at risk.  the subnets and canisters support this so well.

**Comment by rnicoll** [comment]
https://markets.businessinsider.com/news/stocks/dogecoin-whale-12-billion-wallet-address-likely-owner-patrick-lodder-2021-5-1030457161?op=1 is relevant here.

I will say, they're definitely not me, and I'm pretty sure it's not any of the other core maintainers, so fundamentally here there's a problem of "What's the suggested solution?"

**Comment by m-luck** [comment]
This is an argument to keep sustainable proof of work. Even if whales sell off, at least the technology and integrity of the ledger is preserved. Proof of stake would be otherwise more worrying.

This is also why the controlled inflation is actually a positive. It incentivizes the whales to spend on real world assets given bulldozer of depreciation. Now, of course, that requires stablecoin status first (i.e. currently can easily beat inflation as long as the price as an asset is going up dozens percent a day). Market saturation required.

**Comment by mbejda** [comment]
@IAmSurajBobade Dogecoin ( and Bitcoin ) is a fractal currency so concentration doesn't matter. The markets naturally break fractal currencies to meet equilibrium.

**Comment by patricklodder** [comment]
Hi! The dogecoin protocol is agnostic to ownership. You can always ask owners of large wallets if they want to sell you some DOGE tho!
