### ISSUE TITLE
Can you tie the price to Bitcoin so Bitcoin is the Gold and Doge is the Currency of the Gold? Say 1/10000 [feat] 

### ISSUE THREAD

**Issue by dcyroob** [dogecoin/dogecoin#2053]
The concept would be to fix the price to a percentage of Bitcoin.  So Bitcoin being the Gold and wealth storage, and Doge being the currency.. The value mirroring each other makes sense in terms of future world adoption. 

Sorry, I'm a newb so IDK if this is even possible, but it made sense to me so I figured I'd post it.

**Comment by heelhook** [comment]
This is a great idea.

**Comment by NoudZandbergen** [comment]
Don't we want doge to replace bitcoin so we don't have to care about it's flaws and it's ignorant/toxic supporters?

**Comment by dcyroob** [comment]
I don't think Bitcoin will go anywhere...  And I think Elon looks at it like Bitcoin is wealth storage for the wealthy, and Doge as a currency used by everyday people...  So IDK, it just kind of makes sense to tie them together.  Like when the US Dollar was backed by Gold, Doge is backed or tied to Bitcoin which would create stability and secure it's utility.

**Comment by Drael64** [comment]
BTC is deflationary. It can't reach price stability even at higher market size. You need price stability for a currency.

**Comment by NoudZandbergen** [comment]
> BTC is deflationary. It can't reach price stability even at higher market size. You need price stability for a currency.

True, but I don't think doge is much different in that regard.
What will make the difference in the end is when people actually start using it as a currency, and how much of the circulation that will actually be.

It's not just about having a stable value, it's about being regarded as it's own value. It's a currency when instead of having no services or having services be paid for in doge but valued in dollars, a service would have a fixed doge price.

I guess to kick-start it as a currency, we need to create a community that tries to create basic services and jobs, but only accepts payments in doge. Anyone down?

**Comment by Drael64** [comment]
> True, but I don't think doge is much different in that regard.

It's somewhat different. It has an ongoing supply, that never stops. True, that may not always exceed economic growth, but it is in this respect closer to matching demand than BTC, which in theory should make it more price stable at scale. 

Stable value is very important regardless. If the price of the dollar changed by 30% in a day, it would be unusable. A currency ideally needs a max variation at very large scale of +/-10% or so. It remains to be seen if doge can reach that, if the marketcap is big enough, but I think the jury is out on BTC in that respect.

**Comment by rnicoll** [comment]
The prices are set by the market, we do not set them. It's important to remember here that Dogecoin is decentralised, the vast majority of the coins have been mined already and are in the hands of individuals (who are free to determine their price to sell to you), and new mined coins go to the miners.
