### ISSUE TITLE
The doge days of summer fee free or reduced during this time period.July 3rd to August 11th 

### ISSUE THREAD

**Issue by philzweldz** [dogecoin/dogecoin#2058]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by m-luck** [comment]
Please fill out the template! 

I have given an example below. 

<h1>Feature Request </h1>

**Describe the Feature Request**

Reduce fees temporarily during these upcoming months to incentivize adoption. 

**Describe Preferred Solution**

During times when blocks are not being filled at maximum rates, offer a slight discount. In addition to the concept of "tenant" like node behavior, accounting for timezones this incentivizes worldwide adoption, as daytime in one country will be night time in another, and keeps the currency flowing 24/7.  

**Describe Alternatives**

Can have promotional lowered fees during certain days. The asset spikes on the weekends (due to it being the only market open) so weekday incentives can help gain the spotlight over traditional assets. 

**Related Code**

Some pseudo-code: 

```
if txRate < c: 
     txFee = txRate * (d/c)    // d is discount rate decided elsewhere
```

**Additional Context**

This incentivizes consistency and truly makes it an interplanetary currency, whose concept of days and peaks of activity are washed away by pure time-dilated diversity.

**Comment by m-luck** [comment]
Fun fact: I asked a question about interplanetary potential in my graduate class in 2018 with Stanford/NYU Professor Joseph Bonneau. JCB, if you see this, I just had to post the Piazza post! Sue me! 

![signal-2021-05-24-213543_001](https://user-images.githubusercontent.com/43768081/119439941-369abb00-bcd8-11eb-8ccc-8fd3c83aa46c.png)

![signal-2021-05-24-213543_002](https://user-images.githubusercontent.com/43768081/119439961-40242300-bcd8-11eb-85d1-2f9b8a5e7772.png)

**Comment by m-luck** [comment]
Eventually, we may need to account for this through a DAG layer (directed acyclic graph). But I will make this another post

**Comment by Drael64** [comment]
> Fun fact: I asked a question about interplanetary potential in my graduate class in 2018 with Stanford/NYU Professor Joseph Bonneau. JCB, if you see this, I just had to post the Piazza post! Sue me!
> 
> ![signal-2021-05-24-213543_001](https://user-images.githubusercontent.com/43768081/119439941-369abb00-bcd8-11eb-8ccc-8fd3c83aa46c.png)
> 
> ![signal-2021-05-24-213543_002](https://user-images.githubusercontent.com/43768081/119439961-40242300-bcd8-11eb-85d1-2f9b8a5e7772.png)

Could have multiple blockchains, and just offer an exchange rate mediated by some kind of interplantary liquidity exchange (perhaps with a lightning style payment channel to the exchange).
