### ISSUE TITLE
[feat] Request -- Reduce ability of whales to pump and dump

### ISSUE THREAD

**Issue by KillerRabbit345** [dogecoin/dogecoin#2063]
# Feature Request

**Outsized Influence / Market Manipulation**
 
Large wallets have the ability to influence the price of doge.  While is probable that _some_ of the whale wallets are exchanges, it is not the case that all are exchanges.  This wallet, for example, dumps and dumps and then buys at the lower price.  Each 'reload' increases the amount of doge in the wallet. https://bitinfocharts.com/dogecoin/address/DG2mPCnCPXzbwiqKpE1husv3FA9s5t1WMt

**Describe Preferred Solution**

Larger, more frequent transactions should have a greater fee than smaller transactions.

Allow me to use doge to buy coffee and a hammer but discourage people from dumping 1,000,000 doge every few minutes to lower the value of the currency.  Exchanges should be able to register to except themselves from these additional fees.

Lower fees for everyday people, higher fees for the ultra wealthy.

Thanks devs!  Appreciate all you do!

**Comment by m-luck** [comment]
Need whales to be incentivized to participate. But I agree, if you can somehow keep their desire to participate, yet charge them for not holding (sort of like a gains tax), that can help reduce volatility.

**Comment by patricklodder** [comment]
I recommend you contact your local regulators and ask them if they can increase enforcement against market manipulation

**Comment by KillerRabbit345** [comment]
As someone who can only contribute ideas I appreciate the time you took to read and answer.

I disagree that this can only be solved externally -- in an unregulated market, market improving mechanisms can be built into the "tokenonomics" of the coin.  Just as certain structures encourage use or hording I think variable mining fees could improve trading.

But, again, if I disagree I send my thanks for your work.  Doge to the moon!

**Comment by CryptoCooked** [comment]
Regulators are becoming more and more corrupted and less and less useful re: Gamestop SAGA, SEC did nothing and it was a complete heist co-ordinated by them and the banks and the media together, contacting the regulators for this is pointless we're doing DOGE with blockchain to remove their involvement altogether, please re-open and consider this ticket. Making DOGE at least resistant to whale manipulation is vitally important, perhaps a decentralised exchange like a metamask sort of swap, where swap DOGE with BTC p2p, and make so no wallets can hold more than say 1000 000 D per wallet. This would make market manipulation at scale virtually impossible... stabilize the price and make it the people choice, price volatility is what is harming the adoption of crypto, taming the influence that the whales have is arguably one of the most important things, and places DOGE in a league of it's own. Elon Musk would absolutely love this suggestion, because then the whales would find it extremely difficult to short.

**Comment by CryptoCooked** [comment]
> As someone who can only contribute ideas I appreciate the time you took to read and answer.
> 
> I disagree that this can only be solved externally -- in an unregulated market, market improving mechanisms can be built into the "tokenonomics" of the coin. Just as certain structures encourage use or hording I think variable mining fees could improve trading.
> 
> But, again, if I disagree I send my thanks for your work. Doge to the moon!

This is absolutely true, and fundamentally important, please may you really look at this again. 

Imagine a coin that does not follow the price trend of all of the other coins, and rather just goes up organically/naturally rather than pumped and dumped by the banks and hedgefunds like all of the others... This would make DOGE noticed and frankly stop no one from piling in, bringing the market cap up to trillions...

**Comment by KillerRabbit345** [comment]
I really like that idea.  Perhaps you could submit a modified ticket in the future that combines my idea with yours since my powers of persuasion seem to have failed me :)

**Comment by CryptoCooked** [comment]
Done, see:
Prevent market manipulation buy whales using tokenomics
