### ISSUE TITLE
[feat] Renewable Energy-Solar energy

### ISSUE THREAD

**Issue by Corporea** [dogecoin/dogecoin#2075]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by rnicoll** [comment]
Decentralisation means miners are independent of the core maintainers, rather than something we (as open source software maintainers) control, as much as yes it would be great if they used more renewables.

The better news is others are trying to encourage more responsible practices: https://www.theverge.com/2021/5/24/22451900/elon-musk-bitcoin-miners-council-sustainability
