### ISSUE TITLE
Payment for tesla only with DOGE 

### ISSUE THREAD

**Issue by sajrus33** [dogecoin/dogecoin#2077]
# Feature Request

**Describe the Feature Request**
Make Tesla payments only with DOGE

**Describe Preferred Solution**
Payments for Tesla with DOGE only, it would hype DOGE and make our world much eco with its 1% energy usage compared to BTC

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by m-luck** [comment]
Yes, it's chicken and egg. As Ross says in a different thread, the capacity is at 17%, so there's some ways to go in terms of maxing out adoption. What the community must do is create a professional and great product, get a stable or somewhat  monotonically upward valuation, and the rest will follow. 

Luckily enough, what already exists is robust and secure as when it was originally forked, which is pretty good. So the only bottleneck really is a couple dozen prolific devs to maintain the project (easy with current inflow) and then a magnanimous driving publicization force behind them (I won't invoke the name).

Notice I don't say "we" yet, because I have my day job and will laser focus this weekend (or earlier if time permits) on getting the environment up and running.

**Comment by a2br** [comment]
... much off-topic? kinda surprised to even see the `external` tag. This doesn't have much to do with dogecoin development.
