### ISSUE TITLE
[feat] —A DogeSpaceMinning every rocket or satelite have the option to mining Doge and it will bee given away to all Holders

### ISSUE THREAD

**Issue by morlofff** [dogecoin/dogecoin#2087]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by morlofff** [comment]
Much wow

**Comment by AbcSxyZ** [comment]
Probably a partnership to make with #2084 !

I think it's too early for this kind of idea :)

**Comment by a2br** [comment]
doesn't make much sense but ok

**Comment by AbcSxyZ** [comment]
On which fact are you based to say this project is death ?

Some devs are here since years and are still working on it (https://blokt.com/news/dogecoin-doge-interview-core-dev-ross-nicoll-says-huge-step-forward-made-on-doge-ethereum-bridge-exclusive), there is some milestone to the project, they are speaking about improvement/issue since months (see some [project](https://github.com/dogecoin/dogecoin/projects) issues), by promoting the project (Elon & co) people can come, devs educate people on [reddit](https://www.reddit.com/user/Sporklin)/[twitch](https://www.twitch.tv/videos/1020188994).

Are you sure to know what's really going on before saying that ? Agree it's not necessary the most active open source project, but far from death.
