### ISSUE TITLE
[feat] Why not create a app where you can purchase doge and use it to purchase goods inside the app cheaper than you could get things with USD? 

### ISSUE THREAD

**Issue by FatTrucker3** [dogecoin/dogecoin#2094]
If people believe they can save money on a product they will join, it would create a larger following with other communities! This would create a larger amount of doge being baught and sold between the seller and customer

**Comment by AbcSxyZ** [comment]
There is at least [Flexa](https://twitter.com/FlexaHQ/status/1390351448962179072) & [bitpay](https://twitter.com/BitPay/status/1393193127393992710) who allow you to pay to shops.
All you need is a wallet (and the shop so), cashback/promotions will depend on the business deploying this kind of app.

It's a possible idea, but it won't be the right place to expect it. Personally I think it's more important to give to people the ability to spend rather than trying to get promotion or whatever to attract them (huge partnership work potentially), at least for the moment.
