### ISSUE TITLE
[feat] a newly systematic blockchain needs to be.

### ISSUE THREAD

**Issue by Mooncoil** [dogecoin/dogecoin#2142]
A vertical blockchain diary
A diary that keeps the codes
- basically we need to develop a " Lockers " around the world.
Whoever, joins the mining of Doge network, can buy or register for the locker.
A good locker will be coded with new language/alphabetic logs.
Which will create a chain amongst lockers. By which everyone will be able to mine ie hold a locker.  

# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by patricklodder** [comment]
Got that sweet locker code?

**Comment by ThisIsMyDogeAccount** [comment]
> Got that sweet locker code?

I'm somewhat loving your ways of asking for code over the last few days.

I'm interested in seeing it is devolves into just being "code" at some point.

But I like these funny ones a little bit more 😉

**Comment by patricklodder** [comment]
You know how you get into the shower, open your mind and get an idea?

That's not just you... it's what everyone has. Every day. Billions of people.

So I'm not interested in ideas. Because those are cheap.

I want code. Realize those ideas!

Realized ideas are good. Unrealized ideas are bad.

Closing this ❤️
