### ISSUE TITLE
Allow transaction reversal when fraud happens

### ISSUE THREAD

**Issue by CoolxIdea** [dogecoin/dogecoin#2159]
As there were fake websites/wallets appear to steal users passwords and Coins, can we 
1. Set up a platform to allow people report fraud and assign a number to each case
2. Other users (or anyone) can sign up as investigator and verify the fraud report is true with proves (explanations and screenshots)
3. If eg. 20 users from eg. 10 different countries verify the that the fraud report is true, then the transaction will be reversed automatically. And the person who get back the money can tip the addresses who helps in the process. (One button for the total amount, and money will be split evenly/ the first person gets more as that person has to do all the investigation vs the others maybe just reviewing the first person’s investigation)
4. Allow users to report fraud on revered transaction as well

**Comment by bezba** [comment]
can you use this?
https://support.blockchain.com/hc/en-us/articles/211164103-Enable-2-Step-Verification-2FA-#:~:text=2%2DStep%20Verification%20(commonly%20known,%2C%20Yubikey%2C%20or%20SMS%20codes.

**Comment by caidenvsanders** [comment]
This would go against the Blockchain principal of being immutable. Reversing transactions would not be possible because when a block is already mined, there isn't a way to go back without a network-wide consensus of a fork. This could be done if it were implemented as an auto-fork, but that would be extremely performance inhibiting and would be abused in many, many different ways. I think that this feature will not work and is not possible to implement on the Blockchain.
