### ISSUE TITLE
Delete INSTALL.md [or remove installation instruction from README]

### ISSUE THREAD

**Issue by AbcSxyZ** [dogecoin/dogecoin#2162]
Installation instruction are located in `INSTALL.md` and in `README.md`, information are redundant and need to be maintained in both place.

I would leave this information in a single place, probably on README.

Will depend of #1999.

**Comment by AbcSxyZ** [comment]
Commit access is needed to do that :)

**Comment by hrk2023** [comment]
Hey can I work on this?

**Comment by caidenvsanders** [comment]
This is a case where I think that it would probably be best to be redundant. It is standard procedure to put installation instructions in both a `README.MD` and an `INSTALL.MD`. This is because people who don't read the 'README.MD' will know where to look for the installation instructions in the 'INSTALL.MD'.

**Comment by AbcSxyZ** [comment]
INSTALL.md is refreshed in https://github.com/dogecoin/dogecoin/pull/2466.
It's also updating the README to make the repo more accessible
