### ISSUE TITLE
[feat] charity to help the people the coin represents

### ISSUE THREAD

**Issue by TheToneZone** [dogecoin/dogecoin#2173]
Hello Dogecoin Developers, 

I am new to this program so I apologize for probably coming off as a newb. I am here because I followed the posts about leaving potential ideas for future use of the coin. Let me start with saying in no way do I come close to understanding anything technical about programming so I am definitely not going to critique anything Dogecoin stands to represent. What I would like to offer is my idea to set up a charity fund that will receive automatic donations by some method of taking any percentage even just the smallest from each coin that is spent, bought, or by staking. I truthfully haven’t thought that part through because I feel it is not my place to decide that over y’all.
The part I have given thought to is the charity. I have 3 kids about 5-7 hrs apart. This allowed me to get an understanding of emotions and feelings that in my opinion represent the majority of their generations. In particular I feel as if the idea of “Love” or simply respecting each individual as a human has been diminishing since generations above mine (I am 35).  I really don’t know what to say might have caused this but it has to be a number of things. I think top influencing factors would have a lot to do with governmental influence using media and technology accompanied with lack of parental guidance. 
If this coin is supposed to represent the people than why not potentially using my idea in some way. I would also think that if Elon wants to use it for future space exploration, we will need the people to be here as well.  Either way I guess I just needed to try and get my charity idea out there since I have been thinking about it for quite some time now and don’t know how to get the idea to potential backers. I don’t want any money or dogecoin. I would just love to see the world I love not go to hell. I have put quite a bit of thought to my idea regarding financing and charity uses so if it interests the Doge Team then hit me back. My email is aml9163@me.com. 
Thank y’all very much for your time and sorry if I came off as a weirdo lol.

**Comment by patricklodder** [comment]
Hi! Don't give up hope! It won't go to hell, at least never permanently. People are 

One of the things that many of the "neo banks" do in their apps is automatically take your change or a percentage of what you spend into a vault, that then accumulates and you can spend it on charity or save some money for your new car... fully flexible. I think we can do the same with any Dogecoin wallet, to implement this.

I don't think this is a good feature for Dogecoin Core. But it could be a great and valuable feature for a mobile wallet. I'm not sure if any of the mobile wallets has this right now. 

I made you a post on reddit here: https://www.reddit.com/r/dogecoindev/comments/nlssas/from_github_charity_to_help_the_people_the_coin/ for people to comment. I will close & lock this issue here as it is not related to Dogecoin Core.
