### ISSUE TITLE
Make Tesla car pay automatically with dogecoin at charging station[feat] 

### ISSUE THREAD

**Issue by Lex169** [dogecoin/dogecoin#2189]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by ThisIsMyDogeAccount** [comment]
Please do not spam the GitHub

Only Tesla can decide if it wants to accept Dogecoin as payment

Please delete this

**Comment by AbcSxyZ** [comment]
@ThisIsMyDogeAccount Be kind & educate people, otherwise it can discourage people to come back with real issue :)
Let him learn from his mistake !

@Lex169 Github issues are here to raise trouble with the Dogecoin Core software.
As developers [said](https://www.reddit.com/r/dogecoindev/comments/nlryj5/development_update_20210526/) :

> We can’t control external companies, and requests that are for externals are probably better posted to the r/dogecoin subreddit.

You should use any social media or contact the company directly, you will have more impact.

**Comment by Lex169** [comment]
ok, thnx.
