### ISSUE TITLE
Accept Dogecoin as payment for starlink 

### ISSUE THREAD

**Issue by Lex169** [dogecoin/dogecoin#2190]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by ThisIsMyDogeAccount** [comment]
Please do not spam the GitHub

Only Starlink can choose to do that.

Please delete this

**Comment by AbcSxyZ** [comment]
@ThisIsMyDogeAccount Be kind & educate people, otherwise it can discourage people to come back with real issue :)
Let him learn from his mistake !

@Lex169 Github issues are here to raise trouble with the Dogecoin Core software.
As developers [said](https://www.reddit.com/r/dogecoindev/comments/nlryj5/development_update_20210526/) : 
> We can’t control external companies, and requests that are for externals are probably better posted to the r/dogecoin subreddit.

You should use any social media or contact the company directly, you will have more impact.

**Comment by Im-Mr-Chris** [comment]
> @ThisIsMyDogeAccount Be kind & educate people, otherwise it can discourage them to come back with real issue :)
> 
> Let him learn from his mistake !
> 
> 
> 
> @Lex169 Issues on Github are here to raise trouble with the Dogecoin Core software.
> 
> As developers [said](https://www.reddit.com/r/dogecoindev/comments/nlryj5/development_update_20210526/) : 
> 
> > We can’t control external companies, and requests that are for externals are probably better posted to the r/dogecoin subreddit.
> 
> 
> 
> You should use any social media or contact the company directly, you will have more impact.
> 
>  

I agree with the constructive criticism. If I had received what the other had said, I'd probably never look back at GitHub and end up just wrecking myself. We need to continue educating each other with something positive and to look forward to. Otherwise the introverts working in secret or are hiding their passion and interests, will turn away. 

This is just from my own experience. 

I understand this has been closed, but others in the future are still researching and may find this perspective valuable in the future.
