### ISSUE TITLE
Dogecoin Transaction Security

### ISSUE THREAD

**Issue by CoolxIdea** [dogecoin/dogecoin#2194]
Before completing Dogecoins transactions, is it possible to let both the sender and the recipient getting a confirmation before the coins really get sent? 

That will help avoid senders to send the coins to a wrong person for any reasons like copying wrong address, typo, receiving wrong address from recipient, etc

**Comment by rnicoll** [comment]
I'm wondering, actually, if we could do something a bit like Bluetooth pairing, where the recipient provides the address and a number, the sender puts the number into their wallet and the wallet generates a peer to peer message with the hash of the number, which is then relayed. If the recipient gets the right hash, they show it on the acceptance page. A bit like sending a small amount before all of a balance, but not actually a transaction.

**Comment by vertiond** [comment]
I think this could be done using a hash time locked contract?

**Comment by patricklodder** [comment]
In general, if we look at transaction construction solutions, be it PSBT / lightning invoices or one of the wallet protocols (i.e. metamask/walletconnect) the addressing becomes MUCH less interesting because it gets automated away behind links / javascript / QR codes. 

@CoolxIdea: What scenario did you envision where you want to have more interaction when signing a transaction?

**Comment by USDoge** [comment]
Retail transactions, while they settle. Something to this effect wiould be useful. Suspect we will always need a 3rd party to hedge risk, unless we can make transaction instant.

**Comment by CoolxIdea** [comment]
Thank you for the reply! I am thinking about two scenarios: 

Scenario 1. https://ca.news.yahoo.com/hong-kong-families-money-trapped-122547632.html 
Maybe take the Hong Kong news above as an example - some people planned to buy a house, they hired a law firm that kept their house payment ( buyer’s mortgage) and then would send it to the house seller once both the house buyer and seller sign the contract for the transaction at certain price. Unfortunately, the law firm shut down and the bank account was frozen, meaning that the buyers need to pay the mortgage every month, but they do not own the house. I think dogecoins could be super helpful in the case if it is possible that the amount of dogecoins is connected to a contract, and once both parties agree and sign, then the ownership of the house and the amount of doge are exchanged at the same time. This will eliminate the middleman (fees) and also avoid the risk mentioned above.  

Scenario 2. For daily transactions, if I send doge to a lot of different address, and one day I want to send my mother a big payment, it seems easy to accidentally put the wrong address, as there is no phone number/ anything pop up to confirm that is my mother’s address. I think maybe this would work: when sender create a transaction, the sender will also have an option to put a passcode, then the sender can send the passcode to the recipient separately. Only the correct recipient would be able to “unlock” and receive the payment with the passcode. And if no one claim it, then it will reverse back to the sender’s wallet. The reason why the passcode is preferably optional because if the payment is small (eg, tipping) then instant transaction without passcode is more preferred. 

I’m not very familiar with the existing protocol, so not very sure if it’s something already mentioned from the replies above, but thanks for reading through the whole message!!!

# DogeToTheMoon:)

**Comment by Ducktor8** [comment]
The solution you are proposing is for a problem that every payment system has, and probably adding another security layer like this would have an important impact on the reliabiity/security (man in the middle attacks), and also in the performance, because in your proposal you suggest a prior handshake before the real money transaction.
Probably and account based system would resolve this problem to the roots, without having to impact the transaction methods.

**Comment by patricklodder** [comment]
@CoolxIdea
 
Re: scenario 1.

In general, blockchain can only protect native things on the blockchain. There can be consensus that an imported piece of data on the blockchain is true, but there is a difference between a set of Dogecoin (or, more to-the-point and having actual implementations, Ethereum) validators agreeing that something is true, and facts that are universally true for a legal system. After all, I can import competing truths on competing chains, or even worse, on competing smart-contracts. So there is no fool-proof way to fully prevent things getting challenged in, say, a court, right now, unless there is a single recognized source of truth by said legal system.

If you'd ask me, it would be a good thing for governments to look at these types of blockchain applications, so that there is perhaps that single certified source of truth. Then, cross-chain integrations can be done (proofs can be exchanged and validated) and your scenario can be solved. There is no point in trying to do this on a single utxo chain like Dogecoin though, that would be very inefficient and impede Dogecoin's growth as a currency. There are better chain frameworks for this that can then interface with the DOGE asset.

Re: scenario 2.

I think this really should be solved with better payment / addressing protocols. Think combining [PSBT](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) with a scheme like proposed in [BIP75](https://github.com/bitcoin/bips/blob/master/bip-0075.mediawiki) or [BIP47](https://github.com/bitcoin/bips/blob/master/bip-0047.mediawiki). Most of the hard design work is already done for this and it *could* be a straightforward implementation.

**Comment by ReverseControl** [comment]
Privacy and decentralization are the core of Blockchain technology. To maintain those two properties and add that feature it would have to be implemented in the blockchain itself, something like IP at the Transport Layer of the OSI model, but on the Dogecoin blockchain itself. So that messages could be sent to wallets, using only the wallet (public key), as the identifier of where to send the messages. 

Such a layer would allow communications on the block chain without needing any information at all beyond what is publicly available by default, the wallet themselves. Plus, you can use the wallet itself to encrypt the message so that only the recipient can read the message; this is because the wallet itself is public key and only the recipient holds the private key.

There is no legal binding using a system like the one I made up here. It just gets the job done.

@patricklodder  @rnicoll  @CoolxIdea

**Comment by ReverseControl** [comment]
Any further engagement in this conversation should be in the discussion section: https://github.com/dogecoin/dogecoin/discussions. Should there be community interest a discussion could be started on this issue to continue hashing out ideas.
