### ISSUE TITLE
Without Private key? 

### ISSUE THREAD

**Issue by gator6615** [dogecoin/dogecoin#2199]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by gator6615** [comment]
My mining pool sent my coins to a wallet I've never used before???? Are they gone for good?

**Comment by AbcSxyZ** [comment]
As hint, did you give the right wallet when you register/configure it ?
Sadly, if it was misconfigured and the mining pool do not own the wallet where dogecoins were send, they probably won't be able to give you back the fund.

Anyway, this issue is related to your mining pools, you should contact them. Dogecoin core devs won't be able to help you, it's not related to the software source code.

**Comment by gator6615** [comment]
Hey sorry Thanks I thought so- I pull it up on Explorer and almost start to cry-

**Comment by gewure** [comment]
Issue should get closed.
