### ISSUE TITLE
[feat] can we create a way for active devs to get a % or commision of transaction fees? At least a fund me page or some way to tip them in doge for their hard work  

### ISSUE THREAD

**Issue by bdarty** [dogecoin/dogecoin#2209]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by bdarty** [comment]
Maybe a % of transaction fees go to a pool where it can be shared among the devs & coders? People may be more inclined to contribute to doge with some kind of incentive. Doesn't have to come from trans fees. I appreciate their hard work and would like to support those that help. Thanks doge fam! Keep up the good work!

**Comment by patricklodder** [comment]
*Wait so if I write software I should be entitled to life-time royalties? You opened my eyes! Let's be like all the corporate coins out there that self-enrich and then get into trouble with their shareholders because their market cap got surpassed by a joke.* 🤣 

For real though... just writing some code doesn't entitle anyone to the people's moneys. The reason for writing code for Dogecoin is because one believes that there should be a funny, accessible people's coin. No need to make tons of money off that, we leave that to the greedy peoples! They know who they are.

**Comment by bdarty** [comment]
Wow I guess I hit a nerve. I am not one of those rich, greedy a holes but I am a holder of doge and wouldn't mind giving some away to those that are on here trying to help make dogecoin better. I'm not a coder or dev so I can't help in that way. I was just trying to think of a way to help support the part of the doge family that spend hours of their time working on this. Again I'm not a dev & don't know how to write coding so idk what's feasible & what's not. No need to bash the idea though.... We should encourage people with ideas to share them, whether they're do-able or not. One idea can spark another that could lay the foundation for a better tomorrow.

**Comment by patricklodder** [comment]
No nerves were hit, you just didn't really think about the implications of what you're proposing. I mean... imagine you'd have to pay royalties to a developer of clean air every time you breathe. That would suck.

Let's not go there & keep Dogecoin free of greed at the protocol level.
