### ISSUE TITLE
[feat] DOGE NEEDS A CAP

### ISSUE THREAD

**Issue by jvulpo** [dogecoin/dogecoin#2213]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by jvulpo** [comment]
can't be infinite.

**Comment by Ordfin** [comment]
It has it already, although a bit hidden.
10k tokens per block, which means an inflation by ~3,9%, decreasing year after year: this is the cap. 
Looking deeper into it, one could reasonably say that DOGE does not belong to inflationary cryptos.

**Comment by AbcSxyZ** [comment]
As said previously, it has already a supply.

You should take a look to this [reddit post](https://www.reddit.com/r/dogecoindev/comments/mtcv04/the_dogefud_faq/) if you want to understand more this "issue".

> Q: Does DOGE have a fixed supply? Does DOGE have a “cap”? Does DOGE have a “hard cap”?
A: Yes, DOGE has a fixed supply of 10,000 coins per block. Yes, there is a “cap” on how many DOGE will exist at any given time. No, DOGE does not have a “hard cap” because there will never be a day when no more DOGE is issued.

You can also take a look at #1674 to see discuss on the subject.

Personally, I do believe it's a bad idea from an economical perspective [if the goal is to make a currency], I wrote about economic impact of deflation : https://github.com/dogecoin/dogecoin/issues/1963#issuecomment-843617890.

As someone commented on reddit:
> Stop using the term "inflation rate" to describe the increase in the money supply. It's just bad economics. Inflation is the increase in cost of things you buy with a currency. An increase in the money supply might cause inflation, but it's not inherently inflationary. The crypto world doesn't even get freshman economics, so it's constantly worrying about something that's just outright wrong.

**Comment by rnicoll** [comment]
We've already said this definitely isn't something this team is willing to do.
