### ISSUE TITLE
Why not work on a pool to switch to all cryptocurrencies (the base currency to switch is Dogecoin). We are adding it to the main Dogecoin website. Thus, it is possible to make the values of other currencies mainly related to Dogecoin or it is possible to increase the market value significantly because it will be an intermediate currency for all cryptocurrencies [feat] 

### ISSUE THREAD

**Issue by dogecoinsharp** [dogecoin/dogecoin#2226]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by rnicoll** [comment]
It's not really clear if you meaning mining pool or exchange, although what you've described is a bit of both...

Keep in mind for every buy, someone has to sell. To exchange from another currency to Dogecoin, someone must have Dogecoin to sell to you. The price they're willing to trade at is set by market demand (as in, if there's a lot of demand, and not a lot of supply, price goes up, and equally vice-versa). You _can_ get mild differences in price based on where the trade occurs, but these rapidly normalise due to a process called arbitrage ( https://www.investopedia.com/terms/a/arbitrage.asp ).

Generally, the best way for Doge to split away from the influence of other crypto prices, is to keep establishing its own usage independent of other cryptos.

Hope that makes sense.

**Comment by rnicoll** [comment]
(also https://dogedex.xyz/ might be relevant, not sure)

**Comment by dogecoinsharp** [comment]
Initially
Thank you for your kind reply
  Second
  I apologize for not explaining my idea well
Third, https://dogedex.xyz/ is a mythical site that everyone around the world should know about this site
  It should be integrated with the main Dogecoin website
Could you please put it on https://www.reddit.com/r/dogecoin/
It will have a huge impact

. My idea is divided into two parts
section One
 is to make the official website look like

https://uniswap.org/
https://pancakeswap.finance/
https://app.1inch.io/#/1/swap/ETH/DAI

The second section I will write in a new  issues thank you again
