### ISSUE TITLE
Priority decreasing per transaction

### ISSUE THREAD

**Issue by Moonynightmare** [dogecoin/dogecoin#2230]
# Feature Request

**Feature Request**
As it is the coin of people, priorities should be done counting transactions of a wallet per day. if it is the first transaction (such send or much receive) of a wallet its prio 1, second is prio 2 etc. like a normal consumer has like 30 Transactions per day . So we could reset the priorisation iterator with the rise of the moon (nightfall). or maybe you can set it to whatever (24+) time you want... to seperate your transactions "in the middle".

**Describe Preferred Solution**

Implement a priority iterator
Implement priority mining
Miners must mine priority transactions. Maybe a stack system is required

**Describe Alternatives**

**Related Code**
Sadly im not deep enough in the DOGE programming. I can try to write some pseudocode:

Priority iterator:
For transactionPerWallet:
     if time > timer + 24:00
          priority=0
     priority=+1
     If priority = 1
          set timer(hh:mm)

Mining Stack:
p1=getSenderWalletPriority
p2=getReceivingWalletPriority 
transactionPriority= LowerPrio(p1,p2)
Insert e at end of transactions to do with the same priority

Miners can mine lower priority through an iterator too after mining some higher priorities. reset to 1 in 10 minutes or something?

**Additional Context**
It could prevent some issues of attacks (fan-in/fan-out).
Consumer will have fast mined transactions.
Please be gentle with me, I'm relatively new to coding ;)

**Comment by patricklodder** [comment]
Besides that you should never reuse an address, so there's no way to tell this without de-anonymizing, assume we would magically do this (won't) and let's do a thought experiment: what if I'm an employer and I am paying out salaries in DOGE? Would you be okay waiting 5 weeks for your money just because you're at the bottom of my list?

**Comment by Moonynightmare** [comment]
ok, isnt it possible to implement the counter directly into the wallet? It was in the back of my head, that the anonymity would suffer because of an additional counter token per transaction. Or are the wallets easy moddable?
the the transaction priority will always be the lower one. so if an employee made like 30 transactions on a day before payment, the transaction is prio 31. if he made no transaction on payment day, the transaction is prio 1.

**Comment by patricklodder** [comment]
> ok, isnt it possible to implement the counter directly into the wallet?

Sure! But then you're de-anonymizing yourself. And how do miners know you're not lying?

I'm closing this here because this idea will not make it into Dogecoin Core.

By all means though, please continue exploring your idea and talk to people about it on reddit though! https://www.reddit.com/r/dogecoindev/

**Comment by Moonynightmare** [comment]
Thanks for the information.
I see, i have a lot to learn.
