### ISSUE TITLE
[feat] DOGE to become a shard on ethereum?

### ISSUE THREAD

**Issue by simonmadsen** [dogecoin/dogecoin#2251]
Would this help DOGE transition to PoS?

If it becomes a shard has ETH then done the hard work?
And will DOGE not need to do as much as if on 'its own'?

Buterin recently spoke of this: https://www.benzinga.com/markets/cryptocurrency/21/06/21424614/vitalik-buterin-says-he-loves-doge-suggests-dogecoin-ethereum-collaboration-for-scalabilit

I own much eth and about half as much doge

**Comment by patricklodder** [comment]
Dogecoin is a sovereign chain so we don't need to "become" someone's shard. However, bridge technology is in it's infancy and we can definitely use more cross-chain tech. Not just to Ethereum, though, think bigger! Cosmos-based chains, Avalanche, Flare, Polkadot, Stellar... all those... We don't have to bet on one horse, we can bet on ALL the horses. Just have to take care of interoperability and [we were just having a discussion about that on reddit.](https://www.reddit.com/r/dogecoindev/comments/nrvg15/vitalik_on_dogecoin_on_the_eth_network/h0mo1jt/)

Let's discuss the possibilities over on reddit, because all this won't necessarily need changes to Dogecoin Core - at least not to get things started!
