### ISSUE TITLE
[feat] Fetch wallet version on client's start

### ISSUE THREAD

**Issue by p-j01** [dogecoin/dogecoin#2310]
# Feature Request

**Describe the Feature Request**

Tips and hints are being added to the main window of Dogecoin Core in PR #2308. One of them is 

> "Make sure to keep your Wallet updated. You can check the current version at https://github.com/dogecoin/dogecoin/releases".

The current wallet version could be fetched on client's start.

**Describe Preferred Solution**

As in PR #2308, the request could be made in `src/qt/overviewpage.cpp` before the new `UpdateTip()` call.
A small icon in the corner could be added in `src/qt/forms/overviewpage.ui` to notify if wallet is up-to-date (i.e. green wallet icon = up-to-date, red wallet icon = out-of-date). 

**Describe Alternatives**

A dialog in `src/qt/forms/overviewpage.ui` that is showed only if the wallet is out-of-date with a `Update Wallet` button.

**Related Code**

https://github.com/dogecoin/dogecoin/blob/fe0b89e3d5966c451358e5285286df9ee0e3aea9/src/qt/overviewpage.cpp#L131

**Comment by AbcSxyZ** [comment]
It can be interesting, but you would request GitHub to get the actual version ? If yes, is it a good idea to query this server at the startup ?

Possibly, if I'm right the current server should just connect to a couple of peers at start, would it be a good thing to rely on a third part ? Actually, it might be a good way to share update, information, or eventually emergency patch, but there is a dependency question.

**Comment by patricklodder** [comment]
Hi! 

Automatic updates - and even notifications towards those - are extremely risky because it depends on someone pressing the release button, and we're actually moving in the opposite direction by not porting alerts back into 1.21; i.e. we remove the last possible source of centralization from Dogecoin Core by removing the alert functionality altogether.  

Please read #296 too as some of this has been discussed in the past and to get some ideas about why this doesn't work. We can discuss further in discussions if you desire.

PS: the tip/hint you quoted will get a NAK from me on that PR if it still exists in the final proposal for similar reasons...

**Comment by p-j01** [comment]
Okay. Is the [mailing list for releases](https://lists.sourceforge.net/lists/listinfo/dogecoin-releases) still in use? Should I close this issue?

**Comment by ReverseControl** [comment]
The consensus by the Core Development Team is any feature request to automatically update Dogecoin Core will be rejected for the foreseeable future. @patricklodder has commented above explaining why. @rnicoll has also explained why on twitter recently where this has come up.
