### ISSUE TITLE
THIS TRANSACTION IS NOT STANDARD AND SHOULD NOT BE TRUSTED [bug] 

### ISSUE THREAD

**Issue by ghoodsite** [dogecoin/dogecoin#2350]
# Bug Report

**Current behavior:**

adding funds to multidoge triggers this error: 
THIS TRANSACTION IS NOT STANDARD AND SHOULD NOT BE TRUSTED

**Expected behavior**

no idea.. much confused

**Steps to reproduce:**

transfer money into the wallet. 
**Screenshots**

**Dogecoin Core version**

**Machine specs**
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

**Extra information**

**Comment by AbcSxyZ** [comment]
Your issue is concerning Multidoge wallet and not the Dogecoin core, not related to this repository. Multidoge is a wallet when dogecoin core is an implementation of the dogecoin protocol, it let you run a node.

You should report your issue to https://github.com/langerhans/multidoge, but the repository is inactive, and you probably won't have any support.
Personal opinion, but until you know what you're doing, wanting to run a node, I wouldn't recommend any of the wallet available on dogecoin.com... Dogecoin core is too big (need blockchain), Multidoge is abandoned...

**Comment by ReverseControl** [comment]
@patricklodder  @rnicoll @michilumin This should be closed.
