### ISSUE TITLE
[feat] Update and Validate Korean Translation Strings

### ISSUE THREAD

**Issue by chromatic** [dogecoin/dogecoin#2529]
# Feature Request

**Describe the Feature Request**

The Korean translations in `src/qt/locale/bitcoin_ko_KR.ts` contain references to "Bitcoin" that have been updated to "Dogecoin" in the source strings in the code.

**Describe Preferred Solution**

Replace "Bitcoin" with "Dogecoin" as appropriate in the translations and validate the accuracy of other translations in this file.

**Comment by dogespacewizard** [comment]
I'm not very good with code so im not sure the right terms for this or even if this is relevant to your post or if its reiterating what you need but but there are 4 instances in the file for the <source> line that use the word 'Bitcoin' instead of 'Dogecoin' in comparison with the bitcoin_en.ts file, the translation for each of these lines however correctly have the Korean term for Dogecoin = "도지코인"

I could replace the instances of "Bitcoin" being used in the 4 <source> lines with "Dogecoin" if needed 

![image](https://user-images.githubusercontent.com/89301283/147127860-bb295b52-6b18-4a01-80b7-8bf589a47789.png)
![image](https://user-images.githubusercontent.com/89301283/147127873-3945e253-629c-4561-99a5-ddd21340a420.png)
![image](https://user-images.githubusercontent.com/89301283/147127889-e6514ec6-9ddb-4d1d-913a-96b1f35a8a6f.png)
![image](https://user-images.githubusercontent.com/89301283/147127898-85829e7e-0d22-4cd6-983b-dc53747b27fc.png)

**Comment by huedaya** [comment]
Based on the English translation, yes you can fix this by replacing Bitcoin to Dogecoin.
https://github.com/dogecoin/dogecoin/blob/31afd133119dd2e15862d46530cb99424cf564b0/src/qt/locale/bitcoin_en.ts#L763-L767

**Comment by patricklodder** [comment]
> I could replace the instances of "Bitcoin" being used in the 4 lines with "Dogecoin" if needed

This should have been taken care of by the automated translation update, maybe something went wrong. I'll create an issue from your comment.

**Comment by dogespacewizard** [comment]
https://github.com/dogecoin/dogecoin/issues/2821#issuecomment-1024430624

my apologies i believe these 4 instances were an issue on my part due to me not knowing how to sync a fork from upstream
upon checking directly from this repo these instances are not existent
again my apologies

**Comment by Ufakeimdope** [comment]
https://open.spotify.com/track/49BdaEKbK8wgcjCiZFn8Mb?si=M7tHTJi8RuW4P8MImhC9iw&utm_source=copy-link
