### ISSUE TITLE
A miner is mining empty blocks

### ISSUE THREAD

**Issue by didlie** [dogecoin/dogecoin#2585]
The network is frequently exploited by miner: DMr3fEiVrPWFpoCWS958zNtqgnFb7QWn9D

The miner appears to exploit the network by starting the hashing process on receipt of unconfirmed blocks, by mining a sequential empty block and submitting the new empty block as soon as the received block in confirmed. The miner is able to steal from the network by mining multiple blocks using (what appears to be) competitive mining hardware to mine sequential blocks before the propagation the most recent block. The miner is not contributing to the network because it consistently mines blocks where the only transaction is the receipt of the 10,000 Dogecoin mining network tax. The miner is not processing other transactions, but is able to strategically exploit and tax the Dogecoin network through advance-mining of empty sequential blocks.

---Suggested network changes to inhibit advance-mining of empty blocks---

1) There should be a network delay of 10 minutes for the acceptance of empty, transaction-less, blocks by the Dogecoin Core network.

**Comment by vertiond** [comment]
This is called block withholding and is a technique that can be advantageous over time when done correctly.  I have confirmed F2Pool to do this practice on the Vertcoin network in the past.  This isn't a network exploit because this miner is simply making the choice to not relay a solved block and instead get started on the next block immediately without spending time doing relay.  Remember that it's a miner's choice to include txs in their blocks.  Ways to help mitigate this is more network hash rate in order to lessen the block withholder's ability to do this and setting fee policy to not be _too_ low such that tx inclusion is not worth it.

**Comment by patricklodder** [comment]
Some context:

1. [They don't just mine empty blocks](https://sochain.com/block/DOGE/355fc5d132dca47f47b2144a45df0698ff824e9e6287f33b0041f5467620d6ef)
2. This particular pool has a history of updating later than the others, so it's possible they are still on 1.14.2. That version has a problem that block relay slows down message processing, including incoming transactions. 
3. Pools will optimize to start work as soon as possible after finding a block (or someone else found one) to keep all that hardware productive; I cannot recall a pool that **waits** for relay to competitors before starting on the next block. 

Besides, even an empty block that does not cause a chaintip fork still helps securing the network.

So before calling anyone parasitic or accusing them of anything and even going as far as proposing consensus changes, without providing any evidence, please elaborate what you mean by the following, including the data you used to come to your conclusions:

1. "exploit the network by starting the hashing process on receipt of unconfirmed blocks"
2. "mining a sequential empty block and submitting the new empty block as soon as the received block [is] confirmed"
3. "steal from the network by mining multiple blocks"
4. "The miner is not contributing to the network"
5. "The miner is not processing other transactions"
6. "strategically exploit and tax the Dogecoin network through advance-mining"

**Comment by didlie** [comment]
The network will never mature because the parasitic blocks are contributing to excessive dilution.

**Comment by ReverseControl** [comment]
@patricklodder To @didlie's point, a significant number of their rewarded blocks appear to have mined no transactions beyond the coinbase. Yes, ``significant`` can be quantified precisely, but I have to write code to get the actual number and I am not up for it at the moment. I just took a look at which blocks have no fees added to the rewarded 10K DOGE. Its clearly noticeable if you do a visual inspection.

**Comment by didlie** [comment]
Empty block mining can and is done strategically. This particular miner mines almost entirely empty blocks. It is irrelevant who the miner is, only that they are imementing a technical startegy to exoit the network, tax the network, and create depreciation and dilution without contributing to the processing of transactions. Of course, mining an empty block will always be possible, but the network must take preference for actual transaction processing, that is the purpose of the mining and network itself. 

---Proposed network upgrade---
1) New blocks with the largest number of orders are prefered in descending order.
2) Empty blocks are delayed by 10 minutes, providing for the mining of transaction-providing blocks, and inhibiting the occasional double-block  intra-minute empty blocks that credit miners for exploiting the network.

**Comment by vertiond** [comment]
Why don't you start by answering Pat's questions?

**Comment by didlie** [comment]
Answering the questions:

1) It is possible this miner is also a member of one or more of the other pools, and found an exploit to send un-mined and/or unconfirmed blocks to process simultaneously through a private hardware pool.

2) The miner associated with this address mines almost entirely empty blocks. It may have mined transaction blocks in the past, but every block I have seen mined by this miner in the past 30 days has been empty, just a simple credit to the address of 10,000 (now giving it a $2000/ minute credit at current market prices, and well worth the effort to struggle to implement exploits.)

3) Every empty block mined while transactions are waiting to be processed delays the function of the network, credits the miner delaying transaction processing with 10,0000 Doge, and dilutes the value of Dogecoin. It is an exploitative theft, and is obviously parasitic.

4)The miner focuses on pushing empty blocks that credit itself, slow down transaction processing from other users by pushing it's empty blocks in place of real transactions, and causing extemporaneous dilution.

5) Look at its mined blocks. It found an exploit to process its own empty blocks. I've been watching it periodically for the past 30 days, and it is obviously the focus of this miner. Again, it's not an attack on the miner. This is a call to inhibit the implementation of this exploit.

6) multipool membership possible: when the difficulty is low on any empty block that block can be easily pushed through if a miner has advance notice of the block before confirmation. By focusing on mining empty blocks, a miner can take unconfirmed blocks from multiple pools and exploit when a sequential empty block can be solved faster than a block containing transactions can be solved.

**Comment by patricklodder** [comment]
Note: you failed to include ANY evidence, but I'll indulge your speculation for the sake of clearing this up. Maybe, if you anger me sufficiently, I will do the research myself out of frustration with your panicking. Know that you are currently keeping me from doing important work though, so I beg you to please bring more evidence, not just accuse and speculate.

> every block I have seen mined by this miner in the past 30 days has been empty

I just linked you a block from today that wasn't empty in my first comment.

> It is an exploitative theft

If it is according to consensus rules then it's not theft, at worst it's a bug. If it's a bug, we need to look into fixing it. What's the bug?

> Every empty block mined while transactions are waiting to be processed delays the function of the network

Correct. But that doesn't mean there is malicious intent. It can be a misconfiguration, problems because of 1.14.2 that were fixed in 1.14.3, or an optimization that the pool is of the opinion does not hurt.

> The miner focuses on pushing empty blocks that credit itself

Every block credits the miner, why would they send the rewards for mining a block to someone else? That's possible and sub-optimal, but not violating consensus rules. If they would do it too often, truly stalling transaction processing, they would cut their own profits because the price of DOGE would go down. So there is an economic disincentive to do that.

> It found an exploit to process its own empty blocks.

That's not an exploit. Look closely at [testnet](https://chain.so/testnet/doge).

> when the difficulty is low on any empty block that block can be easily pushed through if a miner has advance notice of the block before confirmation. By focusing on mining empty blocks, a miner can take unconfirmed blocks from multiple pools and exploit when a sequential empty block can be solved faster than a block containing transactions can be solved.

Correct. So do you expect this to be a bug in [DigiShield](https://github.com/dogecoin/dogecoin/blob/4c93783ab64ba96e60b7ea37202c072c66f3f544/src/dogecoin.cpp#L41-L87)?

> ---Proposed network upgrade---
>
> 1. New blocks with the largest number of orders are prefered in descending order.
> 2. Empty blocks are delayed by 10 minutes, providing for the mining of transaction-providing blocks, and inhibiting the occasional double-block intra-minute empty blocks that credit miners for exploiting the network.

1. I can exploit this by sending DOGE to myself and making full blocks, ie. this proposed rule incentivizes miners to spam the network
2. I can exploit this by sending DOGE to myself without making full blocks, this proposed rule is easily circumvented.

**Comment by patricklodder** [comment]
> @patricklodder To @didlie's point, a significant number of their rewarded blocks appear to have mined no transactions beyond the coinbase. Yes, `significant` can be quantified precisely, but I have to write code to get the actual number and I am not up for it at the moment. I just took a look at which blocks have no fees added to the rewarded 10K DOGE. Its clearly noticeable if you do a visual inspection.

Agree. I am not saying it's not happening. I do want to investigate it, but we have to break this cycle of accusations without evidence. It anyway doesn't help, because Dogecoin is permissionless, so if there is a bug, we identify it, fix it, and propose a soft fork, which will likely take a longer time. 

There is no need to get worked up and do the FUD thing. @langerhans has a gif for this.

**Comment by rnicoll** [comment]
My inclination here is they're badly configured. In particular, if we follow this back; Dogecoin blocks are typically mined by miners also mining Litecoin. I don't have the tools to hand to dump the Litecoin coinbases out of those blocks, but if I pull up recent Litecoin blocks ( https://chain.so/LTC ), it doesn't take long to find the same thing on Litecoin:

* https://chain.so/block/LTC/2128643
* https://chain.so/block/LTC/2128638
* https://chain.so/block/LTC/009b8e3bf4a14da017a9c408eba8f533af74c2b0e9a5acc0430785fc8798ac3c

I don't know who `LTCPodha2LAxSyBGsGfkWcmKDEB8cWrqLU` are, and frustratingly Google doesn't find them, but lets see if we can find out and go "Hey could you fix your relaying" before we hardfork the coin.

In terms of the proposal; blocks are strictly sequential, so delaying an empty block ten minutes actually means empty blocks are not accept until 10 minutes since the previous block, although distributed agreement on time is essentially impossible, so functionally that means we modify the difficulty target for empty blocks by 10x. That's a fairly drastic change, and if they are exploiting something, I presume they'd just pad each block with dummy transactions paying themselves until it past the threshold anyway. Inclusion of transactions is something we fix via economics not technology.

**Comment by patricklodder** [comment]
>  I don't have the tools to hand to dump the Litecoin coinbases out of those blocks

```
$ dogecoin-cli getblock b1f17e3e93cea21f4a3eb2d31aed4cfb7e3f76edbe94aa2fded920ae7c103f9b | jq -r .auxpow.tx.hex | xargs -n 1 litecoin-tx -json
{
    "txid": "835617cd23aee24b9fb6c2ee450e5dda74a1bab3a4ea470a6a27576e7afd0699",
    "hash": "835617cd23aee24b9fb6c2ee450e5dda74a1bab3a4ea470a6a27576e7afd0699",
    "version": 1,
    "size": 200,
    "vsize": 200,
    "weight": 800,
    "locktime": 0,
    "vin": [
        {
            "coinbase": "03bc7a2004614decdb2cfabe6d6d76f2bc62fd678529723dc342ce04f673ad914bd8bb4deb698c760af0c510717e4000000000000000042f4c502f0822f524ee01000000",
            "sequence": 4294967295
        }
    ],
    "vout": [
        {
            "value": 12.54015453,
            "n": 0,
            "scriptPubKey": {
                "asm": "OP_DUP OP_HASH160 57757ed9e2fa7d86636bdd8066078e22cfa19244 OP_EQUALVERIFY OP_CHECKSIG",
                "hex": "76a91457757ed9e2fa7d86636bdd8066078e22cfa1924488ac",
                "reqSigs": 1,
                "type": "pubkeyhash",
                "addresses": [
                    "LTCPodha2LAxSyBGsGfkWcmKDEB8cWrqLU"
                ]
            }
        },
        {
            "value": 0.00000000,
            "n": 1,
            "scriptPubKey": {
                "asm": "OP_RETURN aa21a9ed01d40bee686956b60a860a15dba0d4107afd639799e31e0ff1c90ac5346930e0",
                "hex": "6a24aa21a9ed01d40bee686956b60a860a15dba0d4107afd639799e31e0ff1c90ac5346930e0",
                "type": "nulldata"
            }
        }
    ],
    "hex": "01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff4403bc7a2004614decdb2cfabe6d6d76f2bc62fd678529723dc342ce04f673ad914bd8bb4deb698c760af0c510717e4000000000000000042f4c502f0822f524ee01000000ffffffff02ddc1be4a000000001976a91457757ed9e2fa7d86636bdd8066078e22cfa1924488ac0000000000000000266a24aa21a9ed01d40bee686956b60a860a15dba0d4107afd639799e31e0ff1c90ac5346930e000000000"
}
```

**Comment by patricklodder** [comment]
Also updated https://blockshibe.net to display empty blocks as yellow in the stack-map on the right so that there is live data viz. Will do more later.

**Comment by didlie** [comment]
This is seems an obvious bug. I know the value and utility of the network will improve if this exploit is disallowed.

I endorse the "10x difficulty on empty blocks" proposal.

Donations for discovering this bug are welcome:
DBJXH3mV154TcYHW6AYkM2v5jx4uj2p9QG

I am not a large holder, but I am banking on the value of the Dogecoin network in the long-term.

**Comment by patricklodder** [comment]
> Donations for discovering this bug are welcome:

What's the bug?

**Comment by RosellaGirl87** [comment]
and Elon Musk will launch a DOGE-1 rocket in Q1 2022 What do you think?

**Comment by rnicoll** [comment]
We've identified the pool, going to reach out to them.

**Comment by rnicoll** [comment]
Also having looked at this again, I'm not _that_ convinced we're not just seeing a pool getting lucky with finding the next block, and transaction rate is low enough their mempool is empty when they started working on it.

**Comment by victorsk2019** [comment]
Hello everyone,

I'm still learning how it all works but to address empty block mining issue, would it help to add a checking for empty blocks function in miner.cpp:

`bool BlockAssembler::CheckEmpty()
{
    return (nBlockTx == 0);
}`

And, if it returns 'true', then do not issue 10,000 coins to miner?  I realize this will not prevent someone from filling the block with fake transactions (as mentioned above already), but using safeguard function and not rewarding miner with 10,000 coins for mining empty blocks would perhaps help with this particular issue?

**Comment by didlie** [comment]
@victorsk2019 The issue with this fix is obviously that in the case transaction volume temporarily slows, miners maintaining the network will not be credited for keeping the network running.

---suggested solutions---
Scale difficulty by number of transactions per block, or rather total transaction fees collected, where the collected fees are credited to the miner in place of the flat 10,000 dilution. 
1) Least difficult: So, if the total fees collected are equal or greater than 10,000, the block difficulty will be set at a minimum and the miner will collect all the fees to total 10,000 or more (if transactions fees exceed 10,000). And in this case the network experiences zero dilution.
2) Intermediate difficulty: The total transactions fees are less than 10,000 and the miner is credited the full 10,000, with the dilution being the the difference of 10,000 - transaction fees = dilution of Dogecoin per mined block.
3) Most difficult: There are no transactions in the miner's block. The network experiences a full 10,000 dilution, and the miner is credited 10,000 for mining an empty block.

If possible to implement, this scheme should benefit the network by reducing dilution, inhibit exploitation of the network by miners possibly focusing their efforts on mining empty blocks in advance of legitimate transactions, and at the same time ensure the sustainability of the network by keeping the incentive to mine during a minute empty of submitted transactions.

**Comment by didlie** [comment]
@patricklodder @rnicoll @ReverseControl @vertiond 
yet another empty block by the same miner just now: Block #3912481

**Comment by quackduck** [comment]
> Hello everyone,
> 
> I'm still learning how it all works but to address empty block mining issue, would it help to add a checking for empty blocks function in miner.cpp:
> 
> `bool BlockAssembler::CheckEmpty() { return (nBlockTx == 0); }`
> 
> And, if it returns 'true', then do not issue 10,000 coins to miner? I realize this will not prevent someone from filling the block with fake transactions (as mentioned above already), but using safeguard function and not rewarding miner with 10,000 coins for mining empty blocks would perhaps help with this particular issue?

I mean, they're already incentivized to include TXs by the TX fees.

**Comment by didlie** [comment]
Are you serious? TX fees are tiny! Are you serious? $2000 + or - $0.40 is not incentive.
RE:
> > Hello everyone,
> > I'm still learning how it all works but to address empty block mining issue, would it help to add a checking for empty blocks function in miner.cpp:
> > `bool BlockAssembler::CheckEmpty() { return (nBlockTx == 0); }`
> > And, if it returns 'true', then do not issue 10,000 coins to miner? I realize this will not prevent someone from filling the block with fake transactions (as mentioned above already), but using safeguard function and not rewarding miner with 10,000 coins for mining empty blocks would perhaps help with this particular issue?
> 
> I mean, they're already incentivized to include TXs by the TX fees.

**Comment by quackduck** [comment]
Oop, then it's a good idea I guess?

**Comment by rnicoll** [comment]
Talked to the miner. What's happening is this:

1. Block n is mined.
2. Nodes remove all transactions in block n from the mempool.
3. The miner's node sends the block template for n+1 is sent to their miners. As the mempool is empty, the template is empty.
4. If it's mined before the next template is sent, it generates an empty block.

The template refresh is up to 55 seconds currently, which means if a block is mined in under 55 seconds (give or take) it can come out empty.

So; they're looking at reducing the refresh interval. However, keep in mind this only happens because we have partially full blocks, if the blocks start filling up the "overflow" transactions will be in the next block.

**Comment by patricklodder** [comment]
Since this is an individual miner's configuration, this is not an issue with Dogecoin Core. If anyone feels the need to discuss this further, please use discussions. I am migrating this issue from here to there.
