### ISSUE TITLE
[feat] is it possible to add some ADA features like treasury!?

### ISSUE THREAD

**Issue by vijaychowthri** [dogecoin/dogecoin#2602]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by polska333** [comment]
I want all my missing d o g e back I'm disabled I died once already not too
long ago it's going to happen again I don't know when every month could be
a couple years hopefully it's longer but I'm a very sick person I'm hooked
up to a machine more than half the day now I can't go afford to go out and
buy more I worked hard to get all my crypto and to have it all disappear
from me with no trace of it or anything from some stupid exchange that I
only went on so I could purchase xrp but I liked it so I ended up getting
out of Robin Hood because they have no wallets and purchasing all my doge
there and no one can do anything about it it's like advantage like it never
existed I'm not a liar what I've been through I would never lie again I'm a
very honest person I've always help others and what I'm going through is
horrible I lost 12 years of my life before this I had a lot of crypto that
was on a tablet that people bought for me I kept it on a tablet in my
nursing home I was in a nursing home for over 5 years and one of the CNA
stole my tablet I'll put that what all my information on it and I don't
know then I get finally get out of the nursing home I'm in assisted living
now I get out I use all my stimulus to purchase those I was doing really
good and now all that is gone in a matter of hours the site crashed and
somehow there's no history of it ever I don't know what to do I'm so scared
my doge would keep my mind off my disability and stop me from thinking of
dying it's sad I don't know what to do

**Comment by patricklodder** [comment]
Please: 

> Describe the Feature Request

❤️

**Comment by polska333** [comment]
Is it possible to help someone who's disabled died once already and it's
going to happen again could be months could be years hopefully it's longer
but I am scared and all my doge went missing now because of my disability
unable to purchase more I will build that up for a long time and now it's
all gone for me it disappeared there's no trace of it I do not understand
it and it's impossible to get in touch with the exchange and someone please
help me

**Comment by QuickMythril** [comment]
what exchange?

**Comment by cryptoyoda8** [comment]
If you mean routing a portion of transaction fees or block rewards to developer or marketing wallets, I would advise strongly against it. It hurts decentralization.
