### ISSUE TITLE
[feat] Lower Transaction Fees

### ISSUE THREAD

**Issue by hbeckeri** [dogecoin/dogecoin#2911]
# Feature Request

**Describe the Feature Request**

I'd like to make dogecoin transactions with sub satoshi fees to miners. Ie: 0.5 or 0.25 sats/byte - this will make it possible to do micro transactions on dogecoin. I have a cool project that will make use of this feature and bring a lot of activity to dogecoin

**Describe Preferred Solution**

make it so nodes will accept these transactions

**Comment by cryptowalletr** [comment]
Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by etherx-dev** [comment]
I dont know why limits for fees are hard coded into the wallet, we should have freedom to set out config on official apps.

Dev should remove hardcoded limitations for the wallet.

**Comment by patricklodder** [comment]
@hbeckeri I lost my reply to this somehow, sorry - too many tabs.

The recommendation is there for spam prevention, so to change that, we'd need to have a little bit more information about what you want to do. What pattern do these micro transactions follow (are they repetitive?) and what is the benefit of having them atomically validated by the entire network, rather than going the payment channel route and settling only periodically on-chain? What if the blocks become full (due to lower fees) and the market raises the median fee to something higher than what you currently ask for? Do you need fast confirmation?

The good news is though that with the changes we've delivered with 1.14.4 and 1.14.5, miners (and relay node opers) can configure their nodes to accept any fee or dust limit, including zero fee, so you'd have to convince miners/pools and some relay nodes of your use-case and then `addnode`; you don't really need a change of the recommendation for your desired parametrization to be usable - you just need node operators and miners to agree with you.

I'm also about 70% done with coding a feature (discussed [here](https://github.com/dogecoin/dogecoin/discussions/2624#discussioncomment-1484641)) that will allow nodes to discriminate a part of their outgoing connections based on the fee filter specified by a peer, giving a preference to peers that have an at least as permissive configuration as our own, so that you wouldn't need to use `addnode` per-se. That would enable you to do experiments without having to get a fixed list of participants for your more permissive requirement.

@etherx-dev: we've already removed all fee/dust hard coding in favor of configurable defaults, so your request has already been honored with the 1.14.5 release. However, if you know of anything we've missed, please let us know. It's important that devs do not have full control over how the network is used, because it weakens permissionless usage (and has so in the past - no one wants a repeat of that.)

**Comment by hbeckeri** [comment]
Im working on adding dogecoin transactions to my on chain social network, twetch.com. Users can send small amounts when liking, posting, following etc. If miners are able to choose what fees they accept, then we should be able to do what we need. I agree that miners instead of developers should have control over the network that makes a lot of sense to me

Since we also want to save the data on the dogecoin blockchain of users post, this leads me into my next request for dogecoin. Just as we think miners should be able to accept whatever fees they want to, miners ought to be able to accept how large blocks they'd like to mine. If they mine too large, they risk getting orphaned so there will be some natural economic equilibrium that will form between miners. The merkle tree structure will allow anyone to still verify their own transactions using spv with minimal data, meaning that even really large blocks wont be a barrier for merchants/dogecoin users to verify and validate transactions they receive

**Comment by patricklodder** [comment]
The problem is that you're basically asking every node operator to store your stuff for centuries, even if they don't use your app. So the cost of operating a node will grow significantly.

How do you plan to compensate Dogecoin node operators for this?

**Comment by hbeckeri** [comment]
Closing this as the feature already exists
