### ISSUE TITLE
 Holding transactions because of low fee

### ISSUE THREAD

**Issue by 123trudy** [dogecoin/dogecoin#2920]
It's not a good thing for transactions to be left behind because of fee this really costs alot sometimes its not what you want but it happens anyway  put the rates that every one will not face this kind of issues.

**Comment by patricklodder** [comment]
Hi! Did you mean you want us to publish [these rates](https://github.com/dogecoin/dogecoin/blob/master/doc/fee-recommendation.md) differently?

What wallet did you run into fee rate issues with?

**Comment by 123trudy** [comment]
I used Trust wallet  but they are holding my transaction it's not delivered
to where i sent it  due  to the low fee, what can i do for it to be
delivered?

**Comment by patricklodder** [comment]
Do you have a transaction id for us to look at?

**Comment by 123trudy** [comment]
787bdfc7811da5738cbde5d2876679bfd4cd461e759c272fa2f7ca1ecb6cafc8

**Comment by patricklodder** [comment]
That's strange: that's exactly [a 1.5 day old Bitcoin transaction hash](https://blockchair.com/bitcoin/transaction/787bdfc7811da5738cbde5d2876679bfd4cd461e759c272fa2f7ca1ecb6cafc8) (the chances of having exactly the same transaction hash on Dogecoin are astronomically small) so this is very likely to be a different issue. 

Please contact Trust Wallet support - if they need help figuring this out, I can make myself available to look into the matter.

**Comment by 123trudy** [comment]
I did open a ticket  yesterday informing them about it but up to now i
didn't get any response from them,
 I do not know really where the problem  could be , i need  help if you can
assist me  please  do i don't even know how long will this take to be
cleared.

**Comment by 123trudy** [comment]
Hallo  the balance i have circle is the one i sent,  it's just appearing
there how do we move it to total spend so it will be reflected in the
address it was sent too?

Please  do your level best and  assist with this issue  please  sir/ ma'am
Your assistance will be highly appreciated thank you.

**Comment by 123trudy** [comment]
Hallo  you didnt come back to me on the solution about my issue  it's still not delivered,  what can I do?

**Comment by patricklodder** [comment]
Hi!

I'm sorry, no one here can fix this issue for you because the Dogecoin network will always reject that bitcoin transaction you gave us because the source of these coins do not exist on the Dogecoin chain. 

You'll have to pick this up with Trust Wallet's team because we cannot possibly know what went wrong in their software. If it turns out that they have a problem integrating with the Dogecoin network or the software maintained in this repository, we will definitely help them with troubleshooting and finding a solution, but there simply isn't a way for us to do anything for you without more details from the Trust Wallet team.

**Comment by Administratordes** [comment]
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/

**Comment by Administratordes** [comment]
> Hallo you didnt come back to me on the solution about my issue it's still not delivered, what can I do?

Check the Livechat link i sent and open that to rectify your issue

**Comment by daank-c** [comment]
There were [3 bug reports](https://github.com/trustwallet/wallet-core/issues?q=is%3Aissue+is%3Aclosed+doge) in the Trust wallet-core repo from this time period (April-May). These issues seem to be regarding similar issues (fee thresholds not being met, held up txns).

These issues have since been closed.
