### ISSUE TITLE
P2PKH Dev/Basic addresses

### ISSUE THREAD

**Issue by Loopite** [dogecoin/dogecoin#3093]
# Bug Report

**Current behavior:** I use this address (P2PKH): AF3trXVo9LwoJsM1XigvMBxWGt7yYATp8t to receive. But I don't receive any coins even though I have this transaction: [https://dogechain.info/tx/39b7b1f2fd31926e45ee220fe73eb0172cf2875c8fb90caf82232ce1996b4b1b](https://dogechain.info/tx/39b7b1f2fd31926e45ee220fe73eb0172cf2875c8fb90caf82232ce1996b4b1b).

**Expected behavior:** The address ``AF3trXVo9LwoJsM1XigvMBxWGt7yYATp8t`` is decodable in base58. There's its content:
```
16 f80f8998314a24769c4bd1fd4954379a0baed082 3f270965
|  |                                        | 
|  |                                        Double SHA-256 (checksum of the Network prefix and the hashed publicKey)
|  20 bytes which contain the hash160 of the elliptic curve secp256k1 public key.
Network prefix 'A'
```
The bug is I have the original address which is ``DTkijPt6pneorLThj5MUEC8oJvBXCsmxFo`` and the privateKey associated. And the expectation is that the software compares only the hashed publicKey and receive my transaction. Because, if I'm not getting wrong, ``AF3trXVo9LwoJsM1XigvMBxWGt7yYATp8t`` is the same **hashed public key** of ``DTkijPt6pneorLThj5MUEC8oJvBXCsmxFo``. So transactions sent to ``AF3trXVo9LwoJsM1XigvMBxWGt7yYATp8t`` could be received with ``DTkijPt6pneorLThj5MUEC8oJvBXCsmxFo`` in the **mainnet**.

**Steps to reproduce:**
All you have to do is to get your hashed public key and to prepend the network byte and append the checksum. You'll have to decode/encode in base58 with [https://appdevtools.com/base58-encoder-decoder](https://appdevtools.com/base58-encoder-decoder) for example.

**Screenshots**
![image](https://user-images.githubusercontent.com/70860774/183295293-f6e8f9f7-4632-4ff7-8c08-b3b9020f9a39.png)
*You can't see my transaction right there.*

**Dogecoin Core version**
Dogecoin Core 1.14.6.0-3a29ba6d4

**Machine specs**
- **OS**: Windows 11 Pro, 64-bit, v.21H2, build.22000.795
- **CPU**: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz
- **RAM**: 32.0 GB (31.8 GB usable)
- **Disk size**: 2,198,430,826,496 bytes (1.99 TB), **Free space**: 1,131,232,337,920 bytes (1.02 TB).
- **Disk Type** (HD/SDD): HD

**Extra information**
I would you to tell me more on the payment method that I use. It's a little bit confusing. I hope you'll be able to help me,
Best wishes.

**Comment by patricklodder** [comment]
Hi,

Network prefixes with byte `0x16` are p2sh addresses, not p2pkh addresses; see: https://github.com/dogecoin/dogecoin/blob/3a29ba6d497cd1d0a32ecb039da0d35ea43c9c85/src/chainparams.cpp#L168

This means that the hash you are looking at `f80f8998314a24769c4bd1fd4954379a0baed082` is not the digest for a public key but for a script for these coins to be able to be spent.

We can see this by looking at the output of the transaction you link:

1. parse the tx
2. extract the output script for the address you mention 
3. parse it with `decodescript`

```bash
dogecoin-cli getrawtransaction 39b7b1f2fd31926e45ee220fe73eb0172cf2875c8fb90caf82232ce1996b4b1b true \
    | jq -r '.vout[].scriptPubKey | select(.addresses[0] == "AF3trXVo9LwoJsM1XigvMBxWGt7yYATp8t") | .hex' \
    | xargs -n 1 dogecoin-cli decodescript
```

```json
{
  "asm": "OP_HASH160 f80f8998314a24769c4bd1fd4954379a0baed082 OP_EQUAL",
  "reqSigs": 1,
  "type": "scripthash",
  "addresses": [
    "AF3trXVo9LwoJsM1XigvMBxWGt7yYATp8t"
  ]
}
```

Note that this says it's a script hash, which is correct because the prefix of the address is `0x16`. You cannot spend these coins with a public key that hashes into `f80f8998314a24769c4bd1fd4954379a0baed082` - only scripts.

if you want to us a p2pkh output, use prefix `0x1e` for the address, per: https://github.com/dogecoin/dogecoin/blob/3a29ba6d497cd1d0a32ecb039da0d35ea43c9c85/src/chainparams.cpp#L167
