### ISSUE TITLE
[feat]  Add a warning wen setting up the Core Wallet that it will broadcast his IP

### ISSUE THREAD

**Issue by qlpqlp** [dogecoin/dogecoin#3151]
# Feature Request

**Describe the Feature Request**
Wen installing the Core Wallet, display a warning that his IP will be broadcast to other peers, and the shibe should always protect themselves with an VPN or setup a TOR connection for safety

**Describe Preferred Solution**
On Setup display a warning with a checkbox to agree and continue the installation

**Describe Alternatives**
Display a warning on GIT Readme on the Download section

**Additional Context**
There is concerns on the Core Wallet were there are shibes that do not know the IP os broadcast to other peers.

**Comment by patricklodder** [comment]
TOR is activated automatically when present, we're working on the update here: #3149

Will you, in return, [adhere to point 5 of our spider rules](https://github.com/dogecoin/dogecoin/blob/master/doc/dnsseed-policy.md)?

> 5. Information gathered as a result of the operators node-spidering (not from DNS queries) may be freely published or retained, but only if this data was not made more complete by biasing node connectivity (a violation of expectation (1)).

**Comment by qlpqlp** [comment]
Did not know about it. Thanks for letting me know :)

I did not know also about the point 5 of spidering.

So int theory, I can collect and share publicly all nodes IP's and information on the JSON that the Core shares, I only cant add more information like for example were the IP is registered to get the location

Is that correct?

**Comment by patricklodder** [comment]
No. What it says is you have to spider using the protocol, which means you need to process all `addr` responses, and you are not allowed to only publish nodes that you actually connected to or that connected to you. You have to publish everything.

**Comment by qlpqlp** [comment]
I will try to read with more attention all of it, just dinner time here, but will try to ask some more questions to you if you dont mind to help me understand. I dont want to expose anyone, and much less to put anyone in danger in anyway :)

**Comment by michilumin** [comment]
@qlpqlp - please stop. Your map is getting broadly negative response and defending it in these channels is looking worse and worse. It's a neat trick, but generally, node runners do not want to be geolocated. Yes, we all know that anyone can do it with effort but all security exists on a sliding scale of difficulty.   Cost (making node runners uncomfortable) vs benefit (knowing where nodes are geographically) of having a map of this data does not balance towards the benefit side. 

It actually is very likely to be a *disincentive* to node running.

I'm asking you as strongly as I can: please stop pushing and trying to justify this mapping effort.

**Comment by michilumin** [comment]
Fine by me, as I actually have further concerns on this. For one, torv3 will actually make setting up wireless nodes easier (CGNAT issues); but moreso, these nodes run unmanned. (Currently takes me 3 hours drive to get to one of them.)  Due to the nature of these links, they're actually a lot easier to locate if the main base station is found (thanks, physics) and by their nature tend to be in remote locations.  

Simple device theft and physical direction finding is a much bigger concern for these nodes, so I would say that torv3 would be a great benefit; as I would hope that the hub/relay itself could be obfuscated from being simply geolocated. Can't DF the (straight-line) spokes if you can't locate the hub.  

This differs from wired hub-and-spoke networks where the spokes only exist in a 'logical direction', not a physical straight-line direction. (people are not going to fuser-monitor, then dig and pull up fiber to get to your house.)

Also -- repeaters/antennas/towers tend to be kinda big and high up, so rough geoloc of the hub is all that would be needed. Our circle of confusion there tends to be a visual one, counted in miles/km. 

So bright side I guess this did highlight some further (completely above-board) need for tor functionality.
