### ISSUE TITLE
How to validate hash ?

### ISSUE THREAD

**Issue by Tamir198** [dogecoin/dogecoin#3263]
Hey, I am currently using [crypto api](https://cryptoapis.io/) to get dogecoin blocks (I am using test environment).

I am having 2 questions: 

1) I got this block  from the crypto api REST API: 

```
{
    apiVersion: '2021-03-20',
    requestId: '63a8dcc64f82f75cfd2ef2df',
    context: 'yourExampleString',
    data: {
      item: {
        hash: 'a830f0d97f819c54023fbe5f596633f5fab362b6f03b19433a98b5512c85efad',
        height: 4194680,
        previousBlockHash:
          'bc82d7a130b3a7362681ecc9a012425b5a4fd6b1517a3e0be7c2d76887612a12',
        timestamp: 1672010904,
        transactionsCount: 1,
        blockchainSpecific: {
          bits: '503398104',
          chainwork:
            '000000000000000000000000000000000000000000000000003f06c765599a86',
          difficulty: '0.0000043136284594604528',
          merkleRoot:
            'e6f1844b6feb22a1ac4ea73aae53e671e643a4efc49fc30dbee7ca5a3315d362',
          nonce: 2496922688,
          size: 195,
          strippedSize: 195,
          version: 6422532,
          weight: 780,
        },
      },
    },
  };
```

I saw a lot of ways to calculate the hash from this block. but I am not sure what is the best way.

2) Let's say that I have solved this block and got some hash, how can I validate the hash?

**Comment by Loopite** [comment]
Hi,

1. You should know there's plenty of 'HASH' algorithms. Dogecoin uses Scrypt to validate Proof-Of-Work and SHA256double (SHA256d) to update the TIP of chain. In your example, you can see that the used algorithm is SHA256double (Otherwise, with Scrypt, there'd be a lot of NULL bytes: 000000, it's the POW principe). The SHA256d is the same as: SHA256(SHA256(**BLOCK HEADER**)).

* BLOCK HEADER =
```
BLOCK VERSION  + PREV. BLOCK. HASH + MERKLE ROOT + TIME                + BITS                + NONCE
(4 bytes LE32) + (32 bytes)        + (32 bytes)  + (4 bytes LE32)      + (4 bytes LE32)      + (4 bytes LE32) = 4 + 32 + 32 + 4 + 4 + 4 = 80 bytes in raw.
```

Notes: 
- LE32 = Little-Endian Bytes Order 32 **bits** <=> 4 bytes.

Example in your JSON case: **/!\ BITS FIELD IS MISSING**

```
1ST     HASH = SHA256d(04006200 122a618768d7c2e70b3e7a51b1d64f5a5b4212a0c9ec812636a7b330a1d782bc 62d315335acae7be0dc39fc4efa443e671e653ae3aa74eaca122eb6f4b84f1e6 98dca863 d83e011e 4004d494)
2ND <=> HASH = SHA256(SHA256(04006200122a618768d7c2e70b3e7a51b1d64f5a5b4212a0c9ec812636a7b330a1d782bc62d315335acae7be0dc39fc4efa443e671e653ae3aa74eaca122eb6f4b84f1e698dca863d83e011e4004d494))
3RD <=> HASH = SHA256(7ae090d3b23fbc8977ac44b58c1f5ec3b3cd55ad2b90f80909dcd545d9d94138)
4TH <=> HASH = adef852c51b5983a43193bf0b662b3faf53366595fbe3f02549c817fd9f030a8
5TH <=> HASH = a830f0d97f819c54023fbe5f596633f5fab362b6f03b19433a98b5512c85efad
```
(Realized with a couple of BYTES-SWAP without software)

Notes:
- The API has displayed the **Hash**, **Previous Block Hash** and the **Merkle Root** fields in a LE32 way. Because the original HASH is the 4th line on my calculus.

2. When you have "found" this block, you have to perform a SCRYPT on the BlockHeader. And, you must verify your Hash is under the uncompressed bits field.

Example with BITCOIN:

```
    GENESIS_HASH = 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
    GENESIS_BITS = 1d00ffff
<=> UNCOMPRESSED_BITS = 00000000ffff0000000000000000000000000000000000000000000000000000
    COMPUTATION:
    000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f (32 bytes)
<?  00000000ffff0000000000000000000000000000000000000000000000000000 (32 bytes)
YES because 0x00 <= 0x00 && 0x00 < 0xff && 0x19 < 0xff
 => Proof-Of-Work on this block is valid.
```
You don't even need a 256 bits bignum library to verify it. You can do it with a simple for loop.

Loopite.

**Comment by Tamir198** [comment]
Thank you, I really appreciate your detailed answer
