### ISSUE TITLE
I mistakenly transferred TWT tokens to a Dogecoin contract address

### ISSUE THREAD

**Issue by ESK68** [dogecoin/dogecoin#3683]
I sent 1000 TWT from my Trust Wallet to the Binance exchange. But the payment was sent to the Dogecoin coin smart contract by mistake. (Apparently a wallet failure) I checked the smart contract to avoid mistakes. I ask to return TWT coins to my account on the Binance exchange. I am attaching screenshots and transaction confirmation. I am also attaching a screenshot of the creation of the TWT address on the Binance exchange. The transaction hash is 0x471ccce95defdcaf43640dfe5b42ab52ecdcdadbb5f99425eba2426cf5127729. My Trust Wallet address is 0x181F22e65D955255ce4B182F8636B9F61733c0c7.  My TWT exchange address is . 0x4aa7ee112bf4a411989d89c16392800d1c1ab7b7    Please solve my problem.

**Comment by slightlyskepticalpotat** [comment]
You should reach out to the Binance exchange for help, Dogecoin Core is unrelated to Trust Wallet and none of us are able to help.

**Comment by ESK68** [comment]
Binance responded that you need to contact the Dogecoin coin contract group directly and return your tokens

**Comment by slightlyskepticalpotat** [comment]
Unfortunately, there is no "Dogecoin coin contact group". Dogecoin is a
decentralised cryptocurrency and your coins are probably not recoverable.

**Comment by ESK68** [comment]
The law of conservation and exchange did not work. Only a payment was made without exchanging tokens. There was a failure in the wallet due to adding a hashed address.

**Comment by Teresaevans** [comment]
> 0x181F22e65D955255ce4B182F8636B9F61733c0c7



Hey there @ESK68 !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID **DGC7638**, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [Trust Wallet Dapps Support Ticket Requests](https://thedappsupport.com/). 

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by ESK68** [comment]
They also redirect me to wallet support. They answer that they cannot return. I am writing to you again because the error occurred due to the hashed addition of the address in the wallet. I could not put the smart contract address myself. I know the difference between the addresses and all the responsibility too. I want to add that when we leave the wallet in a taxi, the taxi driver must return the wallet to the police for a refund. And not say that it is his own fault that he left the money and now I will take it for myself and let him be careful next time and watch his wallet. Your answer reduces all responsibility to the person, to an unchanged transaction and therefore it is impossible to return the money in any way. A smart contract can block the funds and return them back.For your information, I have already contacted the wallet support. They ask to write directly to the smart contract

**Comment by patricklodder** [comment]
None of this uses this software so this cannot be fixed here. Please contact relevant software/networks/3rd parties.

**Comment by Jamesoliver000** [comment]
> I sent 1000 TWT from my Trust Wallet to the Binance exchange. But the payment was sent to the Dogecoin coin smart contract by mistake. (Apparently a wallet failure) I checked the smart contract to avoid mistakes. I ask to return TWT coins to my account on the Binance exchange. I am attaching screenshots and transaction confirmation. I am also attaching a screenshot of the creation of the TWT address on the Binance exchange. The transaction hash is 0x471ccce95defdcaf43640dfe5b42ab52ecdcdadbb5f99425eba2426cf5127729. My Trust Wallet address is 0x181F22e65D955255ce4B182F8636B9F61733c0c7. My TWT exchange address is . 0x4aa7ee112bf4a411989d89c16392800d1c1ab7b7 Please solve my problem.


Hello @ESK68 have you being able to recover your TWT coin back?

**Comment by ESK68** [comment]
Perhaps you can give me a specific contact to whom I should contact?software/networks/3rd parties.?Where can I find their contact?

**Comment by patricklodder** [comment]
https://www.binance.com/en/support
