### ISSUE TITLE
Transaction Stuck and not showing on chain.so

### ISSUE THREAD

**Issue by SokratesOne** [dogecoin/dogecoin#3703]
I have the problem, that my transaction of ~1155 Dodge, that i sent through the Dogecoin Core wallet, has been stuck for almost 2 weeks now. Since its my first transaction of a bigger amount i didnt know, that i should increase the fee (made the transaction with the lowest fee).
I let the wallet fully sync since then, to see if that would fix the problem. But [chain.so](http://chain.so/) still doesnt show my transaction.

Is there anything I can do to get the transaction through or the money back into my wallet to resend it?

**Comment by Angiepeck22** [comment]
Hello @SokratesOne 
I hope your issue is resolved by now. If not, I apologize for the delay. It seems you're facing a transcript error,It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID DOG07638
Please see the link below to our dedicated support line:
[Dogecoin Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
