### ISSUE TITLE
Compile 1.8.1 ,ld returned  1 Error, printing paper wallets

### ISSUE THREAD

**Issue by cqtenq** [dogecoin/dogecoin#779]
when I compile 1.8.1 with printing paper wallets, I have an error. 

src\qt/utilitydialog.cpp:243: undefined reference to 'QPrinter::QPrinter(QPrinter::PrinterMode)'
src\qt/utilitydialog.cpp:244: undefined reference to 'QPrintDialog::QPrintDialog(QPrinter*, QWidget*)'

How to fix ?

**Comment by ypid** [comment]
I found this issue via Google because I had a similar error while migrating [cdcat](https://github.com/ypid/cdcat) to QT5. I solved it by adding 'QT += printsupport' to [cdcat.pro](https://github.com/ypid/cdcat/blob/a34591cda657f848a0cdd2fb7fb0f400ded24f99/src/cdcat.pro#L246). Maybe that helps. I found this hint here: http://www.qt-italia.org/forum/viewtopic.php?f=10&t=1184

**Comment by patricklodder** [comment]
@rnicoll is this fixed now with #1224?

**Comment by rnicoll** [comment]
Yes, fixed in https://github.com/dogecoin/dogecoin/commit/a245210cbe01b4f3f2ba7321958768e1df3df5e3 which adds printsupport as suggested.
