### ISSUE TITLE
Improve return filtering on built in miner

### ISSUE THREAD

**Issue by rnicoll** [dogecoin/dogecoin#922]
The built in miner has a fixed number of zeroes it looks for before returning. This is very difficult to balance effectively, for test/regtest difficulties can be in the single bits range, whereas for main network it's closer to a few bytes if not more.

Want to look at ways of efficiently testing 1-32 bits of the hash before returning, depending on target difficulty, but not worth looking at until later in the 1.9 cycle.

**Comment by wolf9466** [comment]
If you're suggesting doing a different test based on the diff, you're branching (twice, one for the test, one for the test result), which will take a LOT more time than you save by changing the test.

If you're suggesting something else, than the BSF instruction (bit scan forward) should help you. Its return value is undefined if you pass it zero, but it sets ZF in that case - so you'll be able to test any amount of bits quite simply, by modifying the result such that instead of counting trailing zeroes, it finds the first set bit.
